export const jaToEn = new Map([
  ["ひかりのこな", "Bright Powder"],
  ["せんせいのツメ", "Quick Claw"],
  ["おうじゃのしるし", "King's Rock"],
  ["ぎんのこな", "Silver Powder"],
  ["おまもりこばん", "Amulet Coin"],
  ["きよめのおふだ", "Cleanse Tag"],
  ["けむりだま", "Smoke Ball"],
  ["かわらずのいし", "Everstone"],
  ["きあいのハチマキ", "Focus Band"],
  ["しあわせタマゴ", "Lucky Egg"],
  ["ピントレンズ", "Scope Lens"],
  ["メタルコート", "Metal Coat"],
  ["たべのこし", "Leftovers"],
  ["りゅうのウロコ", "Dragon Scale"],
  ["でんきだま", "Light Ball"],
  ["やわらかいすな", "Soft Sand"],
  ["かたいいし", "Hard Stone"],
  ["きせきのタネ", "Miracle Seed"],
  ["くろいメガネ", "Black Glasses"],
  ["くろおび", "Black Belt"],
  ["じしゃく", "Magnet"],
  ["しんぴのしずく", "Mystic Water"],
  ["するどいくちばし", "Sharp Beak"],
  ["どくバリ", "Poison Barb"],
  ["とけないこおり", "Never-Melt Ice"],
  ["のろいのおふだ", "Spell Tag"],
  ["まがったスプーン", "Twisted Spoon"],
  ["もくたん", "Charcoal"],
  ["りゅうのキバ", "Dragon Fang"],
  ["ピンクのリボン", "Pink Bow"],
  ["みずたまリボン", "Polkadot Bow"],
  ["アップグレード", "Up-Grade"],
  ["ラッキーパンチ", "Lucky Punch"],
  ["メタルパウダー", "Metal Powder"],
  ["ふといホネ", "Thick Club"],
  ["ながねぎ", "Stick Leek"],
  ["はかいのいでんし", "Berserk Gene"],
  ["しろいハーブ", "White Herb"],
  ["きょうせいギプス", "Macho Brace"],
  ["やすらぎのすず", "Soothe Bell"],
  ["メンタルハーブ", "Mental Herb"],
  ["こだわりハチマキ", "Choice Band"],
  ["こころのしずく", "Soul Dew"],
  ["しんかいのキバ", "Deep Sea Tooth"],
  ["しんかいのウロコ", "Deep Sea Scale"],
  ["シルクのスカーフ", "Silk Scarf"],
  ["かいがらのすず", "Shell Bell"],
  ["うしおのおこう", "Sea Incense"],
  ["のんきのおこう", "Lax Incense"],
  ["あかいバンダナ", "Red Scarf"],
  ["あおいバンダナ", "Blue Scarf"],
  ["ピンクのバンダナ", "Pink Scarf"],
  ["みどりのバンダナ", "Green Scarf"],
  ["きいろのバンダナ", "Yellow Scarf"],
  ["べにいろのたま", "Red Orb"],
  ["あいいろのたま", "Blue Orb"],
  ["ひのたまプレート", "Flame Plate"],
  ["しずくプレート", "Splash Plate"],
  ["いかずちプレート", "Zap Plate"],
  ["みどりのプレート", "Meadow Plate"],
  ["つららのプレート", "Icicle Plate"],
  ["こぶしのプレート", "Fist Plate"],
  ["もうどくプレート", "Toxic Plate"],
  ["だいちのプレート", "Earth Plate"],
  ["あおぞらプレート", "Sky Plate"],
  ["ふしぎのプレート", "Mind Plate"],
  ["たまむしプレート", "Insect Plate"],
  ["がんせきプレート", "Stone Plate"],
  ["もののけプレート", "Spooky Plate"],
  ["りゅうのプレート", "Draco Plate"],
  ["こわもてプレート", "Dread Plate"],
  ["こうてつプレート", "Iron Plate"],
  ["あやしいおこう", "Odd Incense"],
  ["がんせきおこう", "Rock Incense"],
  ["まんぷくおこう", "Full Incense"],
  ["さざなみのおこう", "Wave Incense"],
  ["おはなのおこう", "Rose Incense"],
  ["こううんのおこう", "Luck Incense"],
  ["きよめのおこう", "Pure Incense"],
  ["プロテクター", "Protector"],
  ["エレキブースター", "Electirizer"],
  ["マグマブースター", "Magmarizer"],
  ["あやしいパッチ", "Dubious Disc"],
  ["れいかいのぬの", "Reaper Cloth"],
  ["するどいツメ", "Razor Claw"],
  ["するどいキバ", "Razor Fang"],
  ["まんまるいし", "Oval Stone"],
  ["こんごうだま", "Adamant Orb"],
  ["しらたま", "Lustrous Orb"],
  ["はっきんだま", "Griseous Orb"],
  ["こうかくレンズ", "Wide Lens"],
  ["ちからのハチマキ", "Muscle Band"],
  ["きあいのタスキ", "Focus Sash"],
  ["ものしりメガネ", "Wise Glasses"],
  ["たつじんのおび", "Expert Belt"],
  ["ひかりのねんど", "Light Clay"],
  ["いのちのたま", "Life Orb"],
  ["パワフルハーブ", "Power Herb"],
  ["どくどくだま", "Toxic Orb"],
  ["かえんだま", "Flame Orb"],
  ["スピードパウダー", "Quick Powder"],
  ["フォーカスレンズ", "Zoom Lens"],
  ["メトロノーム", "Metronome"],
  ["くろいてっきゅう", "Iron Ball"],
  ["こうこうのしっぽ", "Lagging Tail"],
  ["あかいいと", "Destiny Knot"],
  ["くろいヘドロ", "Black Sludge"],
  ["つめたいいわ", "Icy Rock"],
  ["さらさらいわ", "Smooth Rock"],
  ["あついいわ", "Heat Rock"],
  ["しめったいわ", "Damp Rock"],
  ["ねばりのかぎづめ", "Grip Claw"],
  ["こだわりスカーフ", "Choice Scarf"],
  ["くっつきバリ", "Sticky Barb"],
  ["パワーリスト", "Power Bracer"],
  ["パワーベルト", "Power Belt"],
  ["パワーレンズ", "Power Lens"],
  ["パワーバンド", "Power Band"],
  ["パワーアンクル", "Power Anklet"],
  ["パワーウエイト", "Power Weight"],
  ["きれいなぬけがら", "Shed Shell"],
  ["おおきなねっこ", "Big Root"],
  ["こだわりメガネ", "Choice Specs"],
  ["アクアカセット", "Douse Drive"],
  ["イナズマカセット", "Shock Drive"],
  ["ブレイズカセット", "Burn Drive"],
  ["フリーズカセット", "Chill Drive"],
  ["きれいなウロコ", "Prism Scale"],
  ["しんかのきせき", "Eviolite"],
  ["かるいし", "Float Stone"],
  ["ゴツゴツメット", "Rocky Helmet"],
  ["ふうせん", "Air Balloon"],
  ["レッドカード", "Red Card"],
  ["ねらいのまと", "Ring Target"],
  ["しめつけバンド", "Binding Band"],
  ["きゅうこん", "Absorb Bulb"],
  ["じゅうでんち", "Cell Battery"],
  ["だっしゅつボタン", "Eject Button"],
  ["ほのおのジュエル", "Fire Gem"],
  ["みずのジュエル", "Water Gem"],
  ["でんきのジュエル", "Electric Gem"],
  ["くさのジュエル", "Grass Gem"],
  ["こおりのジュエル", "Ice Gem"],
  ["かくとうジュエル", "Fighting Gem"],
  ["どくのジュエル", "Poison Gem"],
  ["じめんのジュエル", "Ground Gem"],
  ["ひこうのジュエル", "Flying Gem"],
  ["エスパージュエル", "Psychic Gem"],
  ["むしのジュエル", "Bug Gem"],
  ["いわのジュエル", "Rock Gem"],
  ["ゴーストジュエル", "Ghost Gem"],
  ["ドラゴンジュエル", "Dragon Gem"],
  ["あくのジュエル", "Dark Gem"],
  ["はがねのジュエル", "Steel Gem"],
  ["ノーマルジュエル", "Normal Gem"],
  ["じゃくてんほけん", "Weakness Policy"],
  ["とつげきチョッキ", "Assault Vest"],
  ["せいれいプレート", "Pixie Plate"],
  ["ホイップポップ", "Whipped Dream"],
  ["においぶくろ", "Sachet"],
  ["ひかりごけ", "Luminous Moss"],
  ["ゆきだま", "Snowball"],
  ["ぼうじんゴーグル", "Safety Goggles"],
  ["ゲンガナイト", "Gengarite"],
  ["サーナイトナイト", "Gardevoirite"],
  ["デンリュウナイト", "Ampharosite"],
  ["フシギバナイト", "Venusaurite"],
  ["リザードナイトX", "Charizardite X"],
  ["リザードナイトY", "Charizardite Y"],
  ["カメックスナイト", "Blastoisinite"],
  ["ミュウツナイトX", "Mewtwonite X"],
  ["ミュウツナイトY", "Mewtwonite Y"],
  ["バシャーモナイト", "Blazikenite"],
  ["チャーレムナイト", "Medichamite"],
  ["ヘルガナイト", "Houndoominite"],
  ["ボスゴドラナイト", "Aggronite"],
  ["ジュペッタナイト", "Banettite"],
  ["バンギラスナイト", "Tyranitarite"],
  ["ハッサムナイト", "Scizorite"],
  ["カイロスナイト", "Pinsirite"],
  ["プテラナイト", "Aerodactylite"],
  ["ルカリオナイト", "Lucarionite"],
  ["ユキノオナイト", "Abomasite"],
  ["ガルーラナイト", "Kangaskhanite"],
  ["ギャラドスナイト", "Gyaradosite"],
  ["アブソルナイト", "Absolite"],
  ["フーディナイト", "Alakazite"],
  ["ヘラクロスナイト", "Heracronite"],
  ["クチートナイト", "Mawilite"],
  ["ライボルトナイト", "Manectite"],
  ["ガブリアスナイト", "Garchompite"],
  ["ラティアスナイト", "Latiasite"],
  ["ラティオスナイト", "Latiosite"],
  ["ラグラージナイト", "Swampertite"],
  ["ジュカインナイト", "Sceptilite"],
  ["ヤミラミナイト", "Sablenite"],
  ["チルタリスナイト", "Altarianite"],
  ["エルレイドナイト", "Galladite"],
  ["タブンネナイト", "Audinite"],
  ["メタグロスナイト", "Metagrossite"],
  ["サメハダナイト", "Sharpedonite"],
  ["ヤドランナイト", "Slowbronite"],
  ["ハガネールナイト", "Steelixite"],
  ["ピジョットナイト", "Pidgeotite"],
  ["オニゴーリナイト", "Glalitite"],
  ["ディアンシナイト", "Diancite"],
  ["バクーダナイト", "Cameruptite"],
  ["ミミロップナイト", "Lopunnite"],
  ["ボーマンダナイト", "Salamencite"],
  ["スピアナイト", "Beedrillite"],
  ["ノーマルZ", "Normalium Z"],
  ["ホノオZ", "Firium Z"],
  ["ミズZ", "Waterium Z"],
  ["デンキZ", "Electrium Z"],
  ["クサZ", "Grassium Z"],
  ["コオリZ", "Icium Z"],
  ["カクトウZ", "Fightinium Z"],
  ["ドクZ", "Poisonium Z"],
  ["ジメンZ", "Groundium Z"],
  ["ヒコウZ", "Flyinium Z"],
  ["エスパーZ", "Psychium Z"],
  ["ムシZ", "Buginium Z"],
  ["イワZ", "Rockium Z"],
  ["ゴーストZ", "Ghostium Z"],
  ["ドラゴンZ", "Dragonium Z"],
  ["アクZ", "Darkinium Z"],
  ["ハガネZ", "Steelium Z"],
  ["フェアリーZ", "Fairium Z"],
  ["ピカチュウZ", "Pikanium Z"],
  ["サトピカZ", "Pikashunium Z"],
  ["アロライZ", "Aloraichium Z"],
  ["イーブイZ", "Eevium Z"],
  ["カビゴンZ", "Snorlium Z"],
  ["ミュウZ", "Mewnium Z"],
  ["ジュナイパーZ", "Decidium Z"],
  ["ガオガエンZ", "Incinium Z"],
  ["アシレーヌZ", "Primarium Z"],
  ["カプZ", "Tapunium Z"],
  ["マーシャドーZ", "Marshadium Z"],
  ["ソルガレオZ", "Solganium Z"],
  ["ルナアーラZ", "Lunalium Z"],
  ["ウルトラネクロZ", "Ultranecrozium Z"],
  ["ミミッキュZ", "Mimikium Z"],
  ["ルガルガンZ", "Lycanium Z"],
  ["ジャラランガZ", "Kommonium Z"],
  ["ファイヤーメモリ", "Fire Memory"],
  ["ウオーターメモリ", "Water Memory"],
  ["グラスメモリ", "Grass Memory"],
  ["エレクトロメモリ", "Electric Memory"],
  ["アイスメモリ", "Ice Memory"],
  ["ファイトメモリ", "Fighting Memory"],
  ["ポイズンメモリ", "Poison Memory"],
  ["グラウンドメモリ", "Ground Memory"],
  ["フライングメモリ", "Flying Memory"],
  ["サイキックメモリ", "Psychic Memory"],
  ["バグメモリ", "Bug Memory"],
  ["ロックメモリ", "Rock Memory"],
  ["ゴーストメモリ", "Ghost Memory"],
  ["ドラゴンメモリ", "Dragon Memory"],
  ["ダークメモリ", "Dark Memory"],
  ["スチールメモリ", "Steel Memory"],
  ["フェアリーメモリ", "Fairy Memory"],
  ["エレキシード", "Electric Seed"],
  ["グラスシード", "Grassy Seed"],
  ["ミストシード", "Misty Seed"],
  ["サイコシード", "Psychic Seed"],
  ["グランドコート", "Terrain Extender"],
  ["ぼうごパット", "Protective Pads"],
  ["ルームサービス", "Room Service"],
  ["だっしゅつパック", "Eject Pack"],
  ["あつぞこブーツ", "Heavy-Duty Boots"],
  ["からぶりほけん", "Blunder Policy"],
  ["のどスプレー", "Throat Spray"],
  ["ばんのうがさ", "Utility Umbrella"],
  ["くちたけん", "Rusted Sword"],
  ["くちたたて", "Rusted Shield"],
  ["いかさまダイス", "Loaded Dice"],
  ["おんみつマント", "Covert Cloak"],
  ["クリアチャーム", "Clear Amulet"],
  ["とくせいガード", "Ability Shield"],
  ["パンチグローブ", "Punching Glove"],
  ["ブーストエナジー", "Booster Energy"],
  ["ものまねハーブ", "Mirror Herb"],
  ["だいこんごうだま", "Adamant Crystal"],
  ["だいしらたま", "Lustrous Globe"],
  ["だいはっきんだま", "Griseous Core"],
  ["ようせいのハネ", "Fairy Feather"],
  ["いどのめん", "Wellspring Mask"],
  ["かまどのめん", "Hearthflame Mask"],
  ["いしずえのめん", "Cornerstone Mask"],
  ["クラボのみ", "Cheri Berry"],
  ["カゴのみ", "Chesto Berry"],
  ["モモンのみ", "Pecha Berry"],
  ["チーゴのみ", "Rawst Berry"],
  ["ナナシのみ", "Aspear Berry"],
  ["ヒメリのみ", "Leppa Berry"],
  ["オレンのみ", "Oran Berry"],
  ["キーのみ", "Persim Berry"],
  ["ラムのみ", "Lum Berry"],
  ["オボンのみ", "Sitrus Berry"],
  ["フィラのみ", "Figy Berry"],
  ["ウイのみ", "Wiki Berry"],
  ["マゴのみ", "Mago Berry"],
  ["バンジのみ", "Aguav Berry"],
  ["イアのみ", "Iapapa Berry"],
  ["ズリのみ", "Razz Berry"],
  ["ブリーのみ", "Bluk Berry"],
  ["ナナのみ", "Nanab Berry"],
  ["セシナのみ", "Wepear Berry"],
  ["パイルのみ", "Pinap Berry"],
  ["ザロクのみ", "Pomeg Berry"],
  ["ネコブのみ", "Kelpsy Berry"],
  ["タポルのみ", "Qualot Berry"],
  ["ロメのみ", "Hondew Berry"],
  ["ウブのみ", "Grepa Berry"],
  ["マトマのみ", "Tamato Berry"],
  ["モコシのみ", "Cornn Berry"],
  ["ゴスのみ", "Magost Berry"],
  ["ラブタのみ", "Rabuta Berry"],
  ["ノメルのみ", "Nomel Berry"],
  ["ノワキのみ", "Spelon Berry"],
  ["シーヤのみ", "Pamtre Berry"],
  ["カイスのみ", "Watmel Berry"],
  ["ドリのみ", "Durin Berry"],
  ["ベリブのみ", "Belue Berry"],
  ["チイラのみ", "Liechi Berry"],
  ["リュガのみ", "Ganlon Berry"],
  ["カムラのみ", "Salac Berry"],
  ["ヤタピのみ", "Petaya Berry"],
  ["ズアのみ", "Apicot Berry"],
  ["サンのみ", "Lansat Berry"],
  ["スターのみ", "Starf Berry"],
  ["ナゾのみ", "Enigma Berry"],
  ["オッカのみ", "Occa Berry"],
  ["イトケのみ", "Passho Berry"],
  ["ソクノのみ", "Wacan Berry"],
  ["リンドのみ", "Rindo Berry"],
  ["ヤチェのみ", "Yache Berry"],
  ["ヨプのみ", "Chople Berry"],
  ["ビアーのみ", "Kebia Berry"],
  ["シュカのみ", "Shuca Berry"],
  ["バコウのみ", "Coba Berry"],
  ["ウタンのみ", "Payapa Berry"],
  ["タンガのみ", "Tanga Berry"],
  ["ヨロギのみ", "Charti Berry"],
  ["カシブのみ", "Kasib Berry"],
  ["ハバンのみ", "Haban Berry"],
  ["ナモのみ", "Colbur Berry"],
  ["リリバのみ", "Babiri Berry"],
  ["ホズのみ", "Chilan Berry"],
  ["ミクルのみ", "Micle Berry"],
  ["イバンのみ", "Custap Berry"],
  ["ジャポのみ", "Jaboca Berry"],
  ["レンブのみ", "Rowap Berry"],
  ["ロゼルのみ", "Roseli Berry"],
  ["アッキのみ", "Kee Berry"],
  ["タラプのみ", "Maranga Berry"],
  ["ポフのみ", "Hopo Berry"]
]);

export const frToEn = new Map([
  ["Poudre Claire", "Bright Powder"],
  ["Vive Griffe", "Quick Claw"],
  ["Roche Royale", "King's Rock"],
  ["Poudre Argentée", "Silver Powder"],
  ["Piece Rune", "Amulet Coin"],
  ["Rune Purifiante", "Cleanse Tag"],
  ["Boule Fumée", "Smoke Ball"],
  ["Pierre Stase", "Everstone"],
  ["Bandeau", "Focus Band"],
  ["Œuf Chance", "Lucky Egg"],
  ["Lentilscope", "Scope Lens"],
  ["Peau Metal", "Metal Coat"],
  ["Restes", "Leftovers"],
  ["Écaille Draco", "Dragon Scale"],
  ["Ballelumiere", "Light Ball"],
  ["Sable Doux", "Soft Sand"],
  ["Pierre Dure", "Hard Stone"],
  ["Grain Miracle", "Miracle Seed"],
  ["Lunettes Noires", "Black Glasses"],
  ["Ceinture Noire", "Black Belt"],
  ["Aimant", "Magnet"],
  ["Eau Mystique", "Mystic Water"],
  ["Bec Pointu", "Sharp Beak"],
  ["Pic Venin", "Poison Barb"],
  ["Glace Éternelle", "Never-Melt Ice"],
  ["Rune Sort", "Spell Tag"],
  ["Cuiller Tordue", "Twisted Spoon"],
  ["Charbon", "Charcoal"],
  ["Croc Dragon", "Dragon Fang"],
  ["Ruban Rose", "Pink Bow"],
  ["Ruban a Pois", "Polkadot Bow"],
  ["Améliorator", "Up-Grade"],
  ["Poing Chance", "Lucky Punch"],
  ["Poudre Metal", "Metal Powder"],
  ["Masse Os", "Thick Club"],
  ["Baton Poireau", "Stick Leek"],
  ["ADN Berzerk", "Berserk Gene"],
  ["Herbe Blanche", "White Herb"],
  ["Bracelet Macho", "Macho Brace"],
  ["Grelot Zen", "Soothe Bell"],
  ["Herbe Mental", "Mental Herb"],
  ["Bandeau Choix", "Choice Band"],
  ["Rosée Âme", "Soul Dew"],
  ["Dent Océan", "Deep Sea Tooth"],
  ["Écaille Océan", "Deep Sea Scale"],
  ["Mouchoir Soie", "Silk Scarf"],
  ["Grelot Coque", "Shell Bell"],
  ["Encens Mer", "Sea Incense"],
  ["Encens Doux", "Lax Incense"],
  ["Foul. Rouge", "Red Scarf"],
  ["Foul. Bleu", "Blue Scarf"],
  ["Foul. Rose", "Pink Scarf"],
  ["Foul. Vert", "Green Scarf"],
  ["Foul. Jaune", "Yellow Scarf"],
  ["Orbe Rouge", "Red Orb"],
  ["Orbe Bleu", "Blue Orb"],
  ["Plaque Flam", "Flame Plate"],
  ["Plaque Hydro", "Splash Plate"],
  ["Plaque Volt", "Zap Plate"],
  ["Plaque Herbe", "Meadow Plate"],
  ["Plaque Glace", "Icicle Plate"],
  ["Plaque Poing", "Fist Plate"],
  ["Plaque Toxic", "Toxic Plate"],
  ["Plaque Terre", "Earth Plate"],
  ["Plaque Ciel", "Sky Plate"],
  ["Plaque Esprit", "Mind Plate"],
  ["Plaquinsect", "Insect Plate"],
  ["Plaque Roc", "Stone Plate"],
  ["Plaque Fantô", "Spooky Plate"],
  ["Plaque Draco", "Draco Plate"],
  ["Plaque Ombre", "Dread Plate"],
  ["Plaque Fer", "Iron Plate"],
  ["Encens Bizarre", "Odd Incense"],
  ["Encens Roc", "Rock Incense"],
  ["Encens Plein", "Full Incense"],
  ["Encens Vague", "Wave Incense"],
  ["Encens Fleur", "Rose Incense"],
  ["Encens Veine", "Luck Incense"],
  ["Encens Pur", "Pure Incense"],
  ["Protecteur", "Protector"],
  ["Électiriseur", "Electirizer"],
  ["Magmariseur", "Magmarizer"],
  ["CD Douteux", "Dubious Disc"],
  ["Tissu Fauche", "Reaper Cloth"],
  ["Griffe Rasoir", "Razor Claw"],
  ["Croc Rasoir", "Razor Fang"],
  ["Pierre Ovale", "Oval Stone"],
  ["Orbe Adamant", "Adamant Orb"],
  ["Orbe Perlé", "Lustrous Orb"],
  ["Orbe Platiné", "Griseous Orb"],
  ["Loupe", "Wide Lens"],
  ["Bandeau Muscle", "Muscle Band"],
  ["Ceinture Force", "Focus Sash"],
  ["Lunettes Sages", "Wise Glasses"],
  ["Ceinture Pro", "Expert Belt"],
  ["Lumargile", "Light Clay"],
  ["Orbe Vie", "Life Orb"],
  ["Herbe Pouvoir", "Power Herb"],
  ["Orbe Toxique", "Toxic Orb"],
  ["Orbe Flamme", "Flame Orb"],
  ["Poudre Vite", "Quick Powder"],
  ["Lentille Zoom", "Zoom Lens"],
  ["Métronome", "Metronome"],
  ["Balle Fer", "Iron Ball"],
  ["Ralentiqueue", "Lagging Tail"],
  ["Nœud Destin", "Destiny Knot"],
  ["Boue Noire", "Black Sludge"],
  ["Roche Glace", "Icy Rock"],
  ["Roche Lisse", "Smooth Rock"],
  ["Roche Chaude", "Heat Rock"],
  ["Roche Humide", "Damp Rock"],
  ["Accro Griffe", "Grip Claw"],
  ["Mouchoir Choix", "Choice Scarf"],
  ["Piquants", "Sticky Barb"],
  ["Poignée Pouvoir", "Power Bracer"],
  ["Ceinture Pouvoir", "Power Belt"],
  ["Lentille Pouvoir", "Power Lens"],
  ["Bandeau Pouvoir", "Power Band"],
  ["Chaîne Pouvoir", "Power Anklet"],
  ["Poids Pouvoir", "Power Weight"],
  ["Carapace Mue", "Shed Shell"],
  ["Grosse Racine", "Big Root"],
  ["Lunettes Choix", "Choice Specs"],
  ["Module Aqua", "Douse Drive"],
  ["Module Choc", "Shock Drive"],
  ["Module Pyro", "Burn Drive"],
  ["Module Cryo", "Chill Drive"],
  ["Bel'Écaille", "Prism Scale"],
  ["Évoluroc", "Eviolite"],
  ["Pierrallégée", "Float Stone"],
  ["Casque Brut", "Rocky Helmet"],
  ["Ballon", "Air Balloon"],
  ["Carton Rouge", "Red Card"],
  ["Point de Mire", "Ring Target"],
  ["Bande Étreinte", "Binding Band"],
  ["Bulbe", "Absorb Bulb"],
  ["Pile", "Cell Battery"],
  ["Bouton Fuite", "Eject Button"],
  ["Joyau Feu", "Fire Gem"],
  ["Joyau Eau", "Water Gem"],
  ["Joyau Électr", "Electric Gem"],
  ["Joyau Plante", "Grass Gem"],
  ["Joyau Glace", "Ice Gem"],
  ["Joyau Combat", "Fighting Gem"],
  ["Joyau Poison", "Poison Gem"],
  ["Joyau Sol", "Ground Gem"],
  ["Joyau Vol", "Flying Gem"],
  ["Joyau Psy", "Psychic Gem"],
  ["Joyau Insect", "Bug Gem"],
  ["Joyau Roche", "Rock Gem"],
  ["Joyau Spectr", "Ghost Gem"],
  ["Joyau Dragon", "Dragon Gem"],
  ["Joyau Ténèbr", "Dark Gem"],
  ["Joyau Acier", "Steel Gem"],
  ["Joyau Normal", "Normal Gem"],
  ["Vulné-Assurance", "Weakness Policy"],
  ["Veste de Combat", "Assault Vest"],
  ["Plaque Pixie", "Pixie Plate"],
  ["Chantibonbon", "Whipped Dream"],
  ["Sachet Senteur", "Sachet"],
  ["Lichen Lumineux", "Luminous Moss"],
  ["Boule de Neige", "Snowball"],
  ["Lunettes Filtre", "Safety Goggles"],
  ["Ectoplasmite", "Gengarite"],
  ["Gardevoirite", "Gardevoirite"],
  ["Pharampite", "Ampharosite"],
  ["Florizarrite", "Venusaurite"],
  ["Dracaufite X", "Charizardite X"],
  ["Dracaufite Y", "Charizardite Y"],
  ["Tortankite", "Blastoisinite"],
  ["Mewtwoïte X", "Mewtwonite X"],
  ["Mewtwoïte Y", "Mewtwonite Y"],
  ["Braségalite", "Blazikenite"],
  ["Charminite", "Medichamite"],
  ["Démolossite", "Houndoominite"],
  ["Galekingite", "Aggronite"],
  ["Branettite", "Banettite"],
  ["Tyranocivite", "Tyranitarite"],
  ["Cizayoxite", "Scizorite"],
  ["Scarabruite", "Pinsirite"],
  ["Ptéraïte", "Aerodactylite"],
  ["Lucarite", "Lucarionite"],
  ["Blizzarite", "Abomasite"],
  ["Kangourexite", "Kangaskhanite"],
  ["Léviatorite", "Gyaradosite"],
  ["Absolite", "Absolite"],
  ["Alakazamite", "Alakazite"],
  ["Scarhinoïte", "Heracronite"],
  ["Mysdibulite", "Mawilite"],
  ["Élecsprintite", "Manectite"],
  ["Carchacrokite", "Garchompite"],
  ["Latiasite", "Latiasite"],
  ["Latiosite", "Latiosite"],
  ["Laggronite", "Swampertite"],
  ["Jungkite", "Sceptilite"],
  ["Ténéfixite", "Sablenite"],
  ["Altarite", "Altarianite"],
  ["Gallamite", "Galladite"],
  ["Nanméouïte", "Audinite"],
  ["Métalossite", "Metagrossite"],
  ["Sharpedite", "Sharpedonite"],
  ["Flagadossite", "Slowbronite"],
  ["Steelixite", "Steelixite"],
  ["Roucarnagite", "Pidgeotite"],
  ["Oniglalite", "Glalitite"],
  ["Diancite", "Diancite"],
  ["Caméruptite", "Cameruptite"],
  ["Lockpinite", "Lopunnite"],
  ["Drattakite", "Salamencite"],
  ["Dardargnite", "Beedrillite"],
  ["Normazélite", "Normalium Z"],
  ["Pyrozélite", "Firium Z"],
  ["Aquazélite", "Waterium Z"],
  ["Voltazélite", "Electrium Z"],
  ["Florazélite", "Grassium Z"],
  ["Cryozélite", "Icium Z"],
  ["Combazélite", "Fightinium Z"],
  ["Toxizélite", "Poisonium Z"],
  ["Terrazélite", "Groundium Z"],
  ["Aérozélite", "Flyinium Z"],
  ["Psychézélite", "Psychium Z"],
  ["Insectozélite", "Buginium Z"],
  ["Rocazélite", "Rockium Z"],
  ["Spectrozélite", "Ghostium Z"],
  ["Dracozélite", "Dragonium Z"],
  ["Ténébrozélite", "Darkinium Z"],
  ["Métallozélite", "Steelium Z"],
  ["Nymphézélite", "Fairium Z"],
  ["Pikazélite", "Pikanium Z"],
  ["Pikachazélite", "Pikashunium Z"],
  ["Aloraïzélite", "Aloraichium Z"],
  ["Évolizélite", "Eevium Z"],
  ["Ronflézélite", "Snorlium Z"],
  ["Mewzélite", "Mewnium Z"],
  ["Archézélite", "Decidium Z"],
  ["Félinozélite", "Incinium Z"],
  ["Oratozélite", "Primarium Z"],
  ["Tokozélite", "Tapunium Z"],
  ["Marshadozélite", "Marshadium Z"],
  ["Solgazélite", "Solganium Z"],
  ["Lunazélite", "Lunalium Z"],
  ["Ultranécrozélite", "Ultranecrozium Z"],
  ["Mimiquizélite", "Mimikium Z"],
  ["Lougarozélite", "Lycanium Z"],
  ["Ékaïzélite", "Kommonium Z"],
  ["ROM Feu", "Fire Memory"],
  ["ROM Eau", "Water Memory"],
  ["ROM Plante", "Grass Memory"],
  ["ROM Électrik", "Electric Memory"],
  ["ROM Glace", "Ice Memory"],
  ["ROM Combat", "Fighting Memory"],
  ["ROM Poison", "Poison Memory"],
  ["ROM Sol", "Ground Memory"],
  ["ROM Vol", "Flying Memory"],
  ["ROM Psy", "Psychic Memory"],
  ["ROM Insecte", "Bug Memory"],
  ["ROM Roche", "Rock Memory"],
  ["ROM Spectre", "Ghost Memory"],
  ["ROM Dragon", "Dragon Memory"],
  ["ROM Ténèbres", "Dark Memory"],
  ["ROM Acier", "Steel Memory"],
  ["ROM Fée", "Fairy Memory"],
  ["Graine Électrik", "Electric Seed"],
  ["Graine Herbe", "Grassy Seed"],
  ["Graine Brume", "Misty Seed"],
  ["Graine Psycho", "Psychic Seed"],
  ["Champ’Duit", "Terrain Extender"],
  ["Pare-Effet", "Protective Pads"],
  ["Chariot Distordu", "Room Service"],
  ["Sac Fuite", "Eject Pack"],
  ["Grosses Bottes", "Heavy-Duty Boots"],
  ["Assurance Échec", "Blunder Policy"],
  ["Spray Gorge", "Throat Spray"],
  ["Parapluie Solide", "Utility Umbrella"],
  ["Épée Rouillée", "Rusted Sword"],
  ["Bouclier Rouillé", "Rusted Shield"],
  ["Dé Pipé", "Loaded Dice"],
  ["Cape Obscure", "Covert Cloak"],
  ["Talisman Sain", "Clear Amulet"],
  ["Garde-Talent", "Ability Shield"],
  ["Gant de Boxe", "Punching Glove"],
  ["Énergie Booster", "Booster Energy"],
  ["Feuille Copieuse", "Mirror Herb"],
  ["Globe Adamant", "Adamant Crystal"],
  ["Globe Perlé", "Lustrous Globe"],
  ["Globe Platiné", "Griseous Core"],
  ["Plume Enchantée", "Fairy Feather"],
  ["Masque du Puits", "Wellspring Mask"],
  ["Masque du Fourneau", "Hearthflame Mask"],
  ["Masque de la Pierre", "Cornerstone Mask"],
  ["Baie Ceriz", "Cheri Berry"],
  ["Baie Maron", "Chesto Berry"],
  ["Baie Pecha", "Pecha Berry"],
  ["Baie Fraive", "Rawst Berry"],
  ["Baie Willia", "Aspear Berry"],
  ["Baie Mepo", "Leppa Berry"],
  ["Baie Oran", "Oran Berry"],
  ["Baie Kika", "Persim Berry"],
  ["Baie Prine", "Lum Berry"],
  ["Baie Sitrus", "Sitrus Berry"],
  ["Baie Figuy", "Figy Berry"],
  ["Baie Wiki", "Wiki Berry"],
  ["Baie Mago", "Mago Berry"],
  ["Baie Gowav", "Aguav Berry"],
  ["Baie Papaya", "Iapapa Berry"],
  ["Baie Framby", "Razz Berry"],
  ["Baie Remu", "Bluk Berry"],
  ["Baie Nanab", "Nanab Berry"],
  ["Baie Repoi", "Wepear Berry"],
  ["Baie Nanana", "Pinap Berry"],
  ["Baie Grena", "Pomeg Berry"],
  ["Baie Alga", "Kelpsy Berry"],
  ["Baie Qualot", "Qualot Berry"],
  ["Baie Lonme", "Hondew Berry"],
  ["Baie Resin", "Grepa Berry"],
  ["Baie Tamato", "Tamato Berry"],
  ["Baie Siam", "Cornn Berry"],
  ["Baie Mangou", "Magost Berry"],
  ["Baie Rabuta", "Rabuta Berry"],
  ["Baie Tronci", "Nomel Berry"],
  ["Baie Kiwan", "Spelon Berry"],
  ["Baie Palma", "Pamtre Berry"],
  ["Baie Stekpa", "Watmel Berry"],
  ["Baie Durin", "Durin Berry"],
  ["Baie Myrte", "Belue Berry"],
  ["Baie Lichii", "Liechi Berry"],
  ["Baie Lingan", "Ganlon Berry"],
  ["Baie Sailak", "Salac Berry"],
  ["Baie Pitaye", "Petaya Berry"],
  ["Baie Abriko", "Apicot Berry"],
  ["Baie Lansat", "Lansat Berry"],
  ["Baie Frista", "Starf Berry"],
  ["Baie Enigma", "Enigma Berry"],
  ["Baie Chocco", "Occa Berry"],
  ["Baie Pocpoc", "Passho Berry"],
  ["Baie Parma", "Wacan Berry"],
  ["Baie Ratam", "Rindo Berry"],
  ["Baie Nanone", "Yache Berry"],
  ["Baie Pomroz", "Chople Berry"],
  ["Baie Kébia", "Kebia Berry"],
  ["Baie Jouca", "Shuca Berry"],
  ["Baie Cobaba", "Coba Berry"],
  ["Baie Yapap", "Payapa Berry"],
  ["Baie Panga", "Tanga Berry"],
  ["Baie Charti", "Charti Berry"],
  ["Baie Sédra", "Kasib Berry"],
  ["Baie Fraigo", "Haban Berry"],
  ["Baie Lampou", "Colbur Berry"],
  ["Baie Babiri", "Babiri Berry"],
  ["Baie Zalis", "Chilan Berry"],
  ["Baie Micle", "Micle Berry"],
  ["Baie Chérim", "Custap Berry"],
  ["Baie Jacoba", "Jaboca Berry"],
  ["Baie Pommo", "Rowap Berry"],
  ["Baie Selro", "Roseli Berry"],
  ["Baie Éka", "Kee Berry"],
  ["Baie Rangma", "Maranga Berry"],
  ["Baie Bouhlon", "Hopo Berry"]
]);

export const deToEn = new Map([
  ["Blendpuder", "Bright Powder"],
  ["Flinkklaue", "Quick Claw"],
  ["King-Stein", "King's Rock"],
  ["Silberstaub", "Silver Powder"],
  ["Münzamulett", "Amulet Coin"],
  ["Schutzband", "Cleanse Tag"],
  ["Rauchball", "Smoke Ball"],
  ["Ewigstein", "Everstone"],
  ["Fokus-Band", "Focus Band"],
  ["Glücks-Ei", "Lucky Egg"],
  ["Scope-Linse", "Scope Lens"],
  ["Metallmantel", "Metal Coat"],
  ["Überreste", "Leftovers"],
  ["Drachenhaut", "Dragon Scale"],
  ["Kugelblitz", "Light Ball"],
  ["Pudersand", "Soft Sand"],
  ["Granitstein", "Hard Stone"],
  ["Wundersaat", "Miracle Seed"],
  ["Schattenglas", "Black Glasses"],
  ["Schwarzgurt", "Black Belt"],
  ["Magnet", "Magnet"],
  ["Zauberwasser", "Mystic Water"],
  ["Hackattack", "Sharp Beak"],
  ["Giftstich", "Poison Barb"],
  ["Ewiges Eis", "Never-Melt Ice"],
  ["Bannsticker", "Spell Tag"],
  ["Krümmlöffel", "Twisted Spoon"],
  ["Holzkohle", "Charcoal"],
  ["Drachenzahn", "Dragon Fang"],
  ["Rosa Band", "Pink Bow"],
  ["Punkt-Band", "Polkadot Bow"],
  ["Up-Grade", "Up-Grade"],
  ["Lucky Punch", "Lucky Punch"],
  ["Metallstaub", "Metal Powder"],
  ["Kampfknochen", "Thick Club"],
  ["Lauchstange", "Stick Leek"],
  ["Berserk-Gen", "Berserk Gene"],
  ["Schlohkraut", "White Herb"],
  ["Machoband", "Macho Brace"],
  ["Sanftglocke", "Soothe Bell"],
  ["Mentalkraut", "Mental Herb"],
  ["Wahlband", "Choice Band"],
  ["Seelentau", "Soul Dew"],
  ["Abysszahn", "Deep Sea Tooth"],
  ["Abyssplatte", "Deep Sea Scale"],
  ["Seidenschal", "Silk Scarf"],
  ["Seegesang", "Shell Bell"],
  ["Seerauch", "Sea Incense"],
  ["Laxrauch", "Lax Incense"],
  ["Roter Schal", "Red Scarf"],
  ["Blauer Schal", "Blue Scarf"],
  ["Rosa Schal", "Pink Scarf"],
  ["Grüner Schal", "Green Scarf"],
  ["Gelber Schal", "Yellow Scarf"],
  ["Rote Kugel", "Red Orb"],
  ["Blaue Kugel", "Blue Orb"],
  ["Feuertafel", "Flame Plate"],
  ["Wassertafel", "Splash Plate"],
  ["Blitztafel", "Zap Plate"],
  ["Wiesentafel", "Meadow Plate"],
  ["Frosttafel", "Icicle Plate"],
  ["Fausttafel", "Fist Plate"],
  ["Gifttafel", "Toxic Plate"],
  ["Erdtafel", "Earth Plate"],
  ["Wolkentafel", "Sky Plate"],
  ["Hirntafel", "Mind Plate"],
  ["Käfertafel", "Insect Plate"],
  ["Steintafel", "Stone Plate"],
  ["Spuktafel", "Spooky Plate"],
  ["Dracotafel", "Draco Plate"],
  ["Furchttafel", "Dread Plate"],
  ["Eisentafel", "Iron Plate"],
  ["Schrägrauch", "Odd Incense"],
  ["Steinrauch", "Rock Incense"],
  ["Lahmrauch", "Full Incense"],
  ["Wellenrauch", "Wave Incense"],
  ["Rosenrauch", "Rose Incense"],
  ["Glücksrauch", "Luck Incense"],
  ["Scheuchrauch", "Pure Incense"],
  ["Schützer", "Protector"],
  ["Stromisierer", "Electirizer"],
  ["Magmaisierer", "Magmarizer"],
  ["Dubiosdisc", "Dubious Disc"],
  ["Düsterumhang", "Reaper Cloth"],
  ["Scharfklaue", "Razor Claw"],
  ["Scharfzahn", "Razor Fang"],
  ["Ovaler Stein", "Oval Stone"],
  ["Adamant-Orb", "Adamant Orb"],
  ["Weiß-Orb", "Lustrous Orb"],
  ["Platinum-Orb", "Griseous Orb"],
  ["Großlinse", "Wide Lens"],
  ["Muskelband", "Muscle Band"],
  ["Fokusgurt", "Focus Sash"],
  ["Schlauglas", "Wise Glasses"],
  ["Expertengurt", "Expert Belt"],
  ["Lichtlehm", "Light Clay"],
  ["Leben-Orb", "Life Orb"],
  ["Energiekraut", "Power Herb"],
  ["Toxik-Orb", "Toxic Orb"],
  ["Heiß-Orb", "Flame Orb"],
  ["Flottstaub", "Quick Powder"],
  ["Zoomlinse", "Zoom Lens"],
  ["Metronom", "Metronome"],
  ["Eisenkugel", "Iron Ball"],
  ["Schwerschwf.", "Lagging Tail"],
  ["Fatumknoten", "Destiny Knot"],
  ["Giftschleim", "Black Sludge"],
  ["Eisbrocken", "Icy Rock"],
  ["Glattbrocken", "Smooth Rock"],
  ["Heißbrocken", "Heat Rock"],
  ["Nassbrocken", "Damp Rock"],
  ["Griffklaue", "Grip Claw"],
  ["Wahlschal", "Choice Scarf"],
  ["Klettdorn", "Sticky Barb"],
  ["Machtreif", "Power Bracer"],
  ["Machtgurt", "Power Belt"],
  ["Machtlinse", "Power Lens"],
  ["Machtband", "Power Band"],
  ["Machtkette", "Power Anklet"],
  ["Machtgewicht", "Power Weight"],
  ["Wechselhülle", "Shed Shell"],
  ["Großwurzel", "Big Root"],
  ["Wahlglas", "Choice Specs"],
  ["Aquamodul", "Douse Drive"],
  ["Blitzmodul", "Shock Drive"],
  ["Flammenmodul", "Burn Drive"],
  ["Gefriermodul", "Chill Drive"],
  ["Schönschuppe", "Prism Scale"],
  ["Evolith", "Eviolite"],
  ["Leichtstein", "Float Stone"],
  ["Beulenhelm", "Rocky Helmet"],
  ["Luftballon", "Air Balloon"],
  ["Rote Karte", "Red Card"],
  ["Zielscheibe", "Ring Target"],
  ["Klammerband", "Binding Band"],
  ["Knolle", "Absorb Bulb"],
  ["Akku", "Cell Battery"],
  ["Fluchtknopf", "Eject Button"],
  ["Feuerjuwel", "Fire Gem"],
  ["Wasserjuwel", "Water Gem"],
  ["Elektrojuwel", "Electric Gem"],
  ["Pflanzjuwel", "Grass Gem"],
  ["Eisjuwel", "Ice Gem"],
  ["Kampfjuwel", "Fighting Gem"],
  ["Giftjuwel", "Poison Gem"],
  ["Bodenjuwel", "Ground Gem"],
  ["Flugjuwel", "Flying Gem"],
  ["Psychojuwel", "Psychic Gem"],
  ["Käferjuwel", "Bug Gem"],
  ["Gesteinjuwel", "Rock Gem"],
  ["Geistjuwel", "Ghost Gem"],
  ["Drakojuwel", "Dragon Gem"],
  ["Unlichtjuwel", "Dark Gem"],
  ["Stahljuwel", "Steel Gem"],
  ["Normaljuwel", "Normal Gem"],
  ["Schwächenschutz", "Weakness Policy"],
  ["Offensivweste", "Assault Vest"],
  ["Feentafel", "Pixie Plate"],
  ["Sahnehäubchen", "Whipped Dream"],
  ["Duftbeutel", "Sachet"],
  ["Leuchtmoos", "Luminous Moss"],
  ["Schneeball", "Snowball"],
  ["Schutzbrille", "Safety Goggles"],
  ["Gengarnit", "Gengarite"],
  ["Guardevoirnit", "Gardevoirite"],
  ["Ampharosnit", "Ampharosite"],
  ["Bisaflornit", "Venusaurite"],
  ["Gluraknit X", "Charizardite X"],
  ["Gluraknit Y", "Charizardite Y"],
  ["Turtoknit", "Blastoisinite"],
  ["Mewtunit X", "Mewtwonite X"],
  ["Mewtunit Y", "Mewtwonite Y"],
  ["Lohgocknit", "Blazikenite"],
  ["Meditalisnit", "Medichamite"],
  ["Hundemonit", "Houndoominite"],
  ["Stollossnit", "Aggronite"],
  ["Banetteonit", "Banettite"],
  ["Despotarnit", "Tyranitarite"],
  ["Scheroxnit", "Scizorite"],
  ["Pinsirnit", "Pinsirite"],
  ["Aerodactylonit", "Aerodactylite"],
  ["Lucarionit", "Lucarionite"],
  ["Rexblisarnit", "Abomasite"],
  ["Kangamanit", "Kangaskhanite"],
  ["Garadosnit", "Gyaradosite"],
  ["Absolnit", "Absolite"],
  ["Simsalanit", "Alakazite"],
  ["Skarabornit", "Heracronite"],
  ["Flunkifernit", "Mawilite"],
  ["Voltensonit", "Manectite"],
  ["Knakracknit", "Garchompite"],
  ["Latiasnit", "Latiasite"],
  ["Latiosnit", "Latiosite"],
  ["Sumpexnit", "Swampertite"],
  ["Gewaldronit", "Sceptilite"],
  ["Zobirisnit", "Sablenite"],
  ["Altarianit", "Altarianite"],
  ["Galagladinit", "Galladite"],
  ["Ohrdochnit", "Audinite"],
  ["Metagrossnit", "Metagrossite"],
  ["Tohaidonit", "Sharpedonite"],
  ["Lahmusnit", "Slowbronite"],
  ["Stahlosnit", "Steelixite"],
  ["Taubossnit", "Pidgeotite"],
  ["Firnontornit", "Glalitite"],
  ["Diancienit", "Diancite"],
  ["Cameruptnit", "Cameruptite"],
  ["Schlapornit", "Lopunnite"],
  ["Brutalandanit", "Salamencite"],
  ["Bibornit", "Beedrillite"],
  ["Normium Z", "Normalium Z"],
  ["Pyrium Z", "Firium Z"],
  ["Aquium Z", "Waterium Z"],
  ["Voltium Z", "Electrium Z"],
  ["Botanium Z", "Grassium Z"],
  ["Glacium Z", "Icium Z"],
  ["Battalium Z", "Fightinium Z"],
  ["Toxium Z", "Poisonium Z"],
  ["Terrium Z", "Groundium Z"],
  ["Aerium Z", "Flyinium Z"],
  ["Psium Z", "Psychium Z"],
  ["Insectium Z", "Buginium Z"],
  ["Petrium Z", "Rockium Z"],
  ["Phantomium Z", "Ghostium Z"],
  ["Dracium Z", "Dragonium Z"],
  ["Noctium Z", "Darkinium Z"],
  ["MetalliumZ", "Steelium Z"],
  ["Sylphium Z", "Fairium Z"],
  ["Pikachium Z", "Pikanium Z"],
  ["Ash-Pikachium Z", "Pikashunium Z"],
  ["A-Raichunium Z", "Aloraichium Z"],
  ["Evolium Z", "Eevium Z"],
  ["Relaxonium Z", "Snorlium Z"],
  ["Mewnium Z", "Mewnium Z"],
  ["Silvarronium Z", "Decidium Z"],
  ["Fuegronium Z", "Incinium Z"],
  ["Primarenium Z", "Primarium Z"],
  ["Kapium Z", "Tapunium Z"],
  ["Marshadownium Z", "Marshadium Z"],
  ["Solgalium Z", "Solganium Z"],
  ["Lunalium Z", "Lunalium Z"],
  ["Ultranecronium Z", "Ultranecrozium Z"],
  ["Mimigmium Z", "Mimikium Z"],
  ["Wolwerockium Z", "Lycanium Z"],
  ["Grandirasium Z", "Kommonium Z"],
  ["Feuer-Disc", "Fire Memory"],
  ["Wasser-Disc", "Water Memory"],
  ["Pflanzen-Disc", "Grass Memory"],
  ["Elektro-Disc", "Electric Memory"],
  ["Eis-Disc", "Ice Memory"],
  ["Kampf-Disc", "Fighting Memory"],
  ["Gift-Disc", "Poison Memory"],
  ["Boden-Disc", "Ground Memory"],
  ["Flug-Disc", "Flying Memory"],
  ["Psycho-Disc", "Psychic Memory"],
  ["Käfer-Disc", "Bug Memory"],
  ["Gesteins-Disc", "Rock Memory"],
  ["Geister-Disc", "Ghost Memory"],
  ["Drachen-Disc", "Dragon Memory"],
  ["Unlicht-Disc", "Dark Memory"],
  ["Stahl-Disc", "Steel Memory"],
  ["Feen-Disc", "Fairy Memory"],
  ["Elektro-Samen", "Electric Seed"],
  ["Gras-Samen", "Grassy Seed"],
  ["Nebel-Samen", "Misty Seed"],
  ["Psycho-Samen", "Psychic Seed"],
  ["Feldbeschichtung", "Terrain Extender"],
  ["Schutzpolster", "Protective Pads"],
  ["Bizarroservice", "Room Service"],
  ["Fluchttasche", "Eject Pack"],
  ["Plateauschuhe", "Heavy-Duty Boots"],
  ["Fehlschlagschutz", "Blunder Policy"],
  ["Halsspray", "Throat Spray"],
  ["Allzweckschirm", "Utility Umbrella"],
  ["Rostiges Schwert", "Rusted Sword"],
  ["Rostiger Schild", "Rusted Shield"],
  ["Gezinkter Würfel", "Loaded Dice"],
  ["Tarnumhang", "Covert Cloak"],
  ["Neutralschmuck", "Clear Amulet"],
  ["Fähigkeitenschild", "Ability Shield"],
  ["Boxhandschuh", "Punching Glove"],
  ["Energiekapsel", "Booster Energy"],
  ["Kopierkraut", "Mirror Herb"],
  ["Adamantkristall", "Adamant Crystal"],
  ["Weißkristall", "Lustrous Globe"],
  ["Platinumkristall", "Griseous Core"],
  ["Feendaune", "Fairy Feather"],
  ["Brunnenmaske", "Wellspring Mask"],
  ["Ofenmaske", "Hearthflame Mask"],
  ["Fundamentmaske", "Cornerstone Mask"],
  ["Amrenabeere", "Cheri Berry"],
  ["Maronbeere", "Chesto Berry"],
  ["Pirsifbeere", "Pecha Berry"],
  ["Fragiabeere", "Rawst Berry"],
  ["Wilbirbeere", "Aspear Berry"],
  ["Jonagobeere", "Leppa Berry"],
  ["Sinelbeere", "Oran Berry"],
  ["Persimbeere", "Persim Berry"],
  ["Prunusbeere", "Lum Berry"],
  ["Tsitrubeere", "Sitrus Berry"],
  ["Giefebeere", "Figy Berry"],
  ["Wikibeere", "Wiki Berry"],
  ["Magobeere", "Mago Berry"],
  ["Gauvebeere", "Aguav Berry"],
  ["Yapabeere", "Iapapa Berry"],
  ["Himmihbeere", "Razz Berry"],
  ["Morbbeere", "Bluk Berry"],
  ["Nanabbeere", "Nanab Berry"],
  ["Nirbebeere", "Wepear Berry"],
  ["Sananabeere", "Pinap Berry"],
  ["Granabeere", "Pomeg Berry"],
  ["Setangbeere", "Kelpsy Berry"],
  ["Qualotbeere", "Qualot Berry"],
  ["Honmelbeere", "Hondew Berry"],
  ["Labrusbeere", "Grepa Berry"],
  ["Tamotbeere", "Tamato Berry"],
  ["Saimbeere", "Cornn Berry"],
  ["Magostbeere", "Magost Berry"],
  ["Rabutabeere", "Rabuta Berry"],
  ["Tronzibeere", "Nomel Berry"],
  ["Kiwanbeere", "Spelon Berry"],
  ["Pallmbeere", "Pamtre Berry"],
  ["Wasmelbeere", "Watmel Berry"],
  ["Durinbeere", "Durin Berry"],
  ["Myrtilbeere", "Belue Berry"],
  ["Lydzibeere", "Liechi Berry"],
  ["Linganbeere", "Ganlon Berry"],
  ["Salkabeere", "Salac Berry"],
  ["Tahaybeere", "Petaya Berry"],
  ["Apikobeere", "Apicot Berry"],
  ["Lansatbeere", "Lansat Berry"],
  ["Krambobeere", "Starf Berry"],
  ["Enigmabeere", "Enigma Berry"],
  ["Koakobeere", "Occa Berry"],
  ["Foepasbeere", "Passho Berry"],
  ["Kerzalbeere", "Wacan Berry"],
  ["Grindobeere", "Rindo Berry"],
  ["Kiroyabeere", "Yache Berry"],
  ["Rospelbeere", "Chople Berry"],
  ["Grarzbeere", "Kebia Berry"],
  ["Schukebeere", "Shuca Berry"],
  ["Kobabeere", "Coba Berry"],
  ["Pyapabeere", "Payapa Berry"],
  ["Tanigabeere", "Tanga Berry"],
  ["Chiaribeere", "Charti Berry"],
  ["Zitarzbeere", "Kasib Berry"],
  ["Terirobeere", "Haban Berry"],
  ["Burleobeere", "Colbur Berry"],
  ["Babiribeere", "Babiri Berry"],
  ["Latchibeere", "Chilan Berry"],
  ["Wunfrubeere", "Micle Berry"],
  ["Eipfelbeere", "Custap Berry"],
  ["Jabocabeere", "Jaboca Berry"],
  ["Roselbeere", "Rowap Berry"],
  ["Hibisbeere", "Roseli Berry"],
  ["Akibeere", "Kee Berry"],
  ["Tarabeere", "Maranga Berry"],
  ["Pfohbeere", "Hopo Berry"]
]);

export const itToEn = new Map([
  ["Luminpolvere", "Bright Powder"],
  ["Rapidartigli", "Quick Claw"],
  ["Roccia Di Re", "King's Rock"],
  ["Argenpolvere", "Silver Powder"],
  ["Monetamuleto", "Amulet Coin"],
  ["Velopuro", "Cleanse Tag"],
  ["Palla Fumo", "Smoke Ball"],
  ["Pietrastante", "Everstone"],
  ["Bandana", "Focus Band"],
  ["Fortunuovo", "Lucky Egg"],
  ["Mirino", "Scope Lens"],
  ["Metalcoperta", "Metal Coat"],
  ["Avanzi", "Leftovers"],
  ["Squama Drago", "Dragon Scale"],
  ["Elettropalla", "Light Ball"],
  ["Sabbia Soffice", "Soft Sand"],
  ["Pietradura", "Hard Stone"],
  ["Miracolseme", "Miracle Seed"],
  ["Occhialineri", "Black Glasses"],
  ["Cinturanera", "Black Belt"],
  ["Calamita", "Magnet"],
  ["Acqua Magica", "Mystic Water"],
  ["Beccaffilato", "Sharp Beak"],
  ["Velenago", "Poison Barb"],
  ["Gelomai", "Never-Melt Ice"],
  ["Spettrotarga", "Spell Tag"],
  ["Cucchiaio Torto", "Twisted Spoon"],
  ["Carbonella", "Charcoal"],
  ["Dentedidrago", "Dragon Fang"],
  ["Fiocco Rosa", "Pink Bow"],
  ["Fiocco Pois", "Polkadot Bow"],
  ["Upgrade", "Up-Grade"],
  ["Fortunpugno", "Lucky Punch"],
  ["Metalpolvere", "Metal Powder"],
  ["Ossospesso", "Thick Club"],
  ["Gambo", "Stick Leek"],
  ["Gene Furioso", "Berserk Gene"],
  ["Erbachiara", "White Herb"],
  ["Crescicappa", "Macho Brace"],
  ["Calmanella", "Soothe Bell"],
  ["Mentalerba", "Mental Herb"],
  ["Bendascelta", "Choice Band"],
  ["Cuorugiada", "Soul Dew"],
  ["Dente Abissi", "Deep Sea Tooth"],
  ["Squamabissi", "Deep Sea Scale"],
  ["Sciarpa Seta", "Silk Scarf"],
  ["Conchinella", "Shell Bell"],
  ["Marearoma", "Sea Incense"],
  ["Distraroma", "Lax Incense"],
  ["Fascia Rossa", "Red Scarf"],
  ["Fascia Blu", "Blue Scarf"],
  ["Fascia Rosa", "Pink Scarf"],
  ["Fascia Verde", "Green Scarf"],
  ["Fascia Gialla", "Yellow Scarf"],
  ["Sfera Rossa", "Red Orb"],
  ["Sfera Blu", "Blue Orb"],
  ["Lastrarogo", "Flame Plate"],
  ["Lastraidro", "Splash Plate"],
  ["Lastrasaetta", "Zap Plate"],
  ["Lastraprato", "Meadow Plate"],
  ["Lastragelo", "Icicle Plate"],
  ["Lastrapugno", "Fist Plate"],
  ["Lastrafiele", "Toxic Plate"],
  ["Lastrageo", "Earth Plate"],
  ["Lastracielo", "Sky Plate"],
  ["Lastramente", "Mind Plate"],
  ["Lastrabaco", "Insect Plate"],
  ["Lastrapietra", "Stone Plate"],
  ["Lastratetra", "Spooky Plate"],
  ["Lastradrakon", "Draco Plate"],
  ["Lastratimore", "Dread Plate"],
  ["Lastraferro", "Iron Plate"],
  ["Bizzoaroma", "Odd Incense"],
  ["Roccioaroma", "Rock Incense"],
  ["Gonfioaroma", "Full Incense"],
  ["Ondaroma", "Wave Incense"],
  ["Rosaroma", "Rose Incense"],
  ["Fortunaroma", "Luck Incense"],
  ["Puroaroma", "Pure Incense"],
  ["Copertura", "Protector"],
  ["Elettritore", "Electirizer"],
  ["Magmatore", "Magmarizer"],
  ["Dubbiodisco", "Dubious Disc"],
  ["Terrorpanno", "Reaper Cloth"],
  ["Affilartigli", "Razor Claw"],
  ["Affilodente", "Razor Fang"],
  ["Pietraovale", "Oval Stone"],
  ["Adamasfera", "Adamant Orb"],
  ["Splendisfera", "Lustrous Orb"],
  ["Grigiosfera", "Griseous Orb"],
  ["Grandelente", "Wide Lens"],
  ["Muscolbanda", "Muscle Band"],
  ["Focalnastro", "Focus Sash"],
  ["Saviocchiali", "Wise Glasses"],
  ["Abilcintura", "Expert Belt"],
  ["Creta Luce", "Light Clay"],
  ["Assorbisfera", "Life Orb"],
  ["Vigorerba", "Power Herb"],
  ["Tossicsfera", "Toxic Orb"],
  ["Fiammosfera", "Flame Orb"],
  ["Velopolvere", "Quick Powder"],
  ["Zoomlente", "Zoom Lens"],
  ["Plessimetro", "Metronome"],
  ["Ferropalla", "Iron Ball"],
  ["Rallentocoda", "Lagging Tail"],
  ["Destincomune", "Destiny Knot"],
  ["Fangopece", "Black Sludge"],
  ["Rocciafredda", "Icy Rock"],
  ["Roccialiscia", "Smooth Rock"],
  ["Rocciacalda", "Heat Rock"],
  ["Rocciaumida", "Damp Rock"],
  ["Presartigli", "Grip Claw"],
  ["Stolascelta", "Choice Scarf"],
  ["Vischiopunta", "Sticky Barb"],
  ["Vigorcerchio", "Power Bracer"],
  ["Vigorfascia", "Power Belt"],
  ["Vigorlente", "Power Lens"],
  ["Vigorbanda", "Power Band"],
  ["Vigorgliera", "Power Anklet"],
  ["Vigorpeso", "Power Weight"],
  ["Disfoguscio", "Shed Shell"],
  ["Granradice", "Big Root"],
  ["Lentiscelta", "Choice Specs"],
  ["Idromodulo", "Douse Drive"],
  ["Voltmodulo", "Shock Drive"],
  ["Piromodulo", "Burn Drive"],
  ["Gelomodulo", "Chill Drive"],
  ["Squama Bella", "Prism Scale"],
  ["Evolcondensa", "Eviolite"],
  ["Pietralieve", "Float Stone"],
  ["Bitorzolelmo", "Rocky Helmet"],
  ["Palloncino", "Air Balloon"],
  ["Cartelrosso", "Red Card"],
  ["Facilsaglio", "Ring Target"],
  ["Legafascia", "Binding Band"],
  ["Bulbo", "Absorb Bulb"],
  ["Ricaripila", "Cell Battery"],
  ["Pulsantefuga", "Eject Button"],
  ["Bijoufuoco", "Fire Gem"],
  ["Bijouacqua", "Water Gem"],
  ["Bijouelettro", "Electric Gem"],
  ["Bijouerba", "Grass Gem"],
  ["Bijoughiac.", "Ice Gem"],
  ["Bijoulotta", "Fighting Gem"],
  ["Bijouveleno", "Poison Gem"],
  ["Bijouterra", "Ground Gem"],
  ["Bijouvolante", "Flying Gem"],
  ["Bijoupsico", "Psychic Gem"],
  ["Bijoucoleot.", "Bug Gem"],
  ["Bijouroccia", "Rock Gem"],
  ["Bijouspettro", "Ghost Gem"],
  ["Bijoudrago", "Dragon Gem"],
  ["Bijoubuio", "Dark Gem"],
  ["Bijouacciaio", "Steel Gem"],
  ["Bijounormale", "Normal Gem"],
  ["Vulneropolizza", "Weakness Policy"],
  ["Corpetto Assalto", "Assault Vest"],
  ["Lastraspiritello", "Pixie Plate"],
  ["Dolcespuma", "Whipped Dream"],
  ["Bustina Aromi", "Sachet"],
  ["Muschioluce", "Luminous Moss"],
  ["Palla di Neve", "Snowball"],
  ["Visierantisabbia", "Safety Goggles"],
  ["Gengarite", "Gengarite"],
  ["Gardevoirite", "Gardevoirite"],
  ["Ampharosite", "Ampharosite"],
  ["Venusaurite", "Venusaurite"],
  ["Charizardite X", "Charizardite X"],
  ["Charizardite Y", "Charizardite Y"],
  ["Blastoisite", "Blastoisinite"],
  ["Mewtwoite X", "Mewtwonite X"],
  ["Mewtwoite Y", "Mewtwonite Y"],
  ["Blazikenite", "Blazikenite"],
  ["Medichamite", "Medichamite"],
  ["Houndoomite", "Houndoominite"],
  ["Aggronite", "Aggronite"],
  ["Banettite", "Banettite"],
  ["Tyranitarite", "Tyranitarite"],
  ["Scizorite", "Scizorite"],
  ["Pinsirite", "Pinsirite"],
  ["Aerodactylite", "Aerodactylite"],
  ["Lucarite", "Lucarionite"],
  ["Abomasnowite", "Abomasite"],
  ["Kangaskhanite", "Kangaskhanite"],
  ["Gyaradosite", "Gyaradosite"],
  ["Absolite", "Absolite"],
  ["Alakazamite", "Alakazite"],
  ["Heracrossite", "Heracronite"],
  ["Mawilite", "Mawilite"],
  ["Manectricite", "Manectite"],
  ["Garchompite", "Garchompite"],
  ["Latiasite", "Latiasite"],
  ["Latiosite", "Latiosite"],
  ["Swampertite", "Swampertite"],
  ["Sceptilite", "Sceptilite"],
  ["Sableyite", "Sablenite"],
  ["Altarite", "Altarianite"],
  ["Galladite", "Galladite"],
  ["Audinite", "Audinite"],
  ["Metagrossite", "Metagrossite"],
  ["Sharpedite", "Sharpedonite"],
  ["Slowbroite", "Slowbronite"],
  ["Steelixite", "Steelixite"],
  ["Pidgeotite", "Pidgeotite"],
  ["Glalite", "Glalitite"],
  ["Diancite", "Diancite"],
  ["Cameruptite", "Cameruptite"],
  ["Lopunnite", "Lopunnite"],
  ["Salamencite", "Salamencite"],
  ["Beedrillite", "Beedrillite"],
  ["Normium Z", "Normalium Z"],
  ["Pirium Z", "Firium Z"],
  ["Idrium Z", "Waterium Z"],
  ["Electrium Z", "Electrium Z"],
  ["Herbium Z", "Grassium Z"],
  ["Glacium Z", "Icium Z"],
  ["Luctium Z", "Fightinium Z"],
  ["Venenium Z", "Poisonium Z"],
  ["Terrium Z", "Groundium Z"],
  ["Volantium Z", "Flyinium Z"],
  ["Psychium Z", "Psychium Z"],
  ["Insectium Z", "Buginium Z"],
  ["Petrium Z", "Rockium Z"],
  ["Spectrium Z", "Ghostium Z"],
  ["Draconium Z", "Dragonium Z"],
  ["Obscurium Z", "Darkinium Z"],
  ["MetalliumZ", "Steelium Z"],
  ["Follectium Z", "Fairium Z"],
  ["Pikacium Z", "Pikanium Z"],
  ["Ashpikacium Z", "Pikashunium Z"],
  ["Aloraicium Z", "Aloraichium Z"],
  ["Eevium Z", "Eevium Z"],
  ["Snorlactium Z", "Snorlium Z"],
  ["Mewnium Z", "Mewnium Z"],
  ["Deciduenium Z", "Decidium Z"],
  ["Incineronium Z", "Incinium Z"],
  ["Primarinium Z", "Primarium Z"],
  ["Tapium Z", "Tapunium Z"],
  ["Marshadium Z", "Marshadium Z"],
  ["Solgaleium Z", "Solganium Z"],
  ["Lunalium Z", "Lunalium Z"],
  ["Ultranecrozium Z", "Ultranecrozium Z"],
  ["Mimikyum Z", "Mimikium Z"],
  ["Lycanrochium Z", "Lycanium Z"],
  ["Kommonium Z", "Kommonium Z"],
  ["ROM Fuoco", "Fire Memory"],
  ["ROM Acqua", "Water Memory"],
  ["ROM Erba", "Grass Memory"],
  ["ROM Elettro", "Electric Memory"],
  ["ROM Ghiaccio", "Ice Memory"],
  ["ROM Lotta", "Fighting Memory"],
  ["ROM Veleno", "Poison Memory"],
  ["ROM Terra", "Ground Memory"],
  ["ROM Volante", "Flying Memory"],
  ["ROM Psico", "Psychic Memory"],
  ["ROM Coleottero", "Bug Memory"],
  ["ROM Roccia", "Rock Memory"],
  ["ROM Spettro", "Ghost Memory"],
  ["ROM Drago", "Dragon Memory"],
  ["ROM Buio", "Dark Memory"],
  ["ROM Acciaio", "Steel Memory"],
  ["ROM Folletto", "Fairy Memory"],
  ["Elettroseme", "Electric Seed"],
  ["Erbaseme", "Grassy Seed"],
  ["Nebbiaseme", "Misty Seed"],
  ["Psicoseme", "Psychic Seed"],
  ["Fissacampo", "Terrain Extender"],
  ["Smorzaurti", "Protective Pads"],
  ["Distorservizio", "Room Service"],
  ["Zainofuga", "Eject Pack"],
  ["Scarponi robusti", "Heavy-Duty Boots"],
  ["Fiascopolizza", "Blunder Policy"],
  ["Spray gola", "Throat Spray"],
  ["Superombrello", "Utility Umbrella"],
  ["Spada rovinata", "Rusted Sword"],
  ["Scudo rovinato", "Rusted Shield"],
  ["Dado truccato", "Loaded Dice"],
  ["Anonimanto", "Covert Cloak"],
  ["Ciondolochiaro", "Clear Amulet"],
  ["Scudo abilità", "Ability Shield"],
  ["Guantone", "Punching Glove"],
  ["Capsula energetica", "Booster Energy"],
  ["Foglia carbone", "Mirror Herb"],
  ["Adamasferoide", "Adamant Crystal"],
  ["Splendisferoide", "Lustrous Globe"],
  ["Grigiosferoide", "Griseous Core"],
  ["Piuma fatata", "Fairy Feather"],
  ["Maschera Pozzo", "Wellspring Mask"],
  ["Maschera Focolare", "Hearthflame Mask"],
  ["Maschera Fondamenta", "Cornerstone Mask"],
  ["Baccaliegia", "Cheri Berry"],
  ["Baccastagna", "Chesto Berry"],
  ["Baccapesca", "Pecha Berry"],
  ["Baccafrago", "Rawst Berry"],
  ["Baccaperina", "Aspear Berry"],
  ["Baccamela", "Leppa Berry"],
  ["Baccarancia", "Oran Berry"],
  ["Baccaki", "Persim Berry"],
  ["Baccaprugna", "Lum Berry"],
  ["Baccacedro", "Sitrus Berry"],
  ["Baccafico", "Figy Berry"],
  ["Baccaprugna", "Wiki Berry"],
  ["Baccamango", "Mago Berry"],
  ["Baccaguava", "Aguav Berry"],
  ["Baccapaia", "Iapapa Berry"],
  ["Baccalampon", "Razz Berry"],
  ["Baccamora", "Bluk Berry"],
  ["Baccabana", "Nanab Berry"],
  ["Baccapera", "Wepear Berry"],
  ["Baccananas", "Pinap Berry"],
  ["Baccagrana", "Pomeg Berry"],
  ["Baccalga", "Kelpsy Berry"],
  ["Baccaloquat", "Qualot Berry"],
  ["Baccamelon", "Hondew Berry"],
  ["Baccauva", "Grepa Berry"],
  ["Baccamodoro", "Tamato Berry"],
  ["Baccavena", "Cornn Berry"],
  ["Baccagostan", "Magost Berry"],
  ["Baccambutan", "Rabuta Berry"],
  ["Baccalemon", "Nomel Berry"],
  ["Baccamelos", "Spelon Berry"],
  ["Baccapalma", "Pamtre Berry"],
  ["Baccacomero", "Watmel Berry"],
  ["Baccadurian", "Durin Berry"],
  ["Baccartillo", "Belue Berry"],
  ["Baccalici", "Liechi Berry"],
  ["Baccalongan", "Ganlon Berry"],
  ["Baccasalak", "Salac Berry"],
  ["Baccapitaya", "Petaya Berry"],
  ["Baccacocca", "Apicot Berry"],
  ["Baccalangsa", "Lansat Berry"],
  ["Baccambola", "Starf Berry"],
  ["Baccaenigma", "Enigma Berry"],
  ["Baccacao", "Occa Berry"],
  ["Baccapasflo", "Passho Berry"],
  ["Baccaparmen", "Wacan Berry"],
  ["Baccarindo", "Rindo Berry"],
  ["Baccamoya", "Yache Berry"],
  ["Baccarosmel", "Chople Berry"],
  ["Baccakebia", "Kebia Berry"],
  ["Baccanaca", "Shuca Berry"],
  ["Baccababa", "Coba Berry"],
  ["Baccapayapa", "Payapa Berry"],
  ["Baccaitan", "Tanga Berry"],
  ["Baccaciofo", "Charti Berry"],
  ["Baccacitrus", "Kasib Berry"],
  ["Baccahaban", "Haban Berry"],
  ["Baccaxan", "Colbur Berry"],
  ["Baccababiri", "Babiri Berry"],
  ["Baccacinlan", "Chilan Berry"],
  ["Baccaracolo", "Micle Berry"],
  ["Baccacrela", "Custap Berry"],
  ["Baccajaba", "Jaboca Berry"],
  ["Baccaroam", "Rowap Berry"],
  ["Baccarcadè", "Roseli Berry"],
  ["Baccalighia", "Kee Berry"],
  ["Baccapane", "Maranga Berry"],
  ["Baccaluppo", "Hopo Berry"]
]);

export const esToEn = new Map([
  ["Polvo Brillo", "Bright Powder"],
  ["Garra Rápida", "Quick Claw"],
  ["Roca del Rey", "King's Rock"],
  ["Polvo Plata", "Silver Powder"],
  ["Moneda Amuleto", "Amulet Coin"],
  ["Amuleto", "Cleanse Tag"],
  ["Bola Humo", "Smoke Ball"],
  ["Piedra Eterna", "Everstone"],
  ["Cinta Focus", "Focus Band"],
  ["Huevo Suerte", "Lucky Egg"],
  ["Periscopio", "Scope Lens"],
  ["Revest. Metálico", "Metal Coat"],
  ["Restos", "Leftovers"],
  ["Escamadragón", "Dragon Scale"],
  ["Bolaluminosa", "Light Ball"],
  ["Arena Fina", "Soft Sand"],
  ["Piedra Dura", "Hard Stone"],
  ["Semilla Milagro", "Miracle Seed"],
  ["Gafas de Sol", "Black Glasses"],
  ["Cinturón Negro", "Black Belt"],
  ["Imán", "Magnet"],
  ["Agua Mística", "Mystic Water"],
  ["Pico Afilado", "Sharp Beak"],
  ["Flecha Venenosa", "Poison Barb"],
  ["Antiderretir", "Never-Melt Ice"],
  ["Hechizo", "Spell Tag"],
  ["Cuchara Torcida", "Twisted Spoon"],
  ["Carbón", "Charcoal"],
  ["Colmillo Dragón", "Dragon Fang"],
  ["Lazo Rosa", "Pink Bow"],
  ["Cintalunares", "Polkadot Bow"],
  ["Mejora", "Up-Grade"],
  ["Puño Suerte", "Lucky Punch"],
  ["Polvo Metálico", "Metal Powder"],
  ["Hueso Grueso", "Thick Club"],
  ["Palo Puerro", "Stick Leek"],
  ["Gen Loco", "Berserk Gene"],
  ["Hierba Blanca", "White Herb"],
  ["Brazal Firme", "Macho Brace"],
  ["Campana Alivio", "Soothe Bell"],
  ["Hierba Mental", "Mental Herb"],
  ["Cinta Elegida", "Choice Band"],
  ["Rocío Bondad", "Soul Dew"],
  ["Diente Marino", "Deep Sea Tooth"],
  ["Escama Marina", "Deep Sea Scale"],
  ["Pañuelo Seda", "Silk Scarf"],
  ["Campana Concha", "Shell Bell"],
  ["Incienso Marino", "Sea Incense"],
  ["Incienso Suave", "Lax Incense"],
  ["Pañuelo Rojo", "Red Scarf"],
  ["Pañuelo Azul", "Blue Scarf"],
  ["Pañuelo Rosa", "Pink Scarf"],
  ["Pañuelo Verde", "Green Scarf"],
  ["Pañuelo Amarillo", "Yellow Scarf"],
  ["Esfera Roja", "Red Orb"],
  ["Esfera Azul", "Blue Orb"],
  ["Tabla Llama", "Flame Plate"],
  ["Tabla Linfa", "Splash Plate"],
  ["Tabla Trueno", "Zap Plate"],
  ["Tabla Pradal", "Meadow Plate"],
  ["Tabla Helada", "Icicle Plate"],
  ["Tabla Fuerte", "Fist Plate"],
  ["Tabla Tóxica", "Toxic Plate"],
  ["Tabla Terrax", "Earth Plate"],
  ["Tabla Cielo", "Sky Plate"],
  ["Tabla Mental", "Mind Plate"],
  ["Tabla Bicho", "Insect Plate"],
  ["Tabla Pétrea", "Stone Plate"],
  ["Tabla Terror", "Spooky Plate"],
  ["Tabla Draco", "Draco Plate"],
  ["Tabla Oscura", "Dread Plate"],
  ["Tabla Acero", "Iron Plate"],
  ["Incienso Raro", "Odd Incense"],
  ["Incienso Roca", "Rock Incense"],
  ["Incienso Lento", "Full Incense"],
  ["Incienso Aqua", "Wave Incense"],
  ["Incienso Floral", "Rose Incense"],
  ["Incienso Duplo", "Luck Incense"],
  ["Incienso Puro", "Pure Incense"],
  ["Protector", "Protector"],
  ["Electrizador", "Electirizer"],
  ["Magmatizador", "Magmarizer"],
  ["Discoxtraño", "Dubious Disc"],
  ["Tela Terrible", "Reaper Cloth"],
  ["Garra Afilada", "Razor Claw"],
  ["Colmillo Agudo", "Razor Fang"],
  ["Piedra Oval", "Oval Stone"],
  ["Diamansfera", "Adamant Orb"],
  ["Lustresfera", "Lustrous Orb"],
  ["Griseosfera", "Griseous Orb"],
  ["Lupa", "Wide Lens"],
  ["Cinta Fuerte", "Muscle Band"],
  ["Banda Focus", "Focus Sash"],
  ["Gafas Especiales", "Wise Glasses"],
  ["Cinta Xperto", "Expert Belt"],
  ["Refleluz", "Light Clay"],
  ["Vidasfera", "Life Orb"],
  ["Hierba Única", "Power Herb"],
  ["Toxisfera", "Toxic Orb"],
  ["Llamasfera", "Flame Orb"],
  ["Polvo Veloz", "Quick Powder"],
  ["Telescopio", "Zoom Lens"],
  ["Metrónomo", "Metronome"],
  ["Bola Férrea", "Iron Ball"],
  ["Cola Plúmbea", "Lagging Tail"],
  ["Lazo Destino", "Destiny Knot"],
  ["Lodo Negro", "Black Sludge"],
  ["Roca Helada", "Icy Rock"],
  ["Roca Suave", "Smooth Rock"],
  ["Roca Calor", "Heat Rock"],
  ["Roca Lluvia", "Damp Rock"],
  ["Garra Garfio", "Grip Claw"],
  ["Pañuelo Elegido", "Choice Scarf"],
  ["Toxiestrella", "Sticky Barb"],
  ["Brazal Recio", "Power Bracer"],
  ["Cinto Recio", "Power Belt"],
  ["Lente Recia", "Power Lens"],
  ["Banda Recia", "Power Band"],
  ["Franja Recia", "Power Anklet"],
  ["Pesa Recia", "Power Weight"],
  ["Muda Concha", "Shed Shell"],
  ["Raíz Grande", "Big Root"],
  ["Gafas Elegid", "Choice Specs"],
  ["HidroROM", "Douse Drive"],
  ["FulgoROM", "Shock Drive"],
  ["PiroROM", "Burn Drive"],
  ["CrioROM", "Chill Drive"],
  ["Escama Bella", "Prism Scale"],
  ["Mineral Evol", "Eviolite"],
  ["Piedra Pómez", "Float Stone"],
  ["Casco Dentado", "Rocky Helmet"],
  ["Globo Helio", "Air Balloon"],
  ["Tarjeta Roja", "Red Card"],
  ["Blanco", "Ring Target"],
  ["Banda Atadura", "Binding Band"],
  ["Tubérculo", "Absorb Bulb"],
  ["Pila", "Cell Battery"],
  ["Botón Escape", "Eject Button"],
  ["G. Fuego", "Fire Gem"],
  ["G. Agua", "Water Gem"],
  ["G. Eléctrica", "Electric Gem"],
  ["G. Planta", "Grass Gem"],
  ["G. Hielo", "Ice Gem"],
  ["G. Lucha", "Fighting Gem"],
  ["G. Veneno", "Poison Gem"],
  ["G. Tierra", "Ground Gem"],
  ["G. Voladora", "Flying Gem"],
  ["G. Psíquica", "Psychic Gem"],
  ["G. Bicho", "Bug Gem"],
  ["G. Roca", "Rock Gem"],
  ["G. Fantasma", "Ghost Gem"],
  ["G. Dragón", "Dragon Gem"],
  ["G. Siniestra", "Dark Gem"],
  ["G. Acero", "Steel Gem"],
  ["Gema Normal", "Normal Gem"],
  ["Seguro Debilidad", "Weakness Policy"],
  ["Chaleco Asalto", "Assault Vest"],
  ["Tabla Duende", "Pixie Plate"],
  ["Dulce de Nata", "Whipped Dream"],
  ["Saquito Fragante", "Sachet"],
  ["Musgo Brillante", "Luminous Moss"],
  ["Bola de Nieve", "Snowball"],
  ["Gafa Protectora", "Safety Goggles"],
  ["Gengarita", "Gengarite"],
  ["Gardevoirita", "Gardevoirite"],
  ["Ampharosita", "Ampharosite"],
  ["Venusaurita", "Venusaurite"],
  ["Charizardita X", "Charizardite X"],
  ["Charizardita Y", "Charizardite Y"],
  ["Blastoisita", "Blastoisinite"],
  ["Mewtwoita X", "Mewtwonite X"],
  ["Mewtwoita Y", "Mewtwonite Y"],
  ["Blazikenita", "Blazikenite"],
  ["Medichamita", "Medichamite"],
  ["Houndoomita", "Houndoominite"],
  ["Aggronita", "Aggronite"],
  ["Banettita", "Banettite"],
  ["Tyranitarita", "Tyranitarite"],
  ["Scizorita", "Scizorite"],
  ["Pinsirita", "Pinsirite"],
  ["Aerodactylita", "Aerodactylite"],
  ["Lucarita", "Lucarionite"],
  ["Abomasnowita", "Abomasite"],
  ["Kangaskhanita", "Kangaskhanite"],
  ["Gyaradosita", "Gyaradosite"],
  ["Absolita", "Absolite"],
  ["Alakazamita", "Alakazite"],
  ["Heracrossita", "Heracronite"],
  ["Mawilita", "Mawilite"],
  ["Manectricita", "Manectite"],
  ["Garchompita", "Garchompite"],
  ["Latiasita", "Latiasite"],
  ["Latiosita", "Latiosite"],
  ["Swampertita", "Swampertite"],
  ["Sceptilita", "Sceptilite"],
  ["Sableynita", "Sablenite"],
  ["Altarianita", "Altarianite"],
  ["Galladita", "Galladite"],
  ["Audinita", "Audinite"],
  ["Metagrossita", "Metagrossite"],
  ["Sharpedonita", "Sharpedonite"],
  ["Slowbronita", "Slowbronite"],
  ["Steelixita", "Steelixite"],
  ["Pidgeotita", "Pidgeotite"],
  ["Glalita", "Glalitite"],
  ["Diancita", "Diancite"],
  ["Cameruptita", "Cameruptite"],
  ["Lopunnita", "Lopunnite"],
  ["Salamencita", "Salamencite"],
  ["Beedrillita", "Beedrillite"],
  ["Normastal Z", "Normalium Z"],
  ["Pirostal Z", "Firium Z"],
  ["Hidrostal Z", "Waterium Z"],
  ["Electrostal Z", "Electrium Z"],
  ["Fitostal Z", "Grassium Z"],
  ["Criostal Z", "Icium Z"],
  ["Lizastal Z", "Fightinium Z"],
  ["Toxistal Z", "Poisonium Z"],
  ["Geostal Z", "Groundium Z"],
  ["Aerostal Z", "Flyinium Z"],
  ["Psicostal Z", "Psychium Z"],
  ["Insectostal Z", "Buginium Z"],
  ["Litostal Z", "Rockium Z"],
  ["Espectrostal Z", "Ghostium Z"],
  ["Dracostal Z", "Dragonium Z"],
  ["Nictostal Z", "Darkinium Z"],
  ["Metalostal Z", "Steelium Z"],
  ["Feeristal Z", "Fairium Z"],
  ["Pikastal Z", "Pikanium Z"],
  ["Ash-Pikastal Z", "Pikashunium Z"],
  ["Alo-Raistal Z", "Aloraichium Z"],
  ["Eeveestal Z", "Eevium Z"],
  ["Snorlastal Z", "Snorlium Z"],
  ["Mewstal Z", "Mewnium Z"],
  ["Dueyestal Z", "Decidium Z"],
  ["Incinostal Z", "Incinium Z"],
  ["Primastal Z", "Primarium Z"],
  ["Tapistal Z", "Tapunium Z"],
  ["Marshastal Z", "Marshadium Z"],
  ["Solgaleostal Z", "Solganium Z"],
  ["Lunalastal Z", "Lunalium Z"],
  ["Ultranecrostal Z", "Ultranecrozium Z"],
  ["Mimikyustal Z", "Mimikium Z"],
  ["Lycanrostal Z", "Lycanium Z"],
  ["Kommostal Z", "Kommonium Z"],
  ["Disco Fuego", "Fire Memory"],
  ["Disco Agua", "Water Memory"],
  ["Disco Planta", "Grass Memory"],
  ["Disco Eléctrico", "Electric Memory"],
  ["Disco Hielo", "Ice Memory"],
  ["Disco Lucha", "Fighting Memory"],
  ["Disco Veneno", "Poison Memory"],
  ["Disco Tierra", "Ground Memory"],
  ["Disco Volador", "Flying Memory"],
  ["Disco Psíquico", "Psychic Memory"],
  ["Disco Bicho", "Bug Memory"],
  ["Disco Roca", "Rock Memory"],
  ["Disco Fantasma", "Ghost Memory"],
  ["Disco Dragón", "Dragon Memory"],
  ["Disco Siniestro", "Dark Memory"],
  ["Disco Acero", "Steel Memory"],
  ["Disco Hada", "Fairy Memory"],
  ["Semilla Electro", "Electric Seed"],
  ["Semilla Hierba", "Grassy Seed"],
  ["Semilla Bruma", "Misty Seed"],
  ["Semilla Psique", "Psychic Seed"],
  ["Cubresuelos", "Terrain Extender"],
  ["Paracontacto", "Protective Pads"],
  ["Servicio Raro", "Room Service"],
  ["Mochila Escape", "Eject Pack"],
  ["Botas Gruesas", "Heavy-Duty Boots"],
  ["Seguro Fallo", "Blunder Policy"],
  ["Espray Bucal", "Throat Spray"],
  ["Parasol Multiuso", "Utility Umbrella"],
  ["Espada Oxidada", "Rusted Sword"],
  ["Escudo Oxidado", "Rusted Shield"],
  ["Dado Trucado", "Loaded Dice"],
  ["Capa Furtiva", "Covert Cloak"],
  ["Amuleto Puro", "Clear Amulet"],
  ["Escudo Habilidad", "Ability Shield"],
  ["Guante de Boxeo", "Punching Glove"],
  ["Energía Potenciadora", "Booster Energy"],
  ["Hierba Copia", "Mirror Herb"],
  ["Gran Diamansfera", "Adamant Crystal"],
  ["Gran Lustresfera", "Lustrous Globe"],
  ["Gran Griseosfera", "Griseous Core"],
  ["Pluma Feérica", "Fairy Feather"],
  ["Máscara Fuente", "Wellspring Mask"],
  ["Máscara Horno", "Hearthflame Mask"],
  ["Máscara Cimiento", "Cornerstone Mask"],
  ["Baya Zreza", "Cheri Berry"],
  ["Baya Atania", "Chesto Berry"],
  ["Baya Meloc", "Pecha Berry"],
  ["Baya Safre", "Rawst Berry"],
  ["Baya Perasi", "Aspear Berry"],
  ["Baya Zanama", "Leppa Berry"],
  ["Baya Aranja", "Oran Berry"],
  ["Baya Caquic", "Persim Berry"],
  ["Baya Ziuela", "Lum Berry"],
  ["Baya Zidra", "Sitrus Berry"],
  ["Baya Higog", "Figy Berry"],
  ["Baya Wiki", "Wiki Berry"],
  ["Baya Ango", "Mago Berry"],
  ["Baya Guaya", "Aguav Berry"],
  ["Baya Pabaya", "Iapapa Berry"],
  ["Baya Frambu", "Razz Berry"],
  ["Baya Oram", "Bluk Berry"],
  ["Baya Latano", "Nanab Berry"],
  ["Baya Peragu", "Wepear Berry"],
  ["Baya Pinia", "Pinap Berry"],
  ["Baya Grana", "Pomeg Berry"],
  ["Baya Algama", "Kelpsy Berry"],
  ["Baya Ispero", "Qualot Berry"],
  ["Baya Meluce", "Hondew Berry"],
  ["Baya Uvav", "Grepa Berry"],
  ["Baya Tamate", "Tamato Berry"],
  ["Baya Mais", "Cornn Berry"],
  ["Baya Aostan", "Magost Berry"],
  ["Baya Rautan", "Rabuta Berry"],
  ["Baya Monli", "Nomel Berry"],
  ["Baya Wikano", "Spelon Berry"],
  ["Baya Plama", "Pamtre Berry"],
  ["Baya Sambia", "Watmel Berry"],
  ["Baya Rudion", "Durin Berry"],
  ["Baya Andano", "Belue Berry"],
  ["Baya Lichi", "Liechi Berry"],
  ["Baya Gonlan", "Ganlon Berry"],
  ["Baya Aslac", "Salac Berry"],
  ["Baya Yapati", "Petaya Berry"],
  ["Baya Aricoc", "Apicot Berry"],
  ["Baya Zonlan", "Lansat Berry"],
  ["Baya Arabol", "Starf Berry"],
  ["Baya Enigma", "Enigma Berry"],
  ["Baya Caoca", "Occa Berry"],
  ["Baya Pasio", "Passho Berry"],
  ["Baya Gualot", "Wacan Berry"],
  ["Baya Tamar", "Rindo Berry"],
  ["Baya Rimoya", "Yache Berry"],
  ["Baya Pomaro", "Chople Berry"],
  ["Baya Kebia", "Kebia Berry"],
  ["Baya Acardo", "Shuca Berry"],
  ["Baya Kouba", "Coba Berry"],
  ["Baya Payapa", "Payapa Berry"],
  ["Baya Yecana", "Tanga Berry"],
  ["Baya Alcho", "Charti Berry"],
  ["Baya Drasi", "Kasib Berry"],
  ["Baya Anjiro", "Haban Berry"],
  ["Baya Dillo", "Colbur Berry"],
  ["Baya Baribá", "Babiri Berry"],
  ["Baya Chilan", "Chilan Berry"],
  ["Baya Lagro", "Micle Berry"],
  ["Baya Chiri", "Custap Berry"],
  ["Baya Jaboca", "Jaboca Berry"],
  ["Baya Magua", "Rowap Berry"],
  ["Baya Hibis", "Roseli Berry"],
  ["Baya Biglia", "Kee Berry"],
  ["Baya Maranga", "Maranga Berry"],
  ["Baya Lupu", "Hopo Berry"]
]);

export const koToEn = new Map([
  ["반짝가루", "Bright Powder"],
  ["선제공격손톱", "Quick Claw"],
  ["왕의징표석", "King's Rock"],
  ["은빛가루", "Silver Powder"],
  ["부적금화", "Amulet Coin"],
  ["순결의부적", "Cleanse Tag"],
  ["연막탄", "Smoke Ball"],
  ["변함없는돌", "Everstone"],
  ["기합의머리띠", "Focus Band"],
  ["행복의알", "Lucky Egg"],
  ["초점렌즈", "Scope Lens"],
  ["금속코트", "Metal Coat"],
  ["먹다남은음식", "Leftovers"],
  ["용의비늘", "Dragon Scale"],
  ["전기구슬", "Light Ball"],
  ["부드러운모래", "Soft Sand"],
  ["딱딱한돌", "Hard Stone"],
  ["기적의씨", "Miracle Seed"],
  ["검은안경", "Black Glasses"],
  ["검은띠", "Black Belt"],
  ["자석", "Magnet"],
  ["신비의물방울", "Mystic Water"],
  ["예리한부리", "Sharp Beak"],
  ["독바늘", "Poison Barb"],
  ["녹지않는얼음", "Never-Melt Ice"],
  ["저주의부적", "Spell Tag"],
  ["휘어진스푼", "Twisted Spoon"],
  ["목탄", "Charcoal"],
  ["용의이빨", "Dragon Fang"],
  ["핑크빛리본", "Pink Bow"],
  ["물방울리본", "Polkadot Bow"],
  ["업그레이드", "Up-Grade"],
  ["럭키펀치", "Lucky Punch"],
  ["금속파우더", "Metal Powder"],
  ["굵은뼈", "Thick Club"],
  ["대파", "Stick Leek"],
  ["파괴의유전자", "Berserk Gene"],
  ["하양허브", "White Herb"],
  ["교정깁스", "Macho Brace"],
  ["평온의방울", "Soothe Bell"],
  ["멘탈허브", "Mental Herb"],
  ["구애머리띠", "Choice Band"],
  ["마음의물방울", "Soul Dew"],
  ["심해의이빨", "Deep Sea Tooth"],
  ["심해의비늘", "Deep Sea Scale"],
  ["실크스카프", "Silk Scarf"],
  ["조개껍질방울", "Shell Bell"],
  ["바닷물향로", "Sea Incense"],
  ["무사태평항로", "Lax Incense"],
  ["빨강밴드", "Red Scarf"],
  ["파랑밴드", "Blue Scarf"],
  ["분홍밴드", "Pink Scarf"],
  ["초록밴드", "Green Scarf"],
  ["노랑밴드", "Yellow Scarf"],
  ["주홍구슬", "Red Orb"],
  ["쪽빛구슬", "Blue Orb"],
  ["불구슬플레이트", "Flame Plate"],
  ["물방울플레이트", "Splash Plate"],
  ["우뢰플레이트", "Zap Plate"],
  ["초록플레이트", "Meadow Plate"],
  ["고드름플레이트", "Icicle Plate"],
  ["주먹플레이트", "Fist Plate"],
  ["맹독플레이트", "Toxic Plate"],
  ["대지플레이트", "Earth Plate"],
  ["푸른하늘플레이트", "Sky Plate"],
  ["이상한플레이트", "Mind Plate"],
  ["비단벌레플레이트", "Insect Plate"],
  ["암석플레이트", "Stone Plate"],
  ["원령플레이트", "Spooky Plate"],
  ["용의플레이트", "Draco Plate"],
  ["공포플레이트", "Dread Plate"],
  ["강철플레이트", "Iron Plate"],
  ["괴상한향로", "Odd Incense"],
  ["암석향로", "Rock Incense"],
  ["만복향로", "Full Incense"],
  ["잔물결향로", "Wave Incense"],
  ["꽃향로", "Rose Incense"],
  ["행운의향로", "Luck Incense"],
  ["순결의향로", "Pure Incense"],
  ["프로텍터", "Protector"],
  ["에레키부스터", "Electirizer"],
  ["마그마부스터", "Magmarizer"],
  ["괴상한패치", "Dubious Disc"],
  ["영계의천", "Reaper Cloth"],
  ["예리한손톱", "Razor Claw"],
  ["예리한이빨", "Razor Fang"],
  ["동글동글돌", "Oval Stone"],
  ["금강옥", "Adamant Orb"],
  ["백옥", "Lustrous Orb"],
  ["백금옥", "Griseous Orb"],
  ["광각렌즈", "Wide Lens"],
  ["힘의머리띠", "Muscle Band"],
  ["기합의띠", "Focus Sash"],
  ["박식안경", "Wise Glasses"],
  ["달인의띠", "Expert Belt"],
  ["빛의점토", "Light Clay"],
  ["생명의구슬", "Life Orb"],
  ["파워풀허브", "Power Herb"],
  ["맹독구슬", "Toxic Orb"],
  ["화염구슬", "Flame Orb"],
  ["스피드파우더", "Quick Powder"],
  ["포커스렌즈", "Zoom Lens"],
  ["메트로놈", "Metronome"],
  ["검은철구", "Iron Ball"],
  ["느림보꼬리", "Lagging Tail"],
  ["빨간실", "Destiny Knot"],
  ["검은진흙", "Black Sludge"],
  ["차가운바위", "Icy Rock"],
  ["보송보송바위", "Smooth Rock"],
  ["뜨거운바위", "Heat Rock"],
  ["축축한바위", "Damp Rock"],
  ["끈기갈고리손톱", "Grip Claw"],
  ["구애스카프", "Choice Scarf"],
  ["끈적끈적바늘", "Sticky Barb"],
  ["파워리스트", "Power Bracer"],
  ["파워벨트", "Power Belt"],
  ["파워렌즈", "Power Lens"],
  ["파워밴드", "Power Band"],
  ["파워앵클릿", "Power Anklet"],
  ["파워웨이트", "Power Weight"],
  ["아름다운허물", "Shed Shell"],
  ["큰뿌리", "Big Root"],
  ["구애안경", "Choice Specs"],
  ["아쿠아카세트", "Douse Drive"],
  ["번개카세트", "Shock Drive"],
  ["블레이즈카세트", "Burn Drive"],
  ["프리즈카세트", "Chill Drive"],
  ["고운비늘", "Prism Scale"],
  ["진화의 휘석", "Eviolite"],
  ["가벼운돌", "Float Stone"],
  ["울퉁불퉁멧", "Rocky Helmet"],
  ["풍선", "Air Balloon"],
  ["레드카드", "Red Card"],
  ["겨냥표적", "Ring Target"],
  ["조임밴드", "Binding Band"],
  ["구근", "Absorb Bulb"],
  ["충전지", "Cell Battery"],
  ["탈출버튼", "Eject Button"],
  ["불꽃주얼", "Fire Gem"],
  ["물주얼", "Water Gem"],
  ["전기주얼", "Electric Gem"],
  ["풀주얼", "Grass Gem"],
  ["얼음주얼", "Ice Gem"],
  ["격투주얼", "Fighting Gem"],
  ["독주얼", "Poison Gem"],
  ["땅주얼", "Ground Gem"],
  ["비행주얼", "Flying Gem"],
  ["에스퍼주얼", "Psychic Gem"],
  ["벌레주얼", "Bug Gem"],
  ["바위주얼", "Rock Gem"],
  ["고스트주얼", "Ghost Gem"],
  ["드래곤주얼", "Dragon Gem"],
  ["악주얼", "Dark Gem"],
  ["강철주얼", "Steel Gem"],
  ["노말주얼", "Normal Gem"],
  ["약점보험", "Weakness Policy"],
  ["돌격조끼", "Assault Vest"],
  ["정령플레이트", "Pixie Plate"],
  ["휘핑팝", "Whipped Dream"],
  ["향기주머니", "Sachet"],
  ["빛이끼", "Luminous Moss"],
  ["눈덩이", "Snowball"],
  ["방진고글", "Safety Goggles"],
  ["팬텀나이트", "Gengarite"],
  ["가디안나이트", "Gardevoirite"],
  ["전룡나이트", "Ampharosite"],
  ["이상해꽃나이트", "Venusaurite"],
  ["리자몽나이트X", "Charizardite X"],
  ["리자몽나이트Y", "Charizardite Y"],
  ["거북왕나이트", "Blastoisinite"],
  ["뮤츠나이트X", "Mewtwonite X"],
  ["뮤츠나이트Y", "Mewtwonite Y"],
  ["번치코나이트", "Blazikenite"],
  ["요가램나이트", "Medichamite"],
  ["헬가나이트", "Houndoominite"],
  ["보스로라나이트", "Aggronite"],
  ["다크펫나이트", "Banettite"],
  ["마기라스나이트", "Tyranitarite"],
  ["핫삼나이트", "Scizorite"],
  ["쁘사이저나이트", "Pinsirite"],
  ["프테라나이트", "Aerodactylite"],
  ["루카리오나이트", "Lucarionite"],
  ["눈설왕나이트", "Abomasite"],
  ["캥카나이트", "Kangaskhanite"],
  ["갸라도스나이트", "Gyaradosite"],
  ["앱솔나이트", "Absolite"],
  ["후디나이트", "Alakazite"],
  ["헤라크로스나이트", "Heracronite"],
  ["입치트나이트", "Mawilite"],
  ["썬더볼트나이트", "Manectite"],
  ["한카리아스나이트", "Garchompite"],
  ["라티아스나이트", "Latiasite"],
  ["라티오스나이트", "Latiosite"],
  ["대짱이나이트", "Swampertite"],
  ["나무킹나이트", "Sceptilite"],
  ["깜까미나이트", "Sablenite"],
  ["파비코리나이트", "Altarianite"],
  ["엘레이드나이트", "Galladite"],
  ["다부니나이트", "Audinite"],
  ["메타그로스나이트", "Metagrossite"],
  ["샤크니아나이트", "Sharpedonite"],
  ["야도란나이트", "Slowbronite"],
  ["강철톤나이트", "Steelixite"],
  ["피죤투나이트", "Pidgeotite"],
  ["얼음귀신나이트", "Glalitite"],
  ["디안시나이트", "Diancite"],
  ["폭타나이트", "Cameruptite"],
  ["이어롭나이트", "Lopunnite"],
  ["보만다나이트", "Salamencite"],
  ["독침붕나이트", "Beedrillite"],
  ["노말Z", "Normalium Z"],
  ["불꽃Z", "Firium Z"],
  ["물Z", "Waterium Z"],
  ["전기Z", "Electrium Z"],
  ["풀Z", "Grassium Z"],
  ["얼음Z", "Icium Z"],
  ["격투Z", "Fightinium Z"],
  ["독Z", "Poisonium Z"],
  ["땅Z", "Groundium Z"],
  ["비행Z", "Flyinium Z"],
  ["에스퍼Z", "Psychium Z"],
  ["벌레Z", "Buginium Z"],
  ["바위Z", "Rockium Z"],
  ["고스트Z", "Ghostium Z"],
  ["드개곤Z", "Dragonium Z"],
  ["악Z", "Darkinium Z"],
  ["강철Z", "Steelium Z"],
  ["페어리Z", "Fairium Z"],
  ["피카츄Z", "Pikanium Z"],
  ["지우피카Z", "Pikashunium Z"],
  ["알로라이Z", "Aloraichium Z"],
  ["이브이Z", "Eevium Z"],
  ["잠만보Z", "Snorlium Z"],
  ["뮤Z", "Mewnium Z"],
  ["모크나이퍼Z", "Decidium Z"],
  ["어흥염Z", "Incinium Z"],
  ["누리레느Z", "Primarium Z"],
  ["카푸Z", "Tapunium Z"],
  ["마샤도Z", "Marshadium Z"],
  ["솔가레오Z", "Solganium Z"],
  ["루나아라Z", "Lunalium Z"],
  ["울트라네크로Z", "Ultranecrozium Z"],
  ["따라큐Z", "Mimikium Z"],
  ["루가루암Z", "Lycanium Z"],
  ["짜랑고우거Z", "Kommonium Z"],
  ["파이어메모리", "Fire Memory"],
  ["워터메모리", "Water Memory"],
  ["그래스메모리", "Grass Memory"],
  ["일렉트릭메모리", "Electric Memory"],
  ["아이메모리", "Ice Memory"],
  ["파이팅메모리", "Fighting Memory"],
  ["포이즌메모리", "Poison Memory"],
  ["그라운드메모리", "Ground Memory"],
  ["플라잉메모리", "Flying Memory"],
  ["사이킥메모리", "Psychic Memory"],
  ["버그메모리", "Bug Memory"],
  ["락메모리", "Rock Memory"],
  ["고스트메모리", "Ghost Memory"],
  ["드래곤메모리", "Dragon Memory"],
  ["다크모리", "Dark Memory"],
  ["스틸메모리", "Steel Memory"],
  ["페어리메모리", "Fairy Memory"],
  ["일렉트릭시드", "Electric Seed"],
  ["그래스시드", "Grassy Seed"],
  ["미스트시드", "Misty Seed"],
  ["사이코시드", "Psychic Seed"],
  ["그라운드코트", "Terrain Extender"],
  ["방호패드", "Protective Pads"],
  ["룸서비스", "Room Service"],
  ["탈출팩", "Eject Pack"],
  ["통굽부츠", "Heavy-Duty Boots"],
  ["허탕보험", "Blunder Policy"],
  ["목스프레이", "Throat Spray"],
  ["만능우산", "Utility Umbrella"],
  ["녹슨검", "Rusted Sword"],
  ["녹슨방패", "Rusted Shield"],
  ["속임수주사위", "Loaded Dice"],
  ["은밀망토", "Covert Cloak"],
  ["클리어참", "Clear Amulet"],
  ["특성가드", "Ability Shield"],
  ["펀치글러브", "Punching Glove"],
  ["부스트에너지", "Booster Energy"],
  ["흉내허브", "Mirror Herb"],
  ["큰금강옥", "Adamant Crystal"],
  ["큰백옥", "Lustrous Globe"],
  ["큰백금옥", "Griseous Core"],
  ["요정의깃털", "Fairy Feather"],
  ["우물의가면", "Wellspring Mask"],
  ["화덕의가면", "Hearthflame Mask"],
  ["주춧돌의가면", "Cornerstone Mask"],
  ["버치열매", "Cheri Berry"],
  ["유루열매", "Chesto Berry"],
  ["복슝열매", "Pecha Berry"],
  ["복분열매", "Rawst Berry"],
  ["배리열매", "Aspear Berry"],
  ["과사열매", "Leppa Berry"],
  ["오랭열매", "Oran Berry"],
  ["시몬열매", "Persim Berry"],
  ["리샘열매", "Lum Berry"],
  ["자뭉열매", "Sitrus Berry"],
  ["무화열매", "Figy Berry"],
  ["위키열매", "Wiki Berry"],
  ["마고열매", "Mago Berry"],
  ["아바열매", "Aguav Berry"],
  ["파야열매", "Iapapa Berry"],
  ["라즈열매", "Razz Berry"],
  ["블리열매", "Bluk Berry"],
  ["나나열매", "Nanab Berry"],
  ["서배열매", "Wepear Berry"],
  ["파인열매", "Pinap Berry"],
  ["유석열매", "Pomeg Berry"],
  ["시마열매", "Kelpsy Berry"],
  ["파비열매", "Qualot Berry"],
  ["로매열매", "Hondew Berry"],
  ["또뽀열매", "Grepa Berry"],
  ["토망열매", "Tamato Berry"],
  ["수숙열매", "Cornn Berry"],
  ["고스티열매", "Magost Berry"],
  ["라부탐열매", "Rabuta Berry"],
  ["노멜열매", "Nomel Berry"],
  ["메호키열매", "Spelon Berry"],
  ["자야열매", "Pamtre Berry"],
  ["슈박열매", "Watmel Berry"],
  ["두리열매", "Durin Berry"],
  ["루베열매", "Belue Berry"],
  ["치리열매", "Liechi Berry"],
  ["용아열매", "Ganlon Berry"],
  ["캄라열매", "Salac Berry"],
  ["야타비열매", "Petaya Berry"],
  ["규살열매", "Apicot Berry"],
  ["랑사열매", "Lansat Berry"],
  ["스타열매", "Starf Berry"],
  ["의문열매", "Enigma Berry"],
  ["오카열매", "Occa Berry"],
  ["꼬시개열매", "Passho Berry"],
  ["초나열매", "Wacan Berry"],
  ["린드열매", "Rindo Berry"],
  ["플카열매", "Yache Berry"],
  ["로플열매", "Chople Berry"],
  ["으름열매", "Kebia Berry"],
  ["슈캐열매", "Shuca Berry"],
  ["바코열매", "Coba Berry"],
  ["야파열매", "Payapa Berry"],
  ["리체열매", "Tanga Berry"],
  ["루미열매", "Charti Berry"],
  ["수불열매", "Kasib Berry"],
  ["하반열매", "Haban Berry"],
  ["마코열매", "Colbur Berry"],
  ["바리비열매", "Babiri Berry"],
  ["카리열매", "Chilan Berry"],
  ["미클열매", "Micle Berry"],
  ["애슈열매", "Custap Berry"],
  ["자보열매", "Jaboca Berry"],
  ["애터열매", "Rowap Berry"],
  ["로셀열매", "Roseli Berry"],
  ["악키열매", "Kee Berry"],
  ["타라프열매", "Maranga Berry"],
  ["포흐열매", "Hopo Berry"]
]);

export const zhCnToEn = new Map([
  ["光粉", "Bright Powder"],
  ["先制之爪", "Quick Claw"],
  ["王者之证", "King's Rock"],
  ["银粉", "Silver Powder"],
  ["护符金币", "Amulet Coin"],
  ["洁净之符", "Cleanse Tag"],
  ["烟雾球", "Smoke Ball"],
  ["不变之石", "Everstone"],
  ["气势头带", "Focus Band"],
  ["幸运蛋", "Lucky Egg"],
  ["焦点镜", "Scope Lens"],
  ["金属膜", "Metal Coat"],
  ["吃剩的东西", "Leftovers"],
  ["龙之鳞片", "Dragon Scale"],
  ["电气球", "Light Ball"],
  ["柔软沙子", "Soft Sand"],
  ["硬石头", "Hard Stone"],
  ["奇迹种子", "Miracle Seed"],
  ["黑色眼镜", "Black Glasses"],
  ["黑带", "Black Belt"],
  ["磁铁", "Magnet"],
  ["神秘水滴", "Mystic Water"],
  ["锐利鸟嘴", "Sharp Beak"],
  ["毒针", "Poison Barb"],
  ["不融冰", "Never-Melt Ice"],
  ["诅咒之符", "Spell Tag"],
  ["弯曲的汤匙", "Twisted Spoon"],
  ["木炭", "Charcoal"],
  ["龙之牙", "Dragon Fang"],
  ["粉红色丝带", "Pink Bow"],
  ["水玉色之带", "Polkadot Bow"],
  ["升级数据", "Up-Grade"],
  ["吉利拳", "Lucky Punch"],
  ["金属粉", "Metal Powder"],
  ["粗骨头", "Thick Club"],
  ["大葱", "Stick Leek"],
  ["破坏基因", "Berserk Gene"],
  ["白色香草", "White Herb"],
  ["强制锻炼器", "Macho Brace"],
  ["安抚之铃", "Soothe Bell"],
  ["心灵香草", "Mental Herb"],
  ["讲究头带", "Choice Band"],
  ["心之水滴", "Soul Dew"],
  ["深海之牙", "Deep Sea Tooth"],
  ["深海鳞片", "Deep Sea Scale"],
  ["丝绸围巾", "Silk Scarf"],
  ["贝壳之铃", "Shell Bell"],
  ["海潮薰香", "Sea Incense"],
  ["悠闲薰香", "Lax Incense"],
  ["红色头巾", "Red Scarf"],
  ["蓝色头巾", "Blue Scarf"],
  ["粉红头巾", "Pink Scarf"],
  ["绿色头巾", "Green Scarf"],
  ["黄色头巾", "Yellow Scarf"],
  ["朱红色宝珠", "Red Orb"],
  ["靛蓝色宝珠", "Blue Orb"],
  ["火球石板", "Flame Plate"],
  ["水滴石板", "Splash Plate"],
  ["雷电石板", "Zap Plate"],
  ["碧绿石板", "Meadow Plate"],
  ["冰柱石板", "Icicle Plate"],
  ["拳头石板", "Fist Plate"],
  ["剧毒石板", "Toxic Plate"],
  ["大地石板", "Earth Plate"],
  ["蓝天石板", "Sky Plate"],
  ["神奇石板", "Mind Plate"],
  ["玉虫石板", "Insect Plate"],
  ["岩石石板", "Stone Plate"],
  ["妖怪石板", "Spooky Plate"],
  ["龙之石板", "Draco Plate"],
  ["恶颜石板", "Dread Plate"],
  ["钢铁石板", "Iron Plate"],
  ["奇异薰香", "Odd Incense"],
  ["岩石薰香", "Rock Incense"],
  ["饱腹薰香", "Full Incense"],
  ["涟漪薰香", "Wave Incense"],
  ["花朵薰香", "Rose Incense"],
  ["幸运薰香", "Luck Incense"],
  ["洁净薰香", "Pure Incense"],
  ["护具", "Protector"],
  ["电力增幅器", "Electirizer"],
  ["熔岩增幅器", "Magmarizer"],
  ["可疑补丁", "Dubious Disc"],
  ["灵界之布", "Reaper Cloth"],
  ["锐利之爪", "Razor Claw"],
  ["锐利之牙", "Razor Fang"],
  ["浑圆之石", "Oval Stone"],
  ["金刚宝珠", "Adamant Orb"],
  ["白玉宝珠", "Lustrous Orb"],
  ["白金宝珠", "Griseous Orb"],
  ["广角镜", "Wide Lens"],
  ["力量头带", "Muscle Band"],
  ["气势披带", "Focus Sash"],
  ["博识眼镜", "Wise Glasses"],
  ["达人带", "Expert Belt"],
  ["光之黏土", "Light Clay"],
  ["生命宝珠", "Life Orb"],
  ["强力香草", "Power Herb"],
  ["剧毒宝珠", "Toxic Orb"],
  ["火焰宝珠", "Flame Orb"],
  ["速度粉", "Quick Powder"],
  ["对焦镜", "Zoom Lens"],
  ["节拍器", "Metronome"],
  ["黑色铁球", "Iron Ball"],
  ["后攻之尾", "Lagging Tail"],
  ["红线", "Destiny Knot"],
  ["黑色污泥", "Black Sludge"],
  ["冰冷岩石", "Icy Rock"],
  ["沙沙岩石", "Smooth Rock"],
  ["炽热岩石", "Heat Rock"],
  ["潮湿岩石", "Damp Rock"],
  ["紧缠钩爪", "Grip Claw"],
  ["讲究围巾", "Choice Scarf"],
  ["附着针", "Sticky Barb"],
  ["力量护腕", "Power Bracer"],
  ["力量腰带", "Power Belt"],
  ["力量镜", "Power Lens"],
  ["力量束带", "Power Band"],
  ["力量护踝", "Power Anklet"],
  ["力量负重", "Power Weight"],
  ["美丽空壳", "Shed Shell"],
  ["大根茎", "Big Root"],
  ["讲究眼镜", "Choice Specs"],
  ["水流卡带", "Douse Drive"],
  ["闪电卡带", "Shock Drive"],
  ["火焰卡带", "Burn Drive"],
  ["冰冻卡带", "Chill Drive"],
  ["美丽鳞片", "Prism Scale"],
  ["进化奇石", "Eviolite"],
  ["轻石", "Float Stone"],
  ["凸凸头盔", "Rocky Helmet"],
  ["气球", "Air Balloon"],
  ["红牌", "Red Card"],
  ["标靶", "Ring Target"],
  ["紧绑束带", "Binding Band"],
  ["球根", "Absorb Bulb"],
  ["充电电池", "Cell Battery"],
  ["逃脱按键", "Eject Button"],
  ["火之宝石", "Fire Gem"],
  ["水之宝石", "Water Gem"],
  ["电之宝石", "Electric Gem"],
  ["草之宝石", "Grass Gem"],
  ["冰之宝石", "Ice Gem"],
  ["格斗宝石", "Fighting Gem"],
  ["毒之宝石", "Poison Gem"],
  ["地面宝石", "Ground Gem"],
  ["飞行宝石", "Flying Gem"],
  ["超能力宝石", "Psychic Gem"],
  ["虫之宝石", "Bug Gem"],
  ["岩石宝石", "Rock Gem"],
  ["幽灵宝石", "Ghost Gem"],
  ["龙之宝石", "Dragon Gem"],
  ["恶之宝石", "Dark Gem"],
  ["钢之宝石", "Steel Gem"],
  ["一般宝石", "Normal Gem"],
  ["弱点保险", "Weakness Policy"],
  ["突击背心", "Assault Vest"],
  ["妖精石板", "Pixie Plate"],
  ["泡沫奶油", "Whipped Dream"],
  ["香袋", "Sachet"],
  ["光苔", "Luminous Moss"],
  ["雪球", "Snowball"],
  ["防尘护目镜", "Safety Goggles"],
  ["耿鬼进化石", "Gengarite"],
  ["沙奈朵进化石", "Gardevoirite"],
  ["电龙进化石", "Ampharosite"],
  ["妙蛙花进化石", "Venusaurite"],
  ["喷火龙进化石X", "Charizardite X"],
  ["喷火龙进化石Y", "Charizardite Y"],
  ["水箭龟进化石", "Blastoisinite"],
  ["超梦进化石X", "Mewtwonite X"],
  ["超梦进化石Y", "Mewtwonite Y"],
  ["火焰鸡进化石", "Blazikenite"],
  ["恰雷姆进化石", "Medichamite"],
  ["黑鲁加进化石", "Houndoominite"],
  ["波士可多拉进化石", "Aggronite"],
  ["诅咒娃娃进化石", "Banettite"],
  ["班基拉斯进化石", "Tyranitarite"],
  ["巨钳螳螂进化石", "Scizorite"],
  ["凯罗斯进化石", "Pinsirite"],
  ["化石翼龙进化石", "Aerodactylite"],
  ["路卡利欧进化石", "Lucarionite"],
  ["暴雪王进化石", "Abomasite"],
  ["袋兽进化石", "Kangaskhanite"],
  ["暴鲤龙进化石", "Gyaradosite"],
  ["阿勃梭鲁进化石", "Absolite"],
  ["胡地进化石", "Alakazite"],
  ["赫拉克罗斯进化石", "Heracronite"],
  ["大嘴娃进化石", "Mawilite"],
  ["雷电兽进化石", "Manectite"],
  ["烈咬陆鲨进化石", "Garchompite"],
  ["拉帝亚斯进化石", "Latiasite"],
  ["拉帝欧斯进化石", "Latiosite"],
  ["巨沼怪进化石", "Swampertite"],
  ["蜥蜴王进化石", "Sceptilite"],
  ["勾魂眼进化石", "Sablenite"],
  ["七夕青鸟进化石", "Altarianite"],
  ["艾路雷朵进化石", "Galladite"],
  ["差不多娃娃进化石", "Audinite"],
  ["巨金怪进化石", "Metagrossite"],
  ["巨牙鲨进化石", "Sharpedonite"],
  ["呆壳兽进化石", "Slowbronite"],
  ["大钢蛇进化石", "Steelixite"],
  ["大比鸟进化石", "Pidgeotite"],
  ["冰鬼护进化石", "Glalitite"],
  ["蒂安希进化石", "Diancite"],
  ["喷火驼进化石", "Cameruptite"],
  ["长耳兔进化石", "Lopunnite"],
  ["暴飞龙进化石", "Salamencite"],
  ["大针蜂进化石", "Beedrillite"],
  ["一般Z", "Normalium Z"],
  ["火Z", "Firium Z"],
  ["水Z", "Waterium Z"],
  ["电Z", "Electrium Z"],
  ["草Z", "Grassium Z"],
  ["冰Z", "Icium Z"],
  ["格斗Z", "Fightinium Z"],
  ["毒Z", "Poisonium Z"],
  ["地面Z", "Groundium Z"],
  ["飞行Z", "Flyinium Z"],
  ["超能力Z", "Psychium Z"],
  ["虫Z", "Buginium Z"],
  ["岩石Z", "Rockium Z"],
  ["幽灵Z", "Ghostium Z"],
  ["龙Z", "Dragonium Z"],
  ["恶Z", "Darkinium Z"],
  ["钢Z", "Steelium Z"],
  ["妖精Z", "Fairium Z"],
  ["皮卡丘Z", "Pikanium Z"],
  ["智皮卡Z", "Pikashunium Z"],
  ["阿罗雷Z", "Aloraichium Z"],
  ["伊布Z", "Eevium Z"],
  ["卡比兽Z", "Snorlium Z"],
  ["梦幻Z", "Mewnium Z"],
  ["狙射树枭Z", "Decidium Z"],
  ["炽焰咆哮虎Z", "Incinium Z"],
  ["西狮海壬Z", "Primarium Z"],
  ["卡璞Z", "Tapunium Z"],
  ["玛夏多Z", "Marshadium Z"],
  ["索尔迦雷欧Z", "Solganium Z"],
  ["露奈雅拉Z", "Lunalium Z"],
  ["究极奈克洛Z", "Ultranecrozium Z"],
  ["谜拟QZ", "Mimikium Z"],
  ["鬃岩狼人Z", "Lycanium Z"],
  ["杖尾鳞甲龙Z", "Kommonium Z"],
  ["火焰存储碟", "Fire Memory"],
  ["清水存储碟", "Water Memory"],
  ["青草存储碟", "Grass Memory"],
  ["电子存储碟", "Electric Memory"],
  ["冰雪存储碟", "Ice Memory"],
  ["战斗存储碟", "Fighting Memory"],
  ["毒存储碟", "Poison Memory"],
  ["大地存储碟", "Ground Memory"],
  ["飞翔存储碟", "Flying Memory"],
  ["精神存储碟", "Psychic Memory"],
  ["虫子存储碟", "Bug Memory"],
  ["岩石存储碟", "Rock Memory"],
  ["幽灵存储碟", "Ghost Memory"],
  ["龙存储碟", "Dragon Memory"],
  ["黑暗存储碟", "Dark Memory"],
  ["钢铁存储碟", "Steel Memory"],
  ["妖精存储碟", "Fairy Memory"],
  ["電氣种子", "Electric Seed"],
  ["青草种子", "Grassy Seed"],
  ["薄雾种子", "Misty Seed"],
  ["精神种子", "Psychic Seed"],
  ["大地膜", "Terrain Extender"],
  ["部位护具", "Protective Pads"],
  ["客房服务", "Room Service"],
  ["避难背包", "Eject Pack"],
  ["厚底靴", "Heavy-Duty Boots"],
  ["打空保险", "Blunder Policy"],
  ["爽喉喷雾", "Throat Spray"],
  ["万能伞", "Utility Umbrella"],
  ["腐朽的剑", "Rusted Sword"],
  ["腐朽的盾", "Rusted Shield"],
  ["机变骰子", "Loaded Dice"],
  ["密探斗篷", "Covert Cloak"],
  ["清净坠饰", "Clear Amulet"],
  ["特性护具", "Ability Shield"],
  ["拳击手套", "Punching Glove"],
  ["驱劲能量", "Booster Energy"],
  ["模仿香草", "Mirror Herb"],
  ["大金刚宝玉", "Adamant Crystal"],
  ["大白宝玉", "Lustrous Globe"],
  ["大白金宝玉", "Griseous Core"],
  ["妖精之羽", "Fairy Feather"],
  ["水井面具", "Wellspring Mask"],
  ["火灶面具", "Hearthflame Mask"],
  ["础石面具", "Cornerstone Mask"],
  ["樱子果", "Cheri Berry"],
  ["零余果", "Chesto Berry"],
  ["桃桃果", "Pecha Berry"],
  ["莓莓果", "Rawst Berry"],
  ["利木果", "Aspear Berry"],
  ["苹野果", "Leppa Berry"],
  ["橙橙果", "Oran Berry"],
  ["柿仔果", "Persim Berry"],
  ["木子果", "Lum Berry"],
  ["文柚果", "Sitrus Berry"],
  ["勿花果", "Figy Berry"],
  ["异奇果", "Wiki Berry"],
  ["芒芒果", "Mago Berry"],
  ["乐芭果", "Aguav Berry"],
  ["芭亚果", "Iapapa Berry"],
  ["蔓莓果", "Razz Berry"],
  ["墨莓果", "Bluk Berry"],
  ["蕉香果", "Nanab Berry"],
  ["西梨果", "Wepear Berry"],
  ["凰梨果", "Pinap Berry"],
  ["榴石果", "Pomeg Berry"],
  ["藻根果", "Kelpsy Berry"],
  ["比巴果", "Qualot Berry"],
  ["哈密果", "Hondew Berry"],
  ["萄葡果", "Grepa Berry"],
  ["茄番果", "Tamato Berry"],
  ["玉黍果", "Cornn Berry"],
  ["岳竹果", "Magost Berry"],
  ["茸丹果", "Rabuta Berry"],
  ["檬柠果", "Nomel Berry"],
  ["刺角果", "Spelon Berry"],
  ["椰木果", "Pamtre Berry"],
  ["瓜西果", "Watmel Berry"],
  ["金枕果", "Durin Berry"],
  ["靛莓果", "Belue Berry"],
  ["枝荔果", "Liechi Berry"],
  ["龙睛果", "Ganlon Berry"],
  ["沙鳞果", "Salac Berry"],
  ["龙火果", "Petaya Berry"],
  ["杏仔果", "Apicot Berry"],
  ["兰萨果", "Lansat Berry"],
  ["星桃果", "Starf Berry"],
  ["谜芝果", "Enigma Berry"],
  ["巧可果", "Occa Berry"],
  ["千香果", "Passho Berry"],
  ["烛木果", "Wacan Berry"],
  ["罗子果", "Rindo Berry"],
  ["番荔果", "Yache Berry"],
  ["莲蒲果", "Chople Berry"],
  ["通通果", "Kebia Berry"],
  ["腰木果", "Shuca Berry"],
  ["棱瓜果", "Coba Berry"],
  ["福禄果", "Payapa Berry"],
  ["扁樱果", "Tanga Berry"],
  ["草蚕果", "Charti Berry"],
  ["佛柑果", "Kasib Berry"],
  ["莓榴果", "Haban Berry"],
  ["刺耳果", "Colbur Berry"],
  ["霹霹果", "Babiri Berry"],
  ["灯浆果", "Chilan Berry"],
  ["奇秘果", "Micle Berry"],
  ["释陀果", "Custap Berry"],
  ["嘉珍果", "Jaboca Berry"],
  ["雾莲果", "Rowap Berry"],
  ["洛玫果", "Roseli Berry"],
  ["亚开果", "Kee Berry"],
  ["香罗果", "Maranga Berry"],
  ["花啤果", "Hopo Berry"]
]);

export const zhTwToEn = new Map([
  ["光粉", "Bright Powder"],
  ["先制之爪", "Quick Claw"],
  ["王者之證", "King's Rock"],
  ["銀粉", "Silver Powder"],
  ["護符金幣", "Amulet Coin"],
  ["潔淨之符", "Cleanse Tag"],
  ["煙霧球", "Smoke Ball"],
  ["不變之石", "Everstone"],
  ["氣勢頭帶", "Focus Band"],
  ["幸運蛋", "Lucky Egg"],
  ["焦點鏡", "Scope Lens"],
  ["金屬膜", "Metal Coat"],
  ["吃剩的東西", "Leftovers"],
  ["龍之鱗片", "Dragon Scale"],
  ["電氣球", "Light Ball"],
  ["柔軟沙子", "Soft Sand"],
  ["硬石頭", "Hard Stone"],
  ["奇跡種子", "Miracle Seed"],
  ["黑色眼鏡", "Black Glasses"],
  ["黑帶", "Black Belt"],
  ["磁鐵", "Magnet"],
  ["神秘水滴", "Mystic Water"],
  ["銳利鳥嘴", "Sharp Beak"],
  ["毒針", "Poison Barb"],
  ["不融冰", "Never-Melt Ice"],
  ["詛咒之符", "Spell Tag"],
  ["彎曲的湯匙", "Twisted Spoon"],
  ["木炭", "Charcoal"],
  ["龍之牙", "Dragon Fang"],
  ["粉红色丝带", "Pink Bow"],
  ["水玉色之带", "Polkadot Bow"],
  ["升級資料", "Up-Grade"],
  ["吉利拳", "Lucky Punch"],
  ["金屬粉", "Metal Powder"],
  ["粗骨頭", "Thick Club"],
  ["大蔥", "Stick Leek"],
  ["破壞基因", "Berserk Gene"],
  ["白色香草", "White Herb"],
  ["強制鍛鍊器", "Macho Brace"],
  ["安撫之鈴", "Soothe Bell"],
  ["心靈香草", "Mental Herb"],
  ["講究頭帶", "Choice Band"],
  ["心之水滴", "Soul Dew"],
  ["深海之牙", "Deep Sea Tooth"],
  ["深海鱗片", "Deep Sea Scale"],
  ["絲綢圍巾", "Silk Scarf"],
  ["貝殼之鈴", "Shell Bell"],
  ["海潮薰香", "Sea Incense"],
  ["悠閒薰香", "Lax Incense"],
  ["紅色頭巾", "Red Scarf"],
  ["藍色頭巾", "Blue Scarf"],
  ["粉紅頭巾", "Pink Scarf"],
  ["綠色頭巾", "Green Scarf"],
  ["黃色頭巾", "Yellow Scarf"],
  ["朱紅色寶珠", "Red Orb"],
  ["靛藍色寶珠", "Blue Orb"],
  ["火球石板", "Flame Plate"],
  ["水滴石板", "Splash Plate"],
  ["雷電石板", "Zap Plate"],
  ["碧綠石板", "Meadow Plate"],
  ["冰柱石板", "Icicle Plate"],
  ["拳頭石板", "Fist Plate"],
  ["劇毒石板", "Toxic Plate"],
  ["大地石板", "Earth Plate"],
  ["藍天石板", "Sky Plate"],
  ["神奇石板", "Mind Plate"],
  ["玉蟲石板", "Insect Plate"],
  ["岩石石板", "Stone Plate"],
  ["妖怪石板", "Spooky Plate"],
  ["龍之石板", "Draco Plate"],
  ["惡顏石板", "Dread Plate"],
  ["鋼鐵石板", "Iron Plate"],
  ["奇異薰香", "Odd Incense"],
  ["岩石薰香", "Rock Incense"],
  ["飽腹薰香", "Full Incense"],
  ["漣漪薰香", "Wave Incense"],
  ["花朵薰香", "Rose Incense"],
  ["幸運薰香", "Luck Incense"],
  ["潔淨薰香", "Pure Incense"],
  ["護具", "Protector"],
  ["電力增幅器", "Electirizer"],
  ["熔岩增幅器", "Magmarizer"],
  ["可疑修正檔", "Dubious Disc"],
  ["靈界之布", "Reaper Cloth"],
  ["銳利之爪", "Razor Claw"],
  ["銳利之牙", "Razor Fang"],
  ["渾圓之石", "Oval Stone"],
  ["金剛寶珠", "Adamant Orb"],
  ["白玉寶珠", "Lustrous Orb"],
  ["白金寶珠", "Griseous Orb"],
  ["廣角鏡", "Wide Lens"],
  ["力量頭帶", "Muscle Band"],
  ["氣勢披帶", "Focus Sash"],
  ["博識眼鏡", "Wise Glasses"],
  ["達人帶", "Expert Belt"],
  ["光之黏土", "Light Clay"],
  ["生命寶珠", "Life Orb"],
  ["強力香草", "Power Herb"],
  ["劇毒寶珠", "Toxic Orb"],
  ["火焰寶珠", "Flame Orb"],
  ["速度粉", "Quick Powder"],
  ["對焦鏡", "Zoom Lens"],
  ["節拍器", "Metronome"],
  ["黑色鐵球", "Iron Ball"],
  ["後攻之尾", "Lagging Tail"],
  ["紅線", "Destiny Knot"],
  ["黑色污泥", "Black Sludge"],
  ["冰冷岩石", "Icy Rock"],
  ["沙沙岩石", "Smooth Rock"],
  ["熾熱岩石", "Heat Rock"],
  ["潮濕岩石", "Damp Rock"],
  ["緊纏鈎爪", "Grip Claw"],
  ["講究圍巾", "Choice Scarf"],
  ["附著針", "Sticky Barb"],
  ["力量護腕", "Power Bracer"],
  ["力量腰帶", "Power Belt"],
  ["力量鏡", "Power Lens"],
  ["力量束帶", "Power Band"],
  ["力量護踝", "Power Anklet"],
  ["力量負重", "Power Weight"],
  ["美麗空殼", "Shed Shell"],
  ["大根莖", "Big Root"],
  ["講究眼鏡", "Choice Specs"],
  ["水流卡帶", "Douse Drive"],
  ["閃電卡帶", "Shock Drive"],
  ["火焰卡帶", "Burn Drive"],
  ["冰凍卡帶", "Chill Drive"],
  ["美麗鱗片", "Prism Scale"],
  ["進化奇石", "Eviolite"],
  ["輕石", "Float Stone"],
  ["凸凸頭盔", "Rocky Helmet"],
  ["氣球", "Air Balloon"],
  ["紅牌", "Red Card"],
  ["標靶", "Ring Target"],
  ["緊綁束帶", "Binding Band"],
  ["球根", "Absorb Bulb"],
  ["充電電池", "Cell Battery"],
  ["逃脫按鍵", "Eject Button"],
  ["火之寶石", "Fire Gem"],
  ["水之寶石", "Water Gem"],
  ["電之寶石", "Electric Gem"],
  ["草之寶石", "Grass Gem"],
  ["冰之寶石", "Ice Gem"],
  ["格鬥寶石", "Fighting Gem"],
  ["毒之寶石", "Poison Gem"],
  ["地面寶石", "Ground Gem"],
  ["飛行寶石", "Flying Gem"],
  ["超能力寶石", "Psychic Gem"],
  ["蟲之寶石", "Bug Gem"],
  ["岩石寶石", "Rock Gem"],
  ["幽靈寶石", "Ghost Gem"],
  ["龍之寶石", "Dragon Gem"],
  ["惡之寶石", "Dark Gem"],
  ["鋼之寶石", "Steel Gem"],
  ["一般寶石", "Normal Gem"],
  ["弱點保險", "Weakness Policy"],
  ["突擊背心", "Assault Vest"],
  ["妖精石板", "Pixie Plate"],
  ["泡沫奶油", "Whipped Dream"],
  ["香袋", "Sachet"],
  ["光苔", "Luminous Moss"],
  ["雪球", "Snowball"],
  ["防塵護目鏡", "Safety Goggles"],
  ["耿鬼進化石", "Gengarite"],
  ["沙奈朵進化石", "Gardevoirite"],
  ["電龍進化石", "Ampharosite"],
  ["妙蛙花進化石", "Venusaurite"],
  ["噴火龍進化石Ｘ", "Charizardite X"],
  ["噴火龍進化石Ｙ", "Charizardite Y"],
  ["水箭龜進化石", "Blastoisinite"],
  ["超夢進化石Ｘ", "Mewtwonite X"],
  ["超夢進化石Ｙ", "Mewtwonite Y"],
  ["火焰雞進化石", "Blazikenite"],
  ["恰雷姆進化石", "Medichamite"],
  ["黑魯加進化石", "Houndoominite"],
  ["波士可多拉進化石", "Aggronite"],
  ["詛咒娃娃進化石", "Banettite"],
  ["班基拉斯進化石", "Tyranitarite"],
  ["巨鉗螳螂進化石", "Scizorite"],
  ["凱羅斯進化石", "Pinsirite"],
  ["化石翼龍進化石", "Aerodactylite"],
  ["路卡利歐進化石", "Lucarionite"],
  ["暴雪王進化石", "Abomasite"],
  ["袋獸進化石", "Kangaskhanite"],
  ["暴鯉龍進化石", "Gyaradosite"],
  ["阿勃梭魯進化石", "Absolite"],
  ["胡地進化石", "Alakazite"],
  ["赫拉克羅斯進化石", "Heracronite"],
  ["大嘴娃進化石", "Mawilite"],
  ["雷電獸進化石", "Manectite"],
  ["烈咬陸鯊進化石", "Garchompite"],
  ["拉帝亞斯進化石", "Latiasite"],
  ["拉帝歐斯進化石", "Latiosite"],
  ["巨沼怪進化石", "Swampertite"],
  ["蜥蜴王進化石", "Sceptilite"],
  ["勾魂眼進化石", "Sablenite"],
  ["七夕青鳥進化石", "Altarianite"],
  ["艾路雷朵進化石", "Galladite"],
  ["差不多娃娃進化石", "Audinite"],
  ["巨金怪進化石", "Metagrossite"],
  ["巨牙鯊進化石", "Sharpedonite"],
  ["呆殼獸進化石", "Slowbronite"],
  ["大鋼蛇進化石", "Steelixite"],
  ["大比鳥進化石", "Pidgeotite"],
  ["冰鬼護進化石", "Glalitite"],
  ["蒂安希進化石", "Diancite"],
  ["噴火駝進化石", "Cameruptite"],
  ["長耳兔進化石", "Lopunnite"],
  ["暴飛龍進化石", "Salamencite"],
  ["大針蜂進化石", "Beedrillite"],
  ["一般Z", "Normalium Z"],
  ["火Z", "Firium Z"],
  ["水Z", "Waterium Z"],
  ["電Z", "Electrium Z"],
  ["草Z", "Grassium Z"],
  ["冰Z", "Icium Z"],
  ["格鬥Z", "Fightinium Z"],
  ["毒Z", "Poisonium Z"],
  ["地面Z", "Groundium Z"],
  ["飛行Z", "Flyinium Z"],
  ["超能力Z", "Psychium Z"],
  ["蟲Z", "Buginium Z"],
  ["岩石Z", "Rockium Z"],
  ["幽靈Z", "Ghostium Z"],
  ["龍Z", "Dragonium Z"],
  ["惡Z", "Darkinium Z"],
  ["鋼Z", "Steelium Z"],
  ["妖精Z", "Fairium Z"],
  ["皮卡丘Z", "Pikanium Z"],
  ["智皮卡Z", "Pikashunium Z"],
  ["阿羅雷Z", "Aloraichium Z"],
  ["伊布Z", "Eevium Z"],
  ["卡比獸Z", "Snorlium Z"],
  ["夢幻Z", "Mewnium Z"],
  ["狙射樹梟Z", "Decidium Z"],
  ["熾焰咆哮虎Z", "Incinium Z"],
  ["西獅海壬Z", "Primarium Z"],
  ["卡璞Z", "Tapunium Z"],
  ["瑪夏多Z", "Marshadium Z"],
  ["索爾迦雷歐Z", "Solganium Z"],
  ["露奈雅拉Z", "Lunalium Z"],
  ["究極奈克洛Z", "Ultranecrozium Z"],
  ["謎擬QZ", "Mimikium Z"],
  ["鬃岩狼人Z", "Lycanium Z"],
  ["杖尾鱗甲龍Z", "Kommonium Z"],
  ["火焰記憶碟", "Fire Memory"],
  ["清水記憶碟", "Water Memory"],
  ["青草記憶碟", "Grass Memory"],
  ["電子記憶碟", "Electric Memory"],
  ["冰雪記憶碟", "Ice Memory"],
  ["戰鬥記憶碟", "Fighting Memory"],
  ["毒記憶碟", "Poison Memory"],
  ["大地記憶碟", "Ground Memory"],
  ["飛翔記憶碟", "Flying Memory"],
  ["精神記憶碟", "Psychic Memory"],
  ["蟲子記憶碟", "Bug Memory"],
  ["岩石記憶碟", "Rock Memory"],
  ["幽靈記憶碟", "Ghost Memory"],
  ["龍記憶碟", "Dragon Memory"],
  ["黑暗記憶碟", "Dark Memory"],
  ["鋼鐵記憶碟", "Steel Memory"],
  ["妖精記憶碟", "Fairy Memory"],
  ["電氣種子", "Electric Seed"],
  ["青草種子", "Grassy Seed"],
  ["薄霧種子", "Misty Seed"],
  ["精神種子", "Psychic Seed"],
  ["大地膜", "Terrain Extender"],
  ["部位護具", "Protective Pads"],
  ["客房服務", "Room Service"],
  ["避難背包", "Eject Pack"],
  ["厚底靴", "Heavy-Duty Boots"],
  ["打空保險", "Blunder Policy"],
  ["爽喉噴霧", "Throat Spray"],
  ["萬能傘", "Utility Umbrella"],
  ["腐朽的劍", "Rusted Sword"],
  ["腐朽的盾", "Rusted Shield"],
  ["老千骰子", "Loaded Dice"],
  ["密探斗篷", "Covert Cloak"],
  ["清淨墜飾", "Clear Amulet"],
  ["特性護具", "Ability Shield"],
  ["拳擊手套", "Punching Glove"],
  ["驅勁能量", "Booster Energy"],
  ["模仿香草", "Mirror Herb"],
  ["大金剛寶玉", "Adamant Crystal"],
  ["大白寶玉", "Lustrous Globe"],
  ["大白金寶玉", "Griseous Core"],
  ["妖精之羽", "Fairy Feather"],
  ["水井面具", "Wellspring Mask"],
  ["火灶面具", "Hearthflame Mask"],
  ["礎石面具", "Cornerstone Mask"],
  ["櫻子果", "Cheri Berry"],
  ["零餘果", "Chesto Berry"],
  ["桃桃果", "Pecha Berry"],
  ["莓莓果", "Rawst Berry"],
  ["利木果", "Aspear Berry"],
  ["蘋野果", "Leppa Berry"],
  ["橙橙果", "Oran Berry"],
  ["柿仔果", "Persim Berry"],
  ["木子果", "Lum Berry"],
  ["文柚果", "Sitrus Berry"],
  ["勿花果", "Figy Berry"],
  ["異奇果", "Wiki Berry"],
  ["芒芒果", "Mago Berry"],
  ["樂芭果", "Aguav Berry"],
  ["芭亞果", "Iapapa Berry"],
  ["蔓莓果", "Razz Berry"],
  ["墨莓果", "Bluk Berry"],
  ["蕉香果", "Nanab Berry"],
  ["西梨果", "Wepear Berry"],
  ["凰梨果", "Pinap Berry"],
  ["榴石果", "Pomeg Berry"],
  ["藻根果", "Kelpsy Berry"],
  ["比巴果", "Qualot Berry"],
  ["哈密果", "Hondew Berry"],
  ["萄葡果", "Grepa Berry"],
  ["茄番果", "Tamato Berry"],
  ["玉黍果", "Cornn Berry"],
  ["岳竹果", "Magost Berry"],
  ["茸丹果", "Rabuta Berry"],
  ["檬檸果", "Nomel Berry"],
  ["刺角果", "Spelon Berry"],
  ["椰木果", "Pamtre Berry"],
  ["瓜西果", "Watmel Berry"],
  ["金枕果", "Durin Berry"],
  ["靛莓果", "Belue Berry"],
  ["枝荔果", "Liechi Berry"],
  ["龍睛果", "Ganlon Berry"],
  ["沙鱗果", "Salac Berry"],
  ["龍火果", "Petaya Berry"],
  ["杏仔果", "Apicot Berry"],
  ["蘭薩果", "Lansat Berry"],
  ["星桃果", "Starf Berry"],
  ["謎芝果", "Enigma Berry"],
  ["巧可果", "Occa Berry"],
  ["千香果", "Passho Berry"],
  ["燭木果", "Wacan Berry"],
  ["羅子果", "Rindo Berry"],
  ["番荔果", "Yache Berry"],
  ["蓮蒲果", "Chople Berry"],
  ["通通果", "Kebia Berry"],
  ["腰木果", "Shuca Berry"],
  ["棱瓜果", "Coba Berry"],
  ["福祿果", "Payapa Berry"],
  ["扁櫻果", "Tanga Berry"],
  ["草蠶果", "Charti Berry"],
  ["佛柑果", "Kasib Berry"],
  ["莓榴果", "Haban Berry"],
  ["刺耳果", "Colbur Berry"],
  ["霹霹果", "Babiri Berry"],
  ["燈漿果", "Chilan Berry"],
  ["奇秘果", "Micle Berry"],
  ["釋陀果", "Custap Berry"],
  ["嘉珍果", "Jaboca Berry"],
  ["霧蓮果", "Rowap Berry"],
  ["洛玫果", "Roseli Berry"],
  ["亞開果", "Kee Berry"],
  ["香羅果", "Maranga Berry"],
  ["花啤果", "Hopo Berry"]
]);

