export const jaToEn = new Map([
  ["あくしゅう", "Stench"],
  ["あめふらし", "Drizzle"],
  ["かそく", "Speed Boost"],
  ["カブトアーマー", "Battle Armor"],
  ["がんじょう", "Sturdy"],
  ["しめりけ", "Damp"],
  ["じゅうなん", "Limber"],
  ["すながくれ", "Sand Veil"],
  ["せいでんき", "Static"],
  ["ちくでん", "Volt Absorb"],
  ["ちょすい", "Water Absorb"],
  ["どんかん", "Oblivious"],
  ["ノーてんき", "Cloud Nine"],
  ["ふくがん", "Compound Eyes"],
  ["ふみん", "Insomnia"],
  ["へんしょく", "Color Change"],
  ["めんえき", "Immunity"],
  ["もらいび", "Flash Fire"],
  ["りんぷん", "Shield Dust"],
  ["マイペース", "Own Tempo"],
  ["きゅうばん", "Suction Cups"],
  ["いかく", "Intimidate"],
  ["かげふみ", "Shadow Tag"],
  ["さめはだ", "Rough Skin"],
  ["ふしぎなまもり", "Wonder Guard"],
  ["ふゆう", "Levitate"],
  ["ほうし", "Effect Spore"],
  ["シンクロ", "Synchronize"],
  ["クリアボディ", "Clear Body"],
  ["しぜんかいふく", "Natural Cure"],
  ["ひらいしん", "Lightning Rod"],
  ["てんのめぐみ", "Serene Grace"],
  ["すいすい", "Swift Swim"],
  ["ようりょくそ", "Chlorophyll"],
  ["はっこう", "Illuminate"],
  ["トレース", "Trace"],
  ["ちからもち", "Huge Power"],
  ["どくのトゲ", "Poison Point"],
  ["せいしんりょく", "Inner Focus"],
  ["マグマのよろい", "Magma Armor"],
  ["みずのベール", "Water Veil"],
  ["じりょく", "Magnet Pull"],
  ["ぼうおん", "Soundproof"],
  ["あめうけざら", "Rain Dish"],
  ["すなおこし", "Sand Stream"],
  ["プレッシャー", "Pressure"],
  ["あついしぼう", "Thick Fat"],
  ["はやおき", "Early Bird"],
  ["ほのおのからだ", "Flame Body"],
  ["にげあし", "Run Away"],
  ["するどいめ", "Keen Eye"],
  ["かいりきバサミ", "Hyper Cutter"],
  ["ものひろい", "Pickup"],
  ["なまけ", "Truant"],
  ["はりきり", "Hustle"],
  ["メロメロボディ", "Cute Charm"],
  ["プラス", "Plus"],
  ["マイナス", "Minus"],
  ["てんきや", "Forecast"],
  ["ねんちゃく", "Sticky Hold"],
  ["だっぴ", "Shed Skin"],
  ["こんじょう", "Guts"],
  ["ふしぎなうろこ", "Marvel Scale"],
  ["ヘドロえき", "Liquid Ooze"],
  ["しんりょく", "Overgrow"],
  ["もうか", "Blaze"],
  ["げきりゅう", "Torrent"],
  ["むしのしらせ", "Swarm"],
  ["いしあたま", "Rock Head"],
  ["ひでり", "Drought"],
  ["ありじごく", "Arena Trap"],
  ["やるき", "Vital Spirit"],
  ["しろいけむり", "White Smoke"],
  ["ヨガパワー", "Pure Power"],
  ["シェルアーマー", "Shell Armor"],
  ["エアロック", "Air Lock"],
  ["ちどりあし", "Tangled Feet"],
  ["でんきエンジン", "Motor Drive"],
  ["とうそうしん", "Rivalry"],
  ["ふくつのこころ", "Steadfast"],
  ["ゆきがくれ", "Snow Cloak"],
  ["くいしんぼう", "Gluttony"],
  ["いかりのつぼ", "Anger Point"],
  ["かるわざ", "Unburden"],
  ["たいねつ", "Heatproof"],
  ["たんじゅん", "Simple"],
  ["かんそうはだ", "Dry Skin"],
  ["ダウンロード", "Download"],
  ["てつのこぶし", "Iron Fist"],
  ["ポイズンヒール", "Poison Heal"],
  ["てきおうりょく", "Adaptability"],
  ["スキルリンク", "Skill Link"],
  ["うるおいボディ", "Hydration"],
  ["サンパワー", "Solar Power"],
  ["はやあし", "Quick Feet"],
  ["ノーマルスキン", "Normalize"],
  ["スナイパー", "Sniper"],
  ["マジックガード", "Magic Guard"],
  ["ノーガード", "No Guard"],
  ["あとだし", "Stall"],
  ["テクニシャン", "Technician"],
  ["リーフガード", "Leaf Guard"],
  ["ぶきよう", "Klutz"],
  ["かたやぶり", "Mold Breaker"],
  ["きょううん", "Super Luck"],
  ["ゆうばく", "Aftermath"],
  ["きけんよち", "Anticipation"],
  ["よちむ", "Forewarn"],
  ["てんねん", "Unaware"],
  ["いろめがね", "Tinted Lens"],
  ["フィルター", "Filter"],
  ["スロースタート", "Slow Start"],
  ["きもったま", "Scrappy"],
  ["よびみず", "Storm Drain"],
  ["アイスボディ", "Ice Body"],
  ["ハードロック", "Solid Rock"],
  ["ゆきふらし", "Snow Warning"],
  ["みつあつめ", "Honey Gather"],
  ["おみとおし", "Frisk"],
  ["すてみ", "Reckless"],
  ["マルチタイプ", "Multitype"],
  ["フラワーギフト", "Flower Gift"],
  ["ナイトメア", "Bad Dreams"],
  ["わるいてぐせ", "Pickpocket"],
  ["ちからずく", "Sheer Force"],
  ["あまのじゃく", "Contrary"],
  ["きんちょうかん", "Unnerve"],
  ["まけんき", "Defiant"],
  ["よわき", "Defeatist"],
  ["のろわれボディ", "Cursed Body"],
  ["いやしのこころ", "Healer"],
  ["フレンドガード", "Friend Guard"],
  ["くだけるよろい", "Weak Armor"],
  ["ヘヴィメタル", "Heavy Metal"],
  ["ライトメタル", "Light Metal"],
  ["マルチスケイル", "Multiscale"],
  ["どくぼうそう", "Toxic Boost"],
  ["ねつぼうそう", "Flare Boost"],
  ["しゅうかく", "Harvest"],
  ["テレパシー", "Telepathy"],
  ["ムラっけ", "Moody"],
  ["ぼうじん", "Overcoat"],
  ["どくしゅ", "Poison Touch"],
  ["さいせいりょく", "Regenerator"],
  ["はとむね", "Big Pecks"],
  ["すなかき", "Sand Rush"],
  ["ミラクルスキン", "Wonder Skin"],
  ["アナライズ", "Analytic"],
  ["イリュージョン", "Illusion"],
  ["かわりもの", "Imposter"],
  ["すりぬけ", "Infiltrator"],
  ["ミイラ", "Mummy"],
  ["じしんかじょう", "Moxie"],
  ["せいぎのこころ", "Justified"],
  ["びびり", "Rattled"],
  ["マジックミラー", "Magic Bounce"],
  ["そうしょく", "Sap Sipper"],
  ["いたずらごころ", "Prankster"],
  ["すなのちから", "Sand Force"],
  ["てつのトゲ", "Iron Barbs"],
  ["ダルマモード", "Zen Mode"],
  ["しょうりのほし", "Victory Star"],
  ["ターボブレイズ", "Turboblaze"],
  ["テラボルテージ", "Teravolt"],
  ["アロマベール", "Aroma Veil"],
  ["フラワーベール", "Flower Veil"],
  ["ほおぶくろ", "Cheek Pouch"],
  ["へんげんじざい", "Protean"],
  ["ファーコート", "Fur Coat"],
  ["マジシャン", "Magician"],
  ["ぼうだん", "Bulletproof"],
  ["かちき", "Competitive"],
  ["がんじょうあご", "Strong Jaw"],
  ["フリーズスキン", "Refrigerate"],
  ["スイートベール", "Sweet Veil"],
  ["バトルスイッチ", "Stance Change"],
  ["はやてのつばさ", "Gale Wings"],
  ["メガランチャー", "Mega Launcher"],
  ["くさのけがわ", "Grass Pelt"],
  ["きょうせい", "Symbiosis"],
  ["かたいツメ", "Tough Claws"],
  ["フェアリースキン", "Pixilate"],
  ["ぬめぬめ", "Gooey"],
  ["スカイスキン", "Aerilate"],
  ["おやこあい", "Parental Bond"],
  ["ダークオーラ", "Dark Aura"],
  ["フェアリーオーラ", "Fairy Aura"],
  ["オーラブレイク", "Aura Break"],
  ["はじまりのうみ", "Primordial Sea"],
  ["おわりのだいち", "Desolate Land"],
  ["デルタストリーム", "Delta Stream"],
  ["じきゅうりょく", "Stamina"],
  ["にげごし", "Wimp Out"],
  ["ききかいひ", "Emergency Exit"],
  ["みずがため", "Water Compaction"],
  ["ひとでなし", "Merciless"],
  ["リミットシールド", "Shields Down"],
  ["はりこみ", "Stakeout"],
  ["すいほう", "Water Bubble"],
  ["はがねつかい", "Steelworker"],
  ["ぎゃくじょう", "Berserk"],
  ["ゆきかき", "Slush Rush"],
  ["えんかく", "Long Reach"],
  ["うるおいボイス", "Liquid Voice"],
  ["ヒーリングシフト", "Triage"],
  ["エレキスキン", "Galvanize"],
  ["サーフテール", "Surge Surfer"],
  ["ぎょぐん", "Schooling"],
  ["ばけのかわ", "Disguise"],
  ["きずなへんげ", "Battle Bond"],
  ["スワームチェンジ", "Power Construct"],
  ["ふしょく", "Corrosion"],
  ["ぜったいねむり", "Comatose"],
  ["じょおうのいげん", "Queenly Majesty"],
  ["とびだすなかみ", "Innards Out"],
  ["おどりこ", "Dancer"],
  ["バッテリー", "Battery"],
  ["もふもふ", "Fluffy"],
  ["ビビッドボディ", "Dazzling"],
  ["ソウルハート", "Soul-Heart"],
  ["カーリーヘアー", "Tangling Hair"],
  ["レシーバー", "Receiver"],
  ["かがくのちから", "Power of Alchemy"],
  ["ビーストブースト", "Beast Boost"],
  ["ARシステム", "RKS System"],
  ["エレキメイカー", "Electric Surge"],
  ["サイコメイカー", "Psychic Surge"],
  ["ミストメイカー", "Misty Surge"],
  ["グラスメイカー", "Grassy Surge"],
  ["メタルプロテクト", "Full Metal Body"],
  ["ファントムガード", "Shadow Shield"],
  ["プリズムアーマー", "Prism Armor"],
  ["ブレインフォース", "Neuroforce"],
  ["ふとうのけん", "Intrepid Sword"],
  ["ふくつのたて", "Dauntless Shield"],
  ["リベロ", "Libero"],
  ["たまひろい", "Ball Fetch"],
  ["わたげ", "Cotton Down"],
  ["スクリューおびれ", "Propeller Tail"],
  ["ミラーアーマー", "Mirror Armor"],
  ["うのミサイル", "Gulp Missile"],
  ["すじがねいり", "Stalwart"],
  ["じょうききかん", "Steam Engine"],
  ["パンクロック", "Punk Rock"],
  ["すなはき", "Sand Spit"],
  ["こおりのりんぷん", "Ice Scales"],
  ["じゅくせい", "Ripen"],
  ["アイスフェイス", "Ice Face"],
  ["パワースポット", "Power Spot"],
  ["ぎたい", "Mimicry"],
  ["バリアフリー", "Screen Cleaner"],
  ["はがねのせいしん", "Steely Spirit"],
  ["ほろびのボディ", "Perish Body"],
  ["さまようたましい", "Wandering Spirit"],
  ["ごりむちゅう", "Gorilla Tactics"],
  ["かがくへんかガス", "Neutralizing Gas"],
  ["パステルベール", "Pastel Veil"],
  ["はらぺこスイッチ", "Hunger Switch"],
  ["クイックドロウ", "Quick Draw"],
  ["ふかしのこぶし", "Unseen Fist"],
  ["トランジスタ", "Transistor"],
  ["りゅうのあぎと", "Dragon's Maw"],
  ["きみょうなくすり", "Curious Medicine"],
  ["しろのいななき", "Chilling Neigh"],
  ["くろのいななき", "Grim Neigh"],
  ["じんばいったい", "As One"],
  ["いかりのこうら", "Anger Shell"],
  ["いわはこび", "Rocky Payload"],
  ["おうごんのからだ", "Good as Gold"],
  ["おもかげやどし", "Embody Aspect"],
  ["おもてなし", "Hospitality"],
  ["かぜのり", "Wind Rider"],
  ["かんろなミツ", "Supersweet Syrup"],
  ["きょうえん", "Costar"],
  ["きよめのしお", "Purifying Salt"],
  ["きれあじ", "Sharpness"],
  ["きんしのちから", "Mycelium Might"],
  ["クォークチャージ", "Quark Drive"],
  ["こだいかっせい", "Protosynthesis"],
  ["こぼれダネ", "Seed Sower"],
  ["こんがりボディ", "Well-Baked Body"],
  ["しれいとう", "Commander"],
  ["しんがん", "Mind's Eye"],
  ["ゼロフォーミング", "Teraform Zero"],
  ["そうだいしょう", "Supreme Overlord"],
  ["テイルアーマー", "Armor Tail"],
  ["テラスシェル", "Tera Shell"],
  ["テラスチェンジ", "Tera Shift"],
  ["でんきにかえる", "Electromorphosis"],
  ["どくくぐつ", "Poison Puppeteer"],
  ["どくげしょう", "Toxic Debris"],
  ["どくのくさり", "Toxic Chain"],
  ["どしょく", "Earth Eater"],
  ["とれないにおい", "Lingering Aroma"],
  ["ねつこうかん", "Thermal Exchange"],
  ["ハドロンエンジン", "Hadron Engine"],
  ["ばんけん", "Guard Dog"],
  ["はんすう", "Cud Chew"],
  ["ひひいろのこどう", "Orichalcum Pulse"],
  ["びんじょう", "Opportunist"],
  ["ふうりょくでんき", "Wind Power"],
  ["マイティチェンジ", "Zero to Hero"],
  ["わざわいのうつわ", "Vessel of Ruin"],
  ["わざわいのおふだ", "Tablets of Ruin"],
  ["わざわいのたま", "Beads of Ruin"],
  ["わざわいのつるぎ", "Sword of Ruin"]
]);

export const frToEn = new Map([
  ["Puanteur", "Stench"],
  ["Crachin", "Drizzle"],
  ["Turbo", "Speed Boost"],
  ["Armurbaston", "Battle Armor"],
  ["Fermeté", "Sturdy"],
  ["Moiteur", "Damp"],
  ["Échauffement", "Limber"],
  ["Voile Sable", "Sand Veil"],
  ["Statik", "Static"],
  ["Absorb Volt", "Volt Absorb"],
  ["Absorb Eau", "Water Absorb"],
  ["Benêt", "Oblivious"],
  ["Ciel Gris", "Cloud Nine"],
  ["Œil Composé", "Compound Eyes"],
  ["Insomnia", "Insomnia"],
  ["Déguisement", "Color Change"],
  ["Vaccin", "Immunity"],
  ["Torche", "Flash Fire"],
  ["Écran Poudre", "Shield Dust"],
  ["Tempo Perso", "Own Tempo"],
  ["Ventouse", "Suction Cups"],
  ["Intimidation", "Intimidate"],
  ["Marque Ombre", "Shadow Tag"],
  ["Peau Dure", "Rough Skin"],
  ["Garde Mystik", "Wonder Guard"],
  ["Lévitation", "Levitate"],
  ["Pose Spore", "Effect Spore"],
  ["Synchro", "Synchronize"],
  ["Corps Sain", "Clear Body"],
  ["Médic Nature", "Natural Cure"],
  ["Paratonnerre", "Lightning Rod"],
  ["Sérénité", "Serene Grace"],
  ["Glissade", "Swift Swim"],
  ["Chlorophylle", "Chlorophyll"],
  ["Lumiattirance", "Illuminate"],
  ["Calque", "Trace"],
  ["Coloforce", "Huge Power"],
  ["Point Poison", "Poison Point"],
  ["Attention", "Inner Focus"],
  ["Armumagma", "Magma Armor"],
  ["Ignifu-Voile", "Water Veil"],
  ["Magnépiège", "Magnet Pull"],
  ["Anti-Bruit", "Soundproof"],
  ["Cuvette", "Rain Dish"],
  ["Sable Volant", "Sand Stream"],
  ["Pression", "Pressure"],
  ["Isograisse", "Thick Fat"],
  ["Matinal", "Early Bird"],
  ["Corps Ardent", "Flame Body"],
  ["Fuite", "Run Away"],
  ["Regard Vif", "Keen Eye"],
  ["Hyper Cutter", "Hyper Cutter"],
  ["Ramassage", "Pickup"],
  ["Absentéisme", "Truant"],
  ["Agitation", "Hustle"],
  ["Joli Sourire", "Cute Charm"],
  ["Plus", "Plus"],
  ["Minus", "Minus"],
  ["Météo", "Forecast"],
  ["Glue", "Sticky Hold"],
  ["Mue", "Shed Skin"],
  ["Cran", "Guts"],
  ["Écaille Spéciale", "Marvel Scale"],
  ["Suintement", "Liquid Ooze"],
  ["Engrais", "Overgrow"],
  ["Brasier", "Blaze"],
  ["Torrent", "Torrent"],
  ["Essaim", "Swarm"],
  ["Tête de Roc", "Rock Head"],
  ["Sécheresse", "Drought"],
  ["Piège Sable", "Arena Trap"],
  ["Esprit Vital", "Vital Spirit"],
  ["Écran Fumée", "White Smoke"],
  ["Force Pure", "Pure Power"],
  ["Coque Armure", "Shell Armor"],
  ["Air Lock", "Air Lock"],
  ["Pieds Confus", "Tangled Feet"],
  ["Motorisé", "Motor Drive"],
  ["Rivalité", "Rivalry"],
  ["Impassible", "Steadfast"],
  ["Rideau Neige", "Snow Cloak"],
  ["Gloutonnerie", "Gluttony"],
  ["Colérique", "Anger Point"],
  ["Délestage", "Unburden"],
  ["Ignifugé", "Heatproof"],
  ["Simple", "Simple"],
  ["Peau Sèche", "Dry Skin"],
  ["Télécharge", "Download"],
  ["Poing de Fer", "Iron Fist"],
  ["Soin Poison", "Poison Heal"],
  ["Adaptabilité", "Adaptability"],
  ["Multi-Coups", "Skill Link"],
  ["Hydratation", "Hydration"],
  ["Force Soleil", "Solar Power"],
  ["Pied Véloce", "Quick Feet"],
  ["Normalise", "Normalize"],
  ["Sniper", "Sniper"],
  ["Garde Magik", "Magic Guard"],
  ["Annule Garde", "No Guard"],
  ["Frein", "Stall"],
  ["Technicien", "Technician"],
  ["Feuille Garde", "Leaf Guard"],
  ["Maladresse", "Klutz"],
  ["Brise Moule", "Mold Breaker"],
  ["Chanceux", "Super Luck"],
  ["Boom Final", "Aftermath"],
  ["Anticipation", "Anticipation"],
  ["Prédiction", "Forewarn"],
  ["Inconscient", "Unaware"],
  ["Lentiteintée", "Tinted Lens"],
  ["Filtre", "Filter"],
  ["Début Calme", "Slow Start"],
  ["Querelleur", "Scrappy"],
  ["Lavabo", "Storm Drain"],
  ["Corps Gel", "Ice Body"],
  ["Solide Roc", "Solid Rock"],
  ["Alerte Neige", "Snow Warning"],
  ["Cherche Miel", "Honey Gather"],
  ["Fouille", "Frisk"],
  ["Téméraire", "Reckless"],
  ["Multi-Type", "Multitype"],
  ["Don Floral", "Flower Gift"],
  ["Mauvais Rêve", "Bad Dreams"],
  ["Pickpocket", "Pickpocket"],
  ["Sans Limite", "Sheer Force"],
  ["Contestation", "Contrary"],
  ["Tension", "Unnerve"],
  ["Acharné", "Defiant"],
  ["Défaitiste", "Defeatist"],
  ["Corps Maudit", "Cursed Body"],
  ["Cœur Soin", "Healer"],
  ["Garde Amie", "Friend Guard"],
  ["Armurouillée", "Weak Armor"],
  ["Heavy Metal", "Heavy Metal"],
  ["Light Metal", "Light Metal"],
  ["Multiécaille", "Multiscale"],
  ["Rage Poison", "Toxic Boost"],
  ["Rage Brûlure", "Flare Boost"],
  ["Récolte", "Harvest"],
  ["Télépathe", "Telepathy"],
  ["Lunatique", "Moody"],
  ["Envelocape", "Overcoat"],
  ["Toxitouche", "Poison Touch"],
  ["Régé-Force", "Regenerator"],
  ["Cœur de Coq", "Big Pecks"],
  ["Baigne Sable", "Sand Rush"],
  ["Peau Miracle", "Wonder Skin"],
  ["Analyste", "Analytic"],
  ["Illusion", "Illusion"],
  ["Imposteur", "Imposter"],
  ["Infiltration", "Infiltrator"],
  ["Momie", "Mummy"],
  ["Impudence", "Moxie"],
  ["Cœur Noble", "Justified"],
  ["Phobique", "Rattled"],
  ["Miroir Magik", "Magic Bounce"],
  ["Herbivore", "Sap Sipper"],
  ["Farceur", "Prankster"],
  ["Force Sable", "Sand Force"],
  ["Épine de Fer", "Iron Barbs"],
  ["Mode Transe", "Zen Mode"],
  ["Victorieux", "Victory Star"],
  ["TurboBrasier", "Turboblaze"],
  ["Téra-Voltage", "Teravolt"],
  ["Aroma-Voile", "Aroma Veil"],
  ["Flora-Voile", "Flower Veil"],
  ["Bajoues", "Cheek Pouch"],
  ["Protéen", "Protean"],
  ["Toison Épaisse", "Fur Coat"],
  ["Magicien", "Magician"],
  ["Pare-Balles", "Bulletproof"],
  ["Battant", "Competitive"],
  ["Prognathe", "Strong Jaw"],
  ["Peau Gelée", "Refrigerate"],
  ["Gluco-Voile", "Sweet Veil"],
  ["Déclic Tactique", "Stance Change"],
  ["Ailes Bourrasque", "Gale Wings"],
  ["Méga Blaster", "Mega Launcher"],
  ["Toison Herbue", "Grass Pelt"],
  ["Symbiose", "Symbiosis"],
  ["Griffe Dure", "Tough Claws"],
  ["Peau Féérique", "Pixilate"],
  ["Poisseux", "Gooey"],
  ["Peau Céleste", "Aerilate"],
  ["Amour Filial", "Parental Bond"],
  ["Aura Ténébreuse", "Dark Aura"],
  ["Aura Féérique", "Fairy Aura"],
  ["Aura Inversée", "Aura Break"],
  ["Mer Primaire", "Primordial Sea"],
  ["Terre Finale", "Desolate Land"],
  ["Souffle Delta", "Delta Stream"],
  ["Endurance", "Stamina"],
  ["Escampette", "Wimp Out"],
  ["Repli Tactique", "Emergency Exit"],
  ["Sable Humide", "Water Compaction"],
  ["Cruauté", "Merciless"],
  ["Bouclier-Carcan", "Shields Down"],
  ["Filature", "Stakeout"],
  ["Aquabulle", "Water Bubble"],
  ["Expert Acier", "Steelworker"],
  ["Dracolère", "Berserk"],
  ["Chasse-Neige", "Slush Rush"],
  ["Longue Portée", "Long Reach"],
  ["Hydrata-Son", "Liquid Voice"],
  ["Prioguérison", "Triage"],
  ["Peau Électrique", "Galvanize"],
  ["Surf Caudal", "Surge Surfer"],
  ["Banc", "Schooling"],
  ["Fantômasque", "Disguise"],
  ["Synergie", "Battle Bond"],
  ["Rassemblement", "Power Construct"],
  ["Corrosion", "Corrosion"],
  ["Hypersommeil", "Comatose"],
  ["Prestance Royale", "Queenly Majesty"],
  ["Expuls’Organes", "Innards Out"],
  ["Danseuse", "Dancer"],
  ["Batterie", "Battery"],
  ["Boule de Poils", "Fluffy"],
  ["Corps Coloré", "Dazzling"],
  ["Animacœur", "Soul-Heart"],
  ["Mèche Rebelle", "Tangling Hair"],
  ["Receveur", "Receiver"],
  ["Osmose", "Power of Alchemy"],
  ["Boost Chimère", "Beast Boost"],
  ["Système Alpha", "RKS System"],
  ["Créa-Élec", "Electric Surge"],
  ["Créa-Psy", "Psychic Surge"],
  ["Créa-Brume", "Misty Surge"],
  ["Créa-Herbe", "Grassy Surge"],
  ["Métallo-Garde", "Full Metal Body"],
  ["Spectro-Bouclier", "Shadow Shield"],
  ["Prisme-Armure", "Prism Armor"],
  ["Cérébro-Force", "Neuroforce"],
  ["Lame Indomptable", "Intrepid Sword"],
  ["Égide Inflexible", "Dauntless Shield"],
  ["Libéro", "Libero"],
  ["Ramasse Ball", "Ball Fetch"],
  ["Effilochage", "Cotton Down"],
  ["Propulseur", "Propeller Tail"],
  ["Armure Miroir", "Mirror Armor"],
  ["Dégobage", "Gulp Missile"],
  ["Nerfs d'Acier", "Stalwart"],
  ["Turbine", "Steam Engine"],
  ["Punk Rock", "Punk Rock"],
  ["Expul'Sable", "Sand Spit"],
  ["Écailles Glacées", "Ice Scales"],
  ["Mûrissement", "Ripen"],
  ["Tête de Gel", "Ice Face"],
  ["Cercle d'Énergie", "Power Spot"],
  ["Mimétisme", "Mimicry"],
  ["Brise-Barrière", "Screen Cleaner"],
  ["Boost Acier", "Steely Spirit"],
  ["Corps Condamné", "Perish Body"],
  ["Âme Vagabonde", "Wandering Spirit"],
  ["Entêtement", "Gorilla Tactics"],
  ["Gaz Inhibiteur", "Neutralizing Gas"],
  ["Voile Pastel", "Pastel Veil"],
  ["Déclic Fringale", "Hunger Switch"],
  ["Tir Vif", "Quick Draw"],
  ["Poing Invisible", "Unseen Fist"],
  ["Transistor", "Transistor"],
  ["Dent de Dragon", "Dragon's Maw"],
  ["Breuvage Suspect", "Curious Medicine"],
  ["Blanche Ruade", "Chilling Neigh"],
  ["Sombre Ruade", "Grim Neigh"],
  ["Osmose Équine", "As One"],
  ["Courroupace", "Anger Shell"],
  ["Porte-Roche", "Rocky Payload"],
  ["Corps en Or", "Good as Gold"],
  ["Force Mémorielle", "Embody Aspect"],
  ["Aux Petits Soins", "Hospitality"],
  ["Aéroporté", "Wind Rider"],
  ["Nectar Mielleux", "Supersweet Syrup"],
  ["Collab", "Costar"],
  ["Sel Purificateur", "Purifying Salt"],
  ["Incisif", "Sharpness"],
  ["Force Fongique", "Mycelium Might"],
  ["Charge Quantique", "Quark Drive"],
  ["Paléosynthèse", "Protosynthesis"],
  ["Semencier", "Seed Sower"],
  ["Bien Cuit", "Well-Baked Body"],
  ["Commandant", "Commander"],
  ["Œil Révélateur", "Mind's Eye"],
  ["Téraformation 0", "Teraform Zero"],
  ["Général Suprême", "Supreme Overlord"],
  ["Armure Caudale", "Armor Tail"],
  ["Téra-Carapace", "Tera Shell"],
  ["Téramorphose", "Tera Shift"],
  ["Grecharge", "Electromorphosis"],
  ["Emprise Toxique", "Poison Puppeteer"],
  ["Dépôt Toxique", "Toxic Debris"],
  ["Chaîne Toxique", "Toxic Chain"],
  ["Absorbe-Terre", "Earth Eater"],
  ["Odeur Tenace", "Lingering Aroma"],
  ["Thermodynamique", "Thermal Exchange"],
  ["Moteur à Hadrons", "Hadron Engine"],
  ["Chien de Garde", "Guard Dog"],
  ["Ruminant", "Cud Chew"],
  ["Pouls Orichalque", "Orichalcum Pulse"],
  ["Opportuniste", "Opportunist"],
  ["Turbine Éolienne", "Wind Power"],
  ["Supermutation", "Zero to Hero"],
  ["Urne du Fléau", "Vessel of Ruin"],
  ["Bois du Fléau", "Tablets of Ruin"],
  ["Perles du Fléau", "Beads of Ruin"],
  ["Épée du Fléau", "Sword of Ruin"]
]);

export const deToEn = new Map([
  ["Duftnote", "Stench"],
  ["Niesel", "Drizzle"],
  ["Temposchub", "Speed Boost"],
  ["Kampfpanzer", "Battle Armor"],
  ["Robustheit", "Sturdy"],
  ["Feuchtigkeit", "Damp"],
  ["Flexibilität", "Limber"],
  ["Sandschleier", "Sand Veil"],
  ["Statik", "Static"],
  ["Voltabsorber", "Volt Absorb"],
  ["H2O-Absorber", "Water Absorb"],
  ["Dösigkeit", "Oblivious"],
  ["Wolke Sieben", "Cloud Nine"],
  ["Facettenauge", "Compound Eyes"],
  ["Insomnia", "Insomnia"],
  ["Farbwechsel", "Color Change"],
  ["Immunität", "Immunity"],
  ["Feuerfänger", "Flash Fire"],
  ["Puderabwehr", "Shield Dust"],
  ["Tempomacher", "Own Tempo"],
  ["Saugnapf", "Suction Cups"],
  ["Bedroher", "Intimidate"],
  ["Wegsperre", "Shadow Tag"],
  ["Rauhaut", "Rough Skin"],
  ["Wunderwache", "Wonder Guard"],
  ["Schwebe", "Levitate"],
  ["Sporenwirt", "Effect Spore"],
  ["Synchro", "Synchronize"],
  ["Neutraltorso", "Clear Body"],
  ["Innere Kraft", "Natural Cure"],
  ["Blitzfänger", "Lightning Rod"],
  ["Edelmut", "Serene Grace"],
  ["Wassertempo", "Swift Swim"],
  ["Chlorophyll", "Chlorophyll"],
  ["Erleuchtung", "Illuminate"],
  ["Fährte", "Trace"],
  ["Kraftkoloss", "Huge Power"],
  ["Giftdorn", "Poison Point"],
  ["Konzentrator", "Inner Focus"],
  ["Magmapanzer", "Magma Armor"],
  ["Aquahülle", "Water Veil"],
  ["Magnetfalle", "Magnet Pull"],
  ["Lärmschutz", "Soundproof"],
  ["Regengenuss", "Rain Dish"],
  ["Sandsturm", "Sand Stream"],
  ["Erzwinger", "Pressure"],
  ["Speckschicht", "Thick Fat"],
  ["Frühwecker", "Early Bird"],
  ["Flammkörper", "Flame Body"],
  ["Angsthase", "Run Away"],
  ["Adlerauge", "Keen Eye"],
  ["Scherenmacht", "Hyper Cutter"],
  ["Mitnahme", "Pickup"],
  ["Schnarchnase", "Truant"],
  ["Übereifer", "Hustle"],
  ["Charmebolzen", "Cute Charm"],
  ["Plus", "Plus"],
  ["Minus", "Minus"],
  ["Prognose", "Forecast"],
  ["Wertehalter", "Sticky Hold"],
  ["Expidermis", "Shed Skin"],
  ["Adrenalin", "Guts"],
  ["Notschutz", "Marvel Scale"],
  ["Kloakensoße", "Liquid Ooze"],
  ["Notdünger", "Overgrow"],
  ["Großbrand", "Blaze"],
  ["Sturzbach", "Torrent"],
  ["Hexaplaga", "Swarm"],
  ["Steinhaupt", "Rock Head"],
  ["Dürre", "Drought"],
  ["Ausweglos", "Arena Trap"],
  ["Munterkeit", "Vital Spirit"],
  ["Pulverrauch", "White Smoke"],
  ["Mentalkraft", "Pure Power"],
  ["Panzerhaut", "Shell Armor"],
  ["Klimaschutz", "Air Lock"],
  ["Fußangel", "Tangled Feet"],
  ["Starthilfe", "Motor Drive"],
  ["Rivalität", "Rivalry"],
  ["Felsenfest", "Steadfast"],
  ["Schneemantel", "Snow Cloak"],
  ["Völlerei", "Gluttony"],
  ["Kurzschluss", "Anger Point"],
  ["Entlastung", "Unburden"],
  ["Hitzeschutz", "Heatproof"],
  ["Wankelmut", "Simple"],
  ["Trockenheit", "Dry Skin"],
  ["Download", "Download"],
  ["Eisenfaust", "Iron Fist"],
  ["Aufheber", "Poison Heal"],
  ["Anpassung", "Adaptability"],
  ["Wertelink", "Skill Link"],
  ["Hydration", "Hydration"],
  ["Solarkraft", "Solar Power"],
  ["Rasanz", "Quick Feet"],
  ["Regulierung", "Normalize"],
  ["Superschütze", "Sniper"],
  ["Magieschild", "Magic Guard"],
  ["Schildlos", "No Guard"],
  ["Zeitspiel", "Stall"],
  ["Techniker", "Technician"],
  ["Floraschild", "Leaf Guard"],
  ["Tollpatsch", "Klutz"],
  ["Überbrückung", "Mold Breaker"],
  ["Glückspilz", "Super Luck"],
  ["Finalschlag", "Aftermath"],
  ["Vorahnung", "Anticipation"],
  ["Vorwarnung", "Forewarn"],
  ["Unkenntnis", "Unaware"],
  ["Aufwertung", "Tinted Lens"],
  ["Filter", "Filter"],
  ["Saumselig", "Slow Start"],
  ["Rauflust", "Scrappy"],
  ["Sturmsog", "Storm Drain"],
  ["Eishaut", "Ice Body"],
  ["Felskern", "Solid Rock"],
  ["Hagelalarm", "Snow Warning"],
  ["Honigmaul", "Honey Gather"],
  ["Schnüffler", "Frisk"],
  ["Achtlos", "Reckless"],
  ["Variabilität", "Multitype"],
  ["Pflanzengabe", "Flower Gift"],
  ["Alptraum", "Bad Dreams"],
  ["Langfinger", "Pickpocket"],
  ["Rohe Gewalt", "Sheer Force"],
  ["Umkehrung", "Contrary"],
  ["Anspannung", "Unnerve"],
  ["Siegeswille", "Defiant"],
  ["Schwächling", "Defeatist"],
  ["Tastfluch", "Cursed Body"],
  ["Heilherz", "Healer"],
  ["Freundeshut", "Friend Guard"],
  ["Bruchrüstung", "Weak Armor"],
  ["Schwermetall", "Heavy Metal"],
  ["Leichtmetall", "Light Metal"],
  ["Multischuppe", "Multiscale"],
  ["Giftwahn", "Toxic Boost"],
  ["Hitzewahn", "Flare Boost"],
  ["Reiche Ernte", "Harvest"],
  ["Telepathie", "Telepathy"],
  ["Gefühlswippe", "Moody"],
  ["Wetterfest", "Overcoat"],
  ["Giftgriff", "Poison Touch"],
  ["Belebekraft", "Regenerator"],
  ["Brustbieter", "Big Pecks"],
  ["Sandscharrer", "Sand Rush"],
  ["Wunderhaut", "Wonder Skin"],
  ["Analyse", "Analytic"],
  ["Trugbild", "Illusion"],
  ["Doppelgänger", "Imposter"],
  ["Schwebedurch", "Infiltrator"],
  ["Mumie", "Mummy"],
  ["Hochmut", "Moxie"],
  ["Redlichkeit", "Justified"],
  ["Hasenfuß", "Rattled"],
  ["Magiespiegel", "Magic Bounce"],
  ["Vegetarier", "Sap Sipper"],
  ["Strolch", "Prankster"],
  ["Sandgewalt", "Sand Force"],
  ["Eisenstachel", "Iron Barbs"],
  ["Trance-Modus", "Zen Mode"],
  ["Triumphstern", "Victory Star"],
  ["Turbobrand", "Turboblaze"],
  ["Teravolt", "Teravolt"],
  ["Dufthülle", "Aroma Veil"],
  ["Blütenhülle", "Flower Veil"],
  ["Backentaschen", "Cheek Pouch"],
  ["Wandlungskunst", "Protean"],
  ["Fellkleid", "Fur Coat"],
  ["Zauberer", "Magician"],
  ["Kugelsicher", "Bulletproof"],
  ["Unbeugsamkeit", "Competitive"],
  ["Titankiefer", "Strong Jaw"],
  ["Frostschicht", "Refrigerate"],
  ["Zuckerhülle", "Sweet Veil"],
  ["Taktikwechsel", "Stance Change"],
  ["Orkanschwingen", "Gale Wings"],
  ["Megawumme", "Mega Launcher"],
  ["Pflanzenpelz", "Grass Pelt"],
  ["Nutznießer", "Symbiosis"],
  ["Krallenwucht", "Tough Claws"],
  ["Feenschicht", "Pixilate"],
  ["Viskosität", "Gooey"],
  ["Zenithaut", "Aerilate"],
  ["Familienbande", "Parental Bond"],
  ["Dunkelaura", "Dark Aura"],
  ["Feenaura", "Fairy Aura"],
  ["Aura-Umkehr", "Aura Break"],
  ["Urmeer", "Primordial Sea"],
  ["Endland", "Desolate Land"],
  ["Delta-Wind", "Delta Stream"],
  ["Zähigkeit", "Stamina"],
  ["Reißaus", "Wimp Out"],
  ["Rückzug", "Emergency Exit"],
  ["Verklumpen", "Water Compaction"],
  ["Quälerei", "Merciless"],
  ["Limitschild", "Shields Down"],
  ["Beschattung", "Stakeout"],
  ["Wasserblase", "Water Bubble"],
  ["Stahlprofi", "Steelworker"],
  ["Wutausbruch", "Berserk"],
  ["Schneescharrer", "Slush Rush"],
  ["Langstrecke", "Long Reach"],
  ["Plätscherstimme", "Liquid Voice"],
  ["Heilwandel", "Triage"],
  ["Elektrohaut", "Galvanize"],
  ["Surf-Schweif", "Surge Surfer"],
  ["Fischschwarm", "Schooling"],
  ["Kostümspuk", "Disguise"],
  ["Freundschaftsakt", "Battle Bond"],
  ["Scharwandel", "Power Construct"],
  ["Korrosion", "Corrosion"],
  ["Dauerschlaf", "Comatose"],
  ["Majestät", "Queenly Majesty"],
  ["Magenkrempler", "Innards Out"],
  ["Tänzer", "Dancer"],
  ["Batterie", "Battery"],
  ["Flauschigkeit", "Fluffy"],
  ["Buntkörper", "Dazzling"],
  ["Seelenherz", "Soul-Heart"],
  ["Lockenkopf", "Tangling Hair"],
  ["Receiver", "Receiver"],
  ["Chemiekraft", "Power of Alchemy"],
  ["Bestien-Boost", "Beast Boost"],
  ["Alpha-System", "RKS System"],
  ["Elektro-Erzeuger", "Electric Surge"],
  ["Psycho-Erzeuger", "Psychic Surge"],
  ["Nebel-Erzeuger", "Misty Surge"],
  ["Gras-Erzeuger", "Grassy Surge"],
  ["Metallprotektor", "Full Metal Body"],
  ["Phantomschutz", "Shadow Shield"],
  ["Prismarüstung", "Prism Armor"],
  ["Zerebralmacht", "Neuroforce"],
  ["Kühnes Schwert", "Intrepid Sword"],
  ["Wackerer Schild", "Dauntless Shield"],
  ["Libero", "Libero"],
  ["Apport", "Ball Fetch"],
  ["Wollflaum", "Cotton Down"],
  ["Schraubflosse", "Propeller Tail"],
  ["Spiegelrüstung", "Mirror Armor"],
  ["Würggeschoss", "Gulp Missile"],
  ["Stahlrückgrat", "Stalwart"],
  ["Dampfantrieb", "Steam Engine"],
  ["Punk Rock", "Punk Rock"],
  ["Sandspeier", "Sand Spit"],
  ["Eisflügelstaub", "Ice Scales"],
  ["Heranreifen", "Ripen"],
  ["Tiefkühlkopf", "Ice Face"],
  ["Kraftquelle", "Power Spot"],
  ["Mimese", "Mimicry"],
  ["Hemmungslos", "Screen Cleaner"],
  ["Stählerner Wille", "Steely Spirit"],
  ["Unheilskörper", "Perish Body"],
  ["Rastlose Seele", "Wandering Spirit"],
  ["Affenfokus", "Gorilla Tactics"],
  ["Reaktionsgas", "Neutralizing Gas"],
  ["Pastellhülle", "Pastel Veil"],
  ["Heißhunger", "Hunger Switch"],
  ["Schnellschuss", "Quick Draw"],
  ["Verborgene Faust", "Unseen Fist"],
  ["Transistor", "Transistor"],
  ["Drachenkiefer", "Dragon's Maw"],
  ["Kuriose Arznei", "Curious Medicine"],
  ["Helles Wiehern", "Chilling Neigh"],
  ["Dunkles Wiehern", "Grim Neigh"],
  ["Reitgespann", "As One"],
  ["Wutpanzer", "Anger Shell"],
  ["Steinträger", "Rocky Payload"],
  ["Goldkörper", "Good as Gold"],
  ["Erinnerungskraft", "Embody Aspect"],
  ["Gastlichkeit", "Hospitality"],
  ["Windreiter", "Wind Rider"],
  ["Süßer Nektar", "Supersweet Syrup"],
  ["Synchronauftritt", "Costar"],
  ["Läutersalz", "Purifying Salt"],
  ["Scharfkantig", "Sharpness"],
  ["Myzelienkraft", "Mycelium Might"],
  ["Quantenantrieb", "Quark Drive"],
  ["Paläosynthese", "Protosynthesis"],
  ["Streusaat", "Seed Sower"],
  ["Knusperkruste", "Well-Baked Body"],
  ["Kommandant", "Commander"],
  ["Geistiges Auge", "Mind's Eye"],
  ["Teraforming Null", "Teraform Zero"],
  ["Feldherr", "Supreme Overlord"],
  ["Schweifrüstung", "Armor Tail"],
  ["Tera-Panzer", "Tera Shell"],
  ["Tera-Wandel", "Tera Shift"],
  ["Dynamo", "Electromorphosis"],
  ["Giftpuppenspiel", "Poison Puppeteer"],
  ["Giftbelag", "Toxic Debris"],
  ["Giftkette", "Toxic Chain"],
  ["Bodenschmaus", "Earth Eater"],
  ["Duftschwade", "Lingering Aroma"],
  ["Thermowandel", "Thermal Exchange"],
  ["Hadronen-Motor", "Hadron Engine"],
  ["Wachhund", "Guard Dog"],
  ["Wiederkäuer", "Cud Chew"],
  ["Orichalkum-Puls", "Orichalcum Pulse"],
  ["Profiteur", "Opportunist"],
  ["Windkraft", "Wind Power"],
  ["Superwechsel", "Zero to Hero"],
  ["Unheilsgefäß", "Vessel of Ruin"],
  ["Unheilstafeln", "Tablets of Ruin"],
  ["Unheilsjuwelen", "Beads of Ruin"],
  ["Unheilsschwert", "Sword of Ruin"]
]);

export const itToEn = new Map([
  ["Tanfo", "Stench"],
  ["Piovischio", "Drizzle"],
  ["Acceleratore", "Speed Boost"],
  ["Lottascudo", "Battle Armor"],
  ["Vigore", "Sturdy"],
  ["Umidità", "Damp"],
  ["Scioltezza", "Limber"],
  ["Sabbiavelo", "Sand Veil"],
  ["Statico", "Static"],
  ["Assorbivolt", "Volt Absorb"],
  ["Assorbacqua", "Water Absorb"],
  ["Indifferenza", "Oblivious"],
  ["Antimeteo", "Cloud Nine"],
  ["Insettocchi", "Compound Eyes"],
  ["Insonnia", "Insomnia"],
  ["Cambiacolore", "Color Change"],
  ["Immunità", "Immunity"],
  ["Fuocardore", "Flash Fire"],
  ["Polvoscudo", "Shield Dust"],
  ["Mente Locale", "Own Tempo"],
  ["Ventose", "Suction Cups"],
  ["Prepotenza", "Intimidate"],
  ["Pedinombra", "Shadow Tag"],
  ["Cartavetro", "Rough Skin"],
  ["Magidifesa", "Wonder Guard"],
  ["Levitazione", "Levitate"],
  ["Spargispora", "Effect Spore"],
  ["Sincronismo", "Synchronize"],
  ["Corpochiaro", "Clear Body"],
  ["Alternacura", "Natural Cure"],
  ["Parafulmine", "Lightning Rod"],
  ["Leggiadro", "Serene Grace"],
  ["Nuotovelox", "Swift Swim"],
  ["Clorofilla", "Chlorophyll"],
  ["Risplendi", "Illuminate"],
  ["Traccia", "Trace"],
  ["Macroforza", "Huge Power"],
  ["Velenopunto", "Poison Point"],
  ["Forza Interiore", "Inner Focus"],
  ["Magmascudo", "Magma Armor"],
  ["Idrovelo", "Water Veil"],
  ["Magnetismo", "Magnet Pull"],
  ["Antisuono", "Soundproof"],
  ["Copripioggia", "Rain Dish"],
  ["Sabbiafiume", "Sand Stream"],
  ["Pressione", "Pressure"],
  ["Grassospesso", "Thick Fat"],
  ["Sveglialampo", "Early Bird"],
  ["Corpodifuoco", "Flame Body"],
  ["Fugafacile", "Run Away"],
  ["Sguardofermo", "Keen Eye"],
  ["Ipertaglio", "Hyper Cutter"],
  ["Raccolta", "Pickup"],
  ["Pigrone", "Truant"],
  ["Tuttafretta", "Hustle"],
  ["Incantevole", "Cute Charm"],
  ["Più", "Plus"],
  ["Meno", "Minus"],
  ["Previsioni", "Forecast"],
  ["Antifurto", "Sticky Hold"],
  ["Muta", "Shed Skin"],
  ["Dentistretti", "Guts"],
  ["Pelledura", "Marvel Scale"],
  ["Melma", "Liquid Ooze"],
  ["Erbaiuto", "Overgrow"],
  ["Aiutofuoco", "Blaze"],
  ["Acquaiuto", "Torrent"],
  ["Aiutinsetto", "Swarm"],
  ["Testadura", "Rock Head"],
  ["Siccità", "Drought"],
  ["Trappoarena", "Arena Trap"],
  ["Spiritovivo", "Vital Spirit"],
  ["Fumochiaro", "White Smoke"],
  ["Forzapura", "Pure Power"],
  ["Guscioscudo", "Shell Armor"],
  ["Riparo", "Air Lock"],
  ["Intricopiedi", "Tangled Feet"],
  ["Elettrorapid", "Motor Drive"],
  ["Antagonismo", "Rivalry"],
  ["Cuordeciso", "Steadfast"],
  ["Mantelneve", "Snow Cloak"],
  ["Voracità", "Gluttony"],
  ["Grancollera", "Anger Point"],
  ["Agiltecnica", "Unburden"],
  ["Antifuoco", "Heatproof"],
  ["Disinvoltura", "Simple"],
  ["Pellearsa", "Dry Skin"],
  ["Download", "Download"],
  ["Ferropugno", "Iron Fist"],
  ["Velencura", "Poison Heal"],
  ["Adattabilità", "Adaptability"],
  ["Abillegame", "Skill Link"],
  ["Idratazione", "Hydration"],
  ["Solarpotere", "Solar Power"],
  ["Piedisvelti", "Quick Feet"],
  ["Normalità", "Normalize"],
  ["Cecchino", "Sniper"],
  ["Magicscudo", "Magic Guard"],
  ["Nullodifesa", "No Guard"],
  ["Rallentatore", "Stall"],
  ["Tecnico", "Technician"],
  ["Fogliamanto", "Leaf Guard"],
  ["Impaccio", "Klutz"],
  ["Rompiforma", "Mold Breaker"],
  ["Supersorte", "Super Luck"],
  ["Scoppio", "Aftermath"],
  ["Presagio", "Anticipation"],
  ["Premonizione", "Forewarn"],
  ["Imprudenza", "Unaware"],
  ["Lentifumé", "Tinted Lens"],
  ["Filtro", "Filter"],
  ["Lentoinizio", "Slow Start"],
  ["Nervisaldi", "Scrappy"],
  ["Acquascolo", "Storm Drain"],
  ["Corpogelo", "Ice Body"],
  ["Solidroccia", "Solid Rock"],
  ["Scendineve", "Snow Warning"],
  ["Mielincetta", "Honey Gather"],
  ["Indagine", "Frisk"],
  ["Temerarietà", "Reckless"],
  ["Multitipo", "Multitype"],
  ["Regalfiore", "Flower Gift"],
  ["Sogniamari", "Bad Dreams"],
  ["Arraffalesto", "Pickpocket"],
  ["Forzabruta", "Sheer Force"],
  ["Inversione", "Contrary"],
  ["Agitazione", "Unnerve"],
  ["Agonismo", "Defiant"],
  ["Sconforto", "Defeatist"],
  ["Corpofunesto", "Cursed Body"],
  ["Curacuore", "Healer"],
  ["Amicoscudo", "Friend Guard"],
  ["Sottilguscio", "Weak Armor"],
  ["Metalpesante", "Heavy Metal"],
  ["Metalleggero", "Light Metal"],
  ["Multisquame", "Multiscale"],
  ["Velenimpeto", "Toxic Boost"],
  ["Bruciaimpeto", "Flare Boost"],
  ["Coglibacche", "Harvest"],
  ["Telepatia", "Telepathy"],
  ["Altalena", "Moody"],
  ["Copricapo", "Overcoat"],
  ["Velentocco", "Poison Touch"],
  ["Rigenergia", "Regenerator"],
  ["Pettinfuori", "Big Pecks"],
  ["Remasabbia", "Sand Rush"],
  ["Splendicute", "Wonder Skin"],
  ["Ponderazione", "Analytic"],
  ["Illusione", "Illusion"],
  ["Sosia", "Imposter"],
  ["Intrapasso", "Infiltrator"],
  ["Mummia", "Mummy"],
  ["Arroganza", "Moxie"],
  ["Giustizia", "Justified"],
  ["Paura", "Rattled"],
  ["Magispecchio", "Magic Bounce"],
  ["Mangiaerba", "Sap Sipper"],
  ["Burla", "Prankster"],
  ["Silicoforza", "Sand Force"],
  ["Spineferrate", "Iron Barbs"],
  ["Stato Zen", "Zen Mode"],
  ["Vittorstella", "Victory Star"],
  ["Piroturbina", "Turboblaze"],
  ["Teravolt", "Teravolt"],
  ["Aromavelo", "Aroma Veil"],
  ["Fiorvelo", "Flower Veil"],
  ["Guancegonfie", "Cheek Pouch"],
  ["Mutatipo", "Protean"],
  ["Foltopelo", "Fur Coat"],
  ["Prestigiatore", "Magician"],
  ["Antiproiettile", "Bulletproof"],
  ["Tenacia", "Competitive"],
  ["Ferromascella", "Strong Jaw"],
  ["Pellegelo", "Refrigerate"],
  ["Dolcevelo", "Sweet Veil"],
  ["Accendilotta", "Stance Change"],
  ["Aliraffica", "Gale Wings"],
  ["Megalancio", "Mega Launcher"],
  ["Peloderba", "Grass Pelt"],
  ["Simbiosi", "Symbiosis"],
  ["Unghiedure", "Tough Claws"],
  ["Pellefolletto", "Pixilate"],
  ["Viscosità", "Gooey"],
  ["Pellecielo", "Aerilate"],
  ["Amorefiliale", "Parental Bond"],
  ["Auratetra", "Dark Aura"],
  ["Aurafolletto", "Fairy Aura"],
  ["Frangiaura", "Aura Break"],
  ["Mare Primordiale", "Primordial Sea"],
  ["Terra Estrema", "Desolate Land"],
  ["Flusso Delta", "Delta Stream"],
  ["Sopportazione", "Stamina"],
  ["Fuggifuggi", "Wimp Out"],
  ["Passoindietro", "Emergency Exit"],
  ["Idrorinforzo", "Water Compaction"],
  ["Spietatezza", "Merciless"],
  ["Scudosoglia", "Shields Down"],
  ["Sorveglianza", "Stakeout"],
  ["Bolladacqua", "Water Bubble"],
  ["Tempracciaio", "Steelworker"],
  ["Furore", "Berserk"],
  ["Spalaneve", "Slush Rush"],
  ["Distacco", "Long Reach"],
  ["Idrovoce", "Liquid Voice"],
  ["Primacura", "Triage"],
  ["Pellelettro", "Galvanize"],
  ["Codasurf", "Surge Surfer"],
  ["Banco", "Schooling"],
  ["Fantasmanto", "Disguise"],
  ["Morfosintonia", "Battle Bond"],
  ["Sciamefusione", "Power Construct"],
  ["Corrosione", "Corrosion"],
  ["Sonno Assoluto", "Comatose"],
  ["Regalità", "Queenly Majesty"],
  ["Espellinterno", "Innards Out"],
  ["Sincrodanza", "Dancer"],
  ["Batteria", "Battery"],
  ["Morbidone", "Fluffy"],
  ["Corposgargiante", "Dazzling"],
  ["Cuoreanima", "Soul-Heart"],
  ["Boccolidoro", "Tangling Hair"],
  ["Ricezione", "Receiver"],
  ["Forza Chimica", "Power of Alchemy"],
  ["Ultraboost", "Beast Boost"],
  ["Sistema Primevo", "RKS System"],
  ["Elettrogenesi", "Electric Surge"],
  ["Psicogenesi", "Psychic Surge"],
  ["Nebbiogenesi", "Misty Surge"],
  ["Erbogenesi", "Grassy Surge"],
  ["Metalprotezione", "Full Metal Body"],
  ["Spettroguardia", "Shadow Shield"],
  ["Scudoprisma", "Prism Armor"],
  ["Cerebroforza", "Neuroforce"],
  ["Spada Indomita", "Intrepid Sword"],
  ["Scudo Saldo", "Dauntless Shield"],
  ["Libero", "Libero"],
  ["Raccattapalle", "Ball Fetch"],
  ["Lanugine", "Cotton Down"],
  ["Elicopinna", "Propeller Tail"],
  ["Blindospecchio", "Mirror Armor"],
  ["Inghiottimissile", "Gulp Missile"],
  ["Volontà di Ferro", "Stalwart"],
  ["Vapormacchina", "Steam Engine"],
  ["Punk Rock", "Punk Rock"],
  ["Sputasabbia", "Sand Spit"],
  ["Geloscaglie", "Ice Scales"],
  ["Maturazione", "Ripen"],
  ["Gelofaccia", "Ice Face"],
  ["Fonte Energetica", "Power Spot"],
  ["Mimetismo", "Mimicry"],
  ["Annullabarriere", "Screen Cleaner"],
  ["Spiritoferreo", "Steely Spirit"],
  ["Ultimotocco", "Perish Body"],
  ["Anima Errante", "Wandering Spirit"],
  ["Vigorilla", "Gorilla Tactics"],
  ["Gas Reagente", "Neutralizing Gas"],
  ["Pastelvelo", "Pastel Veil"],
  ["Pancialterna", "Hunger Switch"],
  ["Colpolesto", "Quick Draw"],
  ["Pugni Invisibili", "Unseen Fist"],
  ["Transistor", "Transistor"],
  ["Dragomascelle", "Dragon's Maw"],
  ["Stranofarmaco", "Curious Medicine"],
  ["Nitrito Bianco", "Chilling Neigh"],
  ["Nitrito Nero", "Grim Neigh"],
  ["Sintonia Equina", "As One"],
  ["Iraguscio", "Anger Shell"],
  ["Portamassi", "Rocky Payload"],
  ["Corpo Aureo", "Good as Gold"],
  ["Albergamemorie", "Embody Aspect"],
  ["Ospitalità", "Hospitality"],
  ["Vento Propizio", "Wind Rider"],
  ["Sciroppo Sublime", "Supersweet Syrup"],
  ["Coprotagonismo", "Costar"],
  ["Sale Purificante", "Purifying Salt"],
  ["Affilama", "Sharpness"],
  ["Micoforza", "Mycelium Might"],
  ["Carica Quark", "Quark Drive"],
  ["Paleoattivazione", "Protosynthesis"],
  ["Spargisemi", "Seed Sower"],
  ["Bentostato", "Well-Baked Body"],
  ["Torre di Comando", "Commander"],
  ["Occhio Interiore", "Mind's Eye"],
  ["Zeroformazione", "Teraform Zero"],
  ["Generale Supremo", "Supreme Overlord"],
  ["Codarmatura", "Armor Tail"],
  ["Teraguscio", "Tera Shell"],
  ["Teramorfosi", "Tera Shift"],
  ["Convertivolt", "Electromorphosis"],
  ["Malia Tossica", "Poison Puppeteer"],
  ["Mantossina", "Toxic Debris"],
  ["Catena Tossica", "Toxic Chain"],
  ["Mangiaterra", "Earth Eater"],
  ["Odore Tenace", "Lingering Aroma"],
  ["Termoscambio", "Thermal Exchange"],
  ["Motore Adronico", "Hadron Engine"],
  ["Cane da Guardia", "Guard Dog"],
  ["Ruminante", "Cud Chew"],
  ["Ritmo d'Oricalco", "Orichalcum Pulse"],
  ["Scrocco", "Opportunist"],
  ["Energia Eolica", "Wind Power"],
  ["Supercambio", "Zero to Hero"],
  ["Vaso Nefasto", "Vessel of Ruin"],
  ["Amuleto Nefasto", "Tablets of Ruin"],
  ["Monile Nefasto", "Beads of Ruin"],
  ["Spada Nefasta", "Sword of Ruin"]
]);

export const esToEn = new Map([
  ["Hedor", "Stench"],
  ["Llovizna", "Drizzle"],
  ["Impulso", "Speed Boost"],
  ["Armadura Batalla", "Battle Armor"],
  ["Robustez", "Sturdy"],
  ["Humedad", "Damp"],
  ["Flexibilidad", "Limber"],
  ["Velo Arena", "Sand Veil"],
  ["Elec. Estática", "Static"],
  ["Absorbe Elec", "Volt Absorb"],
  ["Absorbe Agua", "Water Absorb"],
  ["Despiste", "Oblivious"],
  ["Aclimatación", "Cloud Nine"],
  ["Ojo Compuesto", "Compound Eyes"],
  ["Insomnio", "Insomnia"],
  ["Cambio Color", "Color Change"],
  ["Inmunidad", "Immunity"],
  ["Absorbe Fuego", "Flash Fire"],
  ["Polvo Escudo", "Shield Dust"],
  ["Ritmo Propio", "Own Tempo"],
  ["Ventosas", "Suction Cups"],
  ["Intimidación", "Intimidate"],
  ["Sombra Trampa", "Shadow Tag"],
  ["Piel Tosca", "Rough Skin"],
  ["Superguarda", "Wonder Guard"],
  ["Levitación", "Levitate"],
  ["Efecto Espora", "Effect Spore"],
  ["Sincronía", "Synchronize"],
  ["Cuerpo Puro", "Clear Body"],
  ["Cura Natural", "Natural Cure"],
  ["Pararrayos", "Lightning Rod"],
  ["Dicha", "Serene Grace"],
  ["Nado Rápido", "Swift Swim"],
  ["Clorofila", "Chlorophyll"],
  ["Iluminación", "Illuminate"],
  ["Rastro", "Trace"],
  ["Potencia", "Huge Power"],
  ["Punto Tóxico", "Poison Point"],
  ["Foco Interno", "Inner Focus"],
  ["Escudo Magma", "Magma Armor"],
  ["Velo Agua", "Water Veil"],
  ["Imán", "Magnet Pull"],
  ["Insonorizar", "Soundproof"],
  ["Cura Lluvia", "Rain Dish"],
  ["Chorro Arena", "Sand Stream"],
  ["Presión", "Pressure"],
  ["Sebo", "Thick Fat"],
  ["Madrugar", "Early Bird"],
  ["Cuerpo Llama", "Flame Body"],
  ["Fuga", "Run Away"],
  ["Vista Lince", "Keen Eye"],
  ["Corte Fuerte", "Hyper Cutter"],
  ["Recogida", "Pickup"],
  ["Ausente", "Truant"],
  ["Entusiasmo", "Hustle"],
  ["Gran Encanto", "Cute Charm"],
  ["Más", "Plus"],
  ["Menos", "Minus"],
  ["Predicción", "Forecast"],
  ["Viscosidad", "Sticky Hold"],
  ["Mudar", "Shed Skin"],
  ["Agallas", "Guts"],
  ["Escama Especial", "Marvel Scale"],
  ["Lodo Líquido", "Liquid Ooze"],
  ["Espesura", "Overgrow"],
  ["Mar Llamas", "Blaze"],
  ["Torrente", "Torrent"],
  ["Enjambre", "Swarm"],
  ["Cabeza Roca", "Rock Head"],
  ["Sequía", "Drought"],
  ["Trampa Arena", "Arena Trap"],
  ["Espíritu Vital", "Vital Spirit"],
  ["Humo Blanco", "White Smoke"],
  ["Energía Pura", "Pure Power"],
  ["Caparazón", "Shell Armor"],
  ["Bucle Aire", "Air Lock"],
  ["Tumbos", "Tangled Feet"],
  ["Electromotor", "Motor Drive"],
  ["Rivalidad", "Rivalry"],
  ["Impasible", "Steadfast"],
  ["Manto Níveo", "Snow Cloak"],
  ["Gula", "Gluttony"],
  ["Irascible", "Anger Point"],
  ["Liviano", "Unburden"],
  ["Ignífugo", "Heatproof"],
  ["Simple", "Simple"],
  ["Piel Seca", "Dry Skin"],
  ["Descarga", "Download"],
  ["Puño Férreo", "Iron Fist"],
  ["Antídoto", "Poison Heal"],
  ["Adaptable", "Adaptability"],
  ["Encadenado", "Skill Link"],
  ["Hidratación", "Hydration"],
  ["Poder Solar", "Solar Power"],
  ["Pies Rápidos", "Quick Feet"],
  ["Normalidad", "Normalize"],
  ["Francotirador", "Sniper"],
  ["Muro Mágico", "Magic Guard"],
  ["Indefenso", "No Guard"],
  ["Rezagado", "Stall"],
  ["Experto", "Technician"],
  ["Defensa Hoja", "Leaf Guard"],
  ["Zoquete", "Klutz"],
  ["Rompemoldes", "Mold Breaker"],
  ["Afortunado", "Super Luck"],
  ["Resquicio", "Aftermath"],
  ["Anticipación", "Anticipation"],
  ["Alerta", "Forewarn"],
  ["Ignorante", "Unaware"],
  ["Cromolente", "Tinted Lens"],
  ["Filtro", "Filter"],
  ["Inicio Lento", "Slow Start"],
  ["Intrépido", "Scrappy"],
  ["Colector", "Storm Drain"],
  ["Gélido", "Ice Body"],
  ["Roca Sólida", "Solid Rock"],
  ["Nevada", "Snow Warning"],
  ["Recogemiel", "Honey Gather"],
  ["Cacheo", "Frisk"],
  ["Audaz", "Reckless"],
  ["Multitipo", "Multitype"],
  ["Don Floral", "Flower Gift"],
  ["Mal Sueño", "Bad Dreams"],
  ["Hurto", "Pickpocket"],
  ["Potencia Bruta", "Sheer Force"],
  ["Respondón", "Contrary"],
  ["Nerviosismo", "Unnerve"],
  ["Competitivo", "Defiant"],
  ["Flaqueza", "Defeatist"],
  ["Cuerpo Maldito", "Cursed Body"],
  ["Alma Cura", "Healer"],
  ["Compiescolta", "Friend Guard"],
  ["Armadura Frágil", "Weak Armor"],
  ["Metal Pesado", "Heavy Metal"],
  ["Metal Liviano", "Light Metal"],
  ["Compensación", "Multiscale"],
  ["Ímpetu Tóxico", "Toxic Boost"],
  ["Ímpetu Ardiente", "Flare Boost"],
  ["Cosecha", "Harvest"],
  ["Telepatía", "Telepathy"],
  ["Veleta", "Moody"],
  ["Funda", "Overcoat"],
  ["Toque Tóxico", "Poison Touch"],
  ["Regeneración", "Regenerator"],
  ["Sacapecho", "Big Pecks"],
  ["Ímpetu Arena", "Sand Rush"],
  ["Piel Milagro", "Wonder Skin"],
  ["Cálculo Final", "Analytic"],
  ["Ilusión", "Illusion"],
  ["Impostor", "Imposter"],
  ["Allanamiento", "Infiltrator"],
  ["Momia", "Mummy"],
  ["Autoestima", "Moxie"],
  ["Justiciero", "Justified"],
  ["Cobardía", "Rattled"],
  ["Espejo Mágico", "Magic Bounce"],
  ["Herbívoro", "Sap Sipper"],
  ["Bromista", "Prankster"],
  ["Poder Arena", "Sand Force"],
  ["Punta Acero", "Iron Barbs"],
  ["Modo Daruma", "Zen Mode"],
  ["Tinovictoria", "Victory Star"],
  ["Turbollama", "Turboblaze"],
  ["Terravoltaje", "Teravolt"],
  ["Velo Aroma", "Aroma Veil"],
  ["Velo Flor", "Flower Veil"],
  ["Carrillo", "Cheek Pouch"],
  ["Mutatipo", "Protean"],
  ["Pelaje Recio", "Fur Coat"],
  ["Prestidigitador", "Magician"],
  ["Antibalas", "Bulletproof"],
  ["Tenacidad", "Competitive"],
  ["Mandíbula Fuerte", "Strong Jaw"],
  ["Piel Helada", "Refrigerate"],
  ["Velo Dulce", "Sweet Veil"],
  ["Cambio Táctico", "Stance Change"],
  ["Alas Vendaval", "Gale Wings"],
  ["Megadisparador", "Mega Launcher"],
  ["Manto Frondoso", "Grass Pelt"],
  ["Simbiosis", "Symbiosis"],
  ["Garra Dura", "Tough Claws"],
  ["Piel Feérica", "Pixilate"],
  ["Baba", "Gooey"],
  ["Piel Celeste", "Aerilate"],
  ["Amor Filial", "Parental Bond"],
  ["Aura Oscura", "Dark Aura"],
  ["Aura Feérica", "Fairy Aura"],
  ["Rompeaura", "Aura Break"],
  ["Mar del Albor", "Primordial Sea"],
  ["Tierra del Ocaso", "Desolate Land"],
  ["Ráfaga Delta", "Delta Stream"],
  ["Firmeza", "Stamina"],
  ["Huida", "Wimp Out"],
  ["Retirada", "Emergency Exit"],
  ["Hidrorrefuerzo", "Water Compaction"],
  ["Ensañamiento", "Merciless"],
  ["Escudo Limitado", "Shields Down"],
  ["Vigilante", "Stakeout"],
  ["Pompa", "Water Bubble"],
  ["Acero Templado", "Steelworker"],
  ["Cólera", "Berserk"],
  ["Quitanieves", "Slush Rush"],
  ["Remoto", "Long Reach"],
  ["Voz Fluida", "Liquid Voice"],
  ["Primer Auxilio", "Triage"],
  ["Piel Eléctrica", "Galvanize"],
  ["Cola Surf", "Surge Surfer"],
  ["Banco", "Schooling"],
  ["Disfraz", "Disguise"],
  ["Fuerte Afecto", "Battle Bond"],
  ["Agrupamiento", "Power Construct"],
  ["Corrosión", "Corrosion"],
  ["Letargo Perenne", "Comatose"],
  ["Regia Presencia", "Queenly Majesty"],
  ["Revés", "Innards Out"],
  ["Pareja de Baile", "Dancer"],
  ["Batería", "Battery"],
  ["Peluche", "Fluffy"],
  ["Cuerpo Vívido", "Dazzling"],
  ["Coránima", "Soul-Heart"],
  ["Rizos Rebeldes", "Tangling Hair"],
  ["Receptor", "Receiver"],
  ["Reacción Química", "Power of Alchemy"],
  ["Ultraimpulso", "Beast Boost"],
  ["Sistema Alfa", "RKS System"],
  ["Electrogénesis", "Electric Surge"],
  ["Psicogénesis", "Psychic Surge"],
  ["Nebulogénesis", "Misty Surge"],
  ["Herbogénesis", "Grassy Surge"],
  ["Guardia Metálica", "Full Metal Body"],
  ["Guardia Espectro", "Shadow Shield"],
  ["Armadura Prisma", "Prism Armor"],
  ["Fuerza Cerebral", "Neuroforce"],
  ["Espada Indómita", "Intrepid Sword"],
  ["Escudo Recio", "Dauntless Shield"],
  ["Líbero", "Libero"],
  ["Recogebolas", "Ball Fetch"],
  ["Pelusa", "Cotton Down"],
  ["Hélice Caudal", "Propeller Tail"],
  ["Coraza Reflejo", "Mirror Armor"],
  ["Tragamisil", "Gulp Missile"],
  ["Acérrimol", "Stalwart"],
  ["Combustible", "Steam Engine"],
  ["Punk Rock", "Punk Rock"],
  ["Expulsarena", "Sand Spit"],
  ["Escama de Hielo", "Ice Scales"],
  ["Maduración", "Ripen"],
  ["Cara de hielo", "Ice Face"],
  ["Fuente Energía", "Power Spot"],
  ["Mimetismo", "Mimicry"],
  ["Antibarrera", "Screen Cleaner"],
  ["Alma Acerada", "Steely Spirit"],
  ["Cuerpo Mortal", "Perish Body"],
  ["Alma Errante", "Wandering Spirit"],
  ["Monotema", "Gorilla Tactics"],
  ["Gas Reactivo", "Neutralizing Gas"],
  ["Velo Pastel", "Pastel Veil"],
  ["Mutapetito", "Hunger Switch"],
  ["Mano Rápida", "Quick Draw"],
  ["Puño Invisible", "Unseen Fist"],
  ["Transistor", "Transistor"],
  ["Mandíbula Dragón", "Dragon's Maw"],
  ["Medicina Extraña", "Curious Medicine"],
  ["Relincho Blanco", "Chilling Neigh"],
  ["Relincho Negro", "Grim Neigh"],
  ["Unidad Ecuestre", "As One"],
  ["Coraza Ira", "Anger Shell"],
  ["Transportarrocas", "Rocky Payload"],
  ["Cuerpo Áureo", "Good as Gold"],
  ["Evocarrecuerdos", "Embody Aspect"],
  ["Hospitalidad", "Hospitality"],
  ["Surcavientos", "Wind Rider"],
  ["Néctar Dulce", "Supersweet Syrup"],
  ["Unísono", "Costar"],
  ["Sal Purificadora", "Purifying Salt"],
  ["Cortante", "Sharpness"],
  ["Poder Fúngico", "Mycelium Might"],
  ["Carga Cuark", "Quark Drive"],
  ["Paleosíntesis", "Protosynthesis"],
  ["Disemillar", "Seed Sower"],
  ["Cuerpo Horneado", "Well-Baked Body"],
  ["Comandar", "Commander"],
  ["Ojo Mental", "Mind's Eye"],
  ["Teraformación 0", "Teraform Zero"],
  ["General Supremo", "Supreme Overlord"],
  ["Cola Armadura", "Armor Tail"],
  ["Teracaparazón", "Tera Shell"],
  ["Teracambio", "Tera Shift"],
  ["Dinamo", "Electromorphosis"],
  ["Títere Tóxico", "Poison Puppeteer"],
  ["Capa Tóxica", "Toxic Debris"],
  ["Cadena Tóxica", "Toxic Chain"],
  ["Geofagia", "Earth Eater"],
  ["Olor Persistente", "Lingering Aroma"],
  ["Termoconversión", "Thermal Exchange"],
  ["Motor Hadrónico", "Hadron Engine"],
  ["Perro Guardián", "Guard Dog"],
  ["Rumia", "Cud Chew"],
  ["Latido Oricalco", "Orichalcum Pulse"],
  ["Oportunista", "Opportunist"],
  ["Energía Eólica", "Wind Power"],
  ["Cambio Heroico", "Zero to Hero"],
  ["Caldero Debacle", "Vessel of Ruin"],
  ["Tablilla Debacle", "Tablets of Ruin"],
  ["Abalorio Debacle", "Beads of Ruin"],
  ["Espada Debacle", "Sword of Ruin"]
]);

export const koToEn = new Map([
  ["악취", "Stench"],
  ["잔비", "Drizzle"],
  ["가속", "Speed Boost"],
  ["전투무장", "Battle Armor"],
  ["옹골참", "Sturdy"],
  ["습기", "Damp"],
  ["유연", "Limber"],
  ["모래숨기", "Sand Veil"],
  ["정전기", "Static"],
  ["축전", "Volt Absorb"],
  ["저수", "Water Absorb"],
  ["둔감", "Oblivious"],
  ["날씨부정", "Cloud Nine"],
  ["복안", "Compound Eyes"],
  ["불면", "Insomnia"],
  ["변색", "Color Change"],
  ["면역", "Immunity"],
  ["타오르는불꽃", "Flash Fire"],
  ["인분", "Shield Dust"],
  ["마이페이스", "Own Tempo"],
  ["흡반", "Suction Cups"],
  ["위협", "Intimidate"],
  ["그림자밟기", "Shadow Tag"],
  ["까칠한피부", "Rough Skin"],
  ["불가사의부적", "Wonder Guard"],
  ["부유", "Levitate"],
  ["포자", "Effect Spore"],
  ["싱크로", "Synchronize"],
  ["클리어바디", "Clear Body"],
  ["자연회복", "Natural Cure"],
  ["피뢰침", "Lightning Rod"],
  ["하늘의은총", "Serene Grace"],
  ["쓱쓱", "Swift Swim"],
  ["엽록소", "Chlorophyll"],
  ["발광", "Illuminate"],
  ["트레이스", "Trace"],
  ["천하장사", "Huge Power"],
  ["독가시", "Poison Point"],
  ["정신력", "Inner Focus"],
  ["마그마의무장", "Magma Armor"],
  ["수의베일", "Water Veil"],
  ["자력", "Magnet Pull"],
  ["방음", "Soundproof"],
  ["젖은접시", "Rain Dish"],
  ["모래날림", "Sand Stream"],
  ["프레셔", "Pressure"],
  ["두꺼운지방", "Thick Fat"],
  ["일찍기상", "Early Bird"],
  ["불꽃몸", "Flame Body"],
  ["도주", "Run Away"],
  ["날카로운눈", "Keen Eye"],
  ["괴력집게", "Hyper Cutter"],
  ["픽업", "Pickup"],
  ["게으름", "Truant"],
  ["의욕", "Hustle"],
  ["헤롱헤롱바디", "Cute Charm"],
  ["플러스", "Plus"],
  ["마이너스", "Minus"],
  ["기분파", "Forecast"],
  ["점착", "Sticky Hold"],
  ["탈피", "Shed Skin"],
  ["근성", "Guts"],
  ["이상한비늘", "Marvel Scale"],
  ["해감액", "Liquid Ooze"],
  ["심록", "Overgrow"],
  ["맹화", "Blaze"],
  ["급류", "Torrent"],
  ["벌레의알림", "Swarm"],
  ["돌머리", "Rock Head"],
  ["가뭄", "Drought"],
  ["개미지옥", "Arena Trap"],
  ["의기양양", "Vital Spirit"],
  ["하얀연기", "White Smoke"],
  ["순수한힘", "Pure Power"],
  ["조가비갑옷", "Shell Armor"],
  ["에어록", "Air Lock"],
  ["갈지자걸음", "Tangled Feet"],
  ["전기엔진", "Motor Drive"],
  ["투쟁심", "Rivalry"],
  ["불굴의마음", "Steadfast"],
  ["눈숨기", "Snow Cloak"],
  ["먹보", "Gluttony"],
  ["분노의경혈", "Anger Point"],
  ["곡예", "Unburden"],
  ["내열", "Heatproof"],
  ["단순", "Simple"],
  ["건조피부", "Dry Skin"],
  ["다운로드", "Download"],
  ["철주먹", "Iron Fist"],
  ["포이즌힐", "Poison Heal"],
  ["적응력", "Adaptability"],
  ["스킬링크", "Skill Link"],
  ["촉촉바디", "Hydration"],
  ["선파워", "Solar Power"],
  ["속보", "Quick Feet"],
  ["노말스킨", "Normalize"],
  ["스나이퍼", "Sniper"],
  ["매직가드", "Magic Guard"],
  ["노가드", "No Guard"],
  ["시간벌기", "Stall"],
  ["테크니션", "Technician"],
  ["리프가드", "Leaf Guard"],
  ["서투름", "Klutz"],
  ["틀깨기", "Mold Breaker"],
  ["대운", "Super Luck"],
  ["유폭", "Aftermath"],
  ["위험예지", "Anticipation"],
  ["예지몽", "Forewarn"],
  ["천진", "Unaware"],
  ["색안경", "Tinted Lens"],
  ["필터", "Filter"],
  ["슬로스타트", "Slow Start"],
  ["배짱", "Scrappy"],
  ["마중물", "Storm Drain"],
  ["아이스바디", "Ice Body"],
  ["하드록", "Solid Rock"],
  ["눈퍼뜨리기", "Snow Warning"],
  ["꿀모으기", "Honey Gather"],
  ["통찰", "Frisk"],
  ["이판사판", "Reckless"],
  ["멀티타입", "Multitype"],
  ["플라워기프트", "Flower Gift"],
  ["나이트메어", "Bad Dreams"],
  ["나쁜손버릇", "Pickpocket"],
  ["우격다짐", "Sheer Force"],
  ["심술꾸러기", "Contrary"],
  ["긴장감", "Unnerve"],
  ["오기", "Defiant"],
  ["무기력", "Defeatist"],
  ["저주받은바디", "Cursed Body"],
  ["치유의마음", "Healer"],
  ["프렌드가드", "Friend Guard"],
  ["깨어진갑옷", "Weak Armor"],
  ["헤비메탈", "Heavy Metal"],
  ["라이트메탈", "Light Metal"],
  ["멀티스케일", "Multiscale"],
  ["독폭주", "Toxic Boost"],
  ["열폭주", "Flare Boost"],
  ["수확", "Harvest"],
  ["텔레파시", "Telepathy"],
  ["변덕쟁이", "Moody"],
  ["방진", "Overcoat"],
  ["독수", "Poison Touch"],
  ["재생력", "Regenerator"],
  ["부풀린가슴", "Big Pecks"],
  ["모래헤치기", "Sand Rush"],
  ["미라클스킨", "Wonder Skin"],
  ["애널라이즈", "Analytic"],
  ["일루전", "Illusion"],
  ["괴짜", "Imposter"],
  ["틈새포착", "Infiltrator"],
  ["미라", "Mummy"],
  ["자기과신", "Moxie"],
  ["정의의마음", "Justified"],
  ["주눅", "Rattled"],
  ["매직미러", "Magic Bounce"],
  ["초식", "Sap Sipper"],
  ["짓궂은마음", "Prankster"],
  ["모래의힘", "Sand Force"],
  ["철가시", "Iron Barbs"],
  ["달마모드", "Zen Mode"],
  ["승리의별", "Victory Star"],
  ["터보블레이즈", "Turboblaze"],
  ["테라볼티지", "Teravolt"],
  ["아로마베일", "Aroma Veil"],
  ["플라워베일", "Flower Veil"],
  ["볼주머니", "Cheek Pouch"],
  ["변환자재", "Protean"],
  ["퍼코트", "Fur Coat"],
  ["매지션", "Magician"],
  ["방탄", "Bulletproof"],
  ["승기", "Competitive"],
  ["옹골찬턱", "Strong Jaw"],
  ["프리즈스킨", "Refrigerate"],
  ["스위트베일", "Sweet Veil"],
  ["배틀스위치", "Stance Change"],
  ["질풍날개", "Gale Wings"],
  ["메가런처", "Mega Launcher"],
  ["풀모피", "Grass Pelt"],
  ["공생", "Symbiosis"],
  ["단단한발톱", "Tough Claws"],
  ["페어리스킨", "Pixilate"],
  ["미끈미끈", "Gooey"],
  ["스카이스킨", "Aerilate"],
  ["부자유친", "Parental Bond"],
  ["다크오라", "Dark Aura"],
  ["페어리오라", "Fairy Aura"],
  ["오라브레이크", "Aura Break"],
  ["시작의바다", "Primordial Sea"],
  ["끝의대지", "Desolate Land"],
  ["델타스트림", "Delta Stream"],
  ["지구력", "Stamina"],
  ["도망태세", "Wimp Out"],
  ["위기회피", "Emergency Exit"],
  ["꾸덕꾸덕굳기", "Water Compaction"],
  ["무도한행동", "Merciless"],
  ["리밋실드", "Shields Down"],
  ["잠복", "Stakeout"],
  ["수포", "Water Bubble"],
  ["강철술사", "Steelworker"],
  ["발끈", "Berserk"],
  ["눈치우기", "Slush Rush"],
  ["원격", "Long Reach"],
  ["촉촉보이스", "Liquid Voice"],
  ["힐링시프트", "Triage"],
  ["일렉트릭스킨", "Galvanize"],
  ["서핑테일", "Surge Surfer"],
  ["어군", "Schooling"],
  ["탈", "Disguise"],
  ["유대변화", "Battle Bond"],
  ["스웜체인지", "Power Construct"],
  ["부식", "Corrosion"],
  ["절대안깸", "Comatose"],
  ["여왕의위엄", "Queenly Majesty"],
  ["내용물분출", "Innards Out"],
  ["무희", "Dancer"],
  ["배터리", "Battery"],
  ["복슬복슬", "Fluffy"],
  ["비비드바디", "Dazzling"],
  ["소울하트", "Soul-Heart"],
  ["컬리헤어", "Tangling Hair"],
  ["리시버", "Receiver"],
  ["과학의힘", "Power of Alchemy"],
  ["비스트부스트", "Beast Boost"],
  ["AR시스템", "RKS System"],
  ["일렉트릭메이커", "Electric Surge"],
  ["사이코메이커", "Psychic Surge"],
  ["미스트메이커", "Misty Surge"],
  ["그래스메이커", "Grassy Surge"],
  ["메탈프로텍트", "Full Metal Body"],
  ["스펙터가드", "Shadow Shield"],
  ["프리즘아머", "Prism Armor"],
  ["브레인포스", "Neuroforce"],
  ["불요의검", "Intrepid Sword"],
  ["불굴의방패", "Dauntless Shield"],
  ["리베로", "Libero"],
  ["볼줍기", "Ball Fetch"],
  ["솜털", "Cotton Down"],
  ["스크루지느러미", "Propeller Tail"],
  ["미러아머", "Mirror Armor"],
  ["그대로꿀꺽미사일", "Gulp Missile"],
  ["굳건한신념", "Stalwart"],
  ["증기기관", "Steam Engine"],
  ["펑크록", "Punk Rock"],
  ["모래뿜기", "Sand Spit"],
  ["얼음인분", "Ice Scales"],
  ["숙성", "Ripen"],
  ["아이스페이스", "Ice Face"],
  ["파워스폿", "Power Spot"],
  ["의태", "Mimicry"],
  ["배리어프리", "Screen Cleaner"],
  ["강철정신", "Steely Spirit"],
  ["멸망의바디", "Perish Body"],
  ["떠도는영혼", "Wandering Spirit"],
  ["무아지경", "Gorilla Tactics"],
  ["화학변화가스", "Neutralizing Gas"],
  ["파스텔베일", "Pastel Veil"],
  ["꼬르륵스위치", "Hunger Switch"],
  ["퀵드로", "Quick Draw"],
  ["보이지않는주먹", "Unseen Fist"],
  ["트랜지스터", "Transistor"],
  ["용의턱", "Dragon's Maw"],
  ["기묘한약", "Curious Medicine"],
  ["백의울음", "Chilling Neigh"],
  ["흑의울음", "Grim Neigh"],
  ["혼연일체", "As One"],
  ["분노의껍질", "Anger Shell"],
  ["바위나르기", "Rocky Payload"],
  ["황금몸", "Good as Gold"],
  ["초상투영", "Embody Aspect"],
  ["대접", "Hospitality"],
  ["바람타기", "Wind Rider"],
  ["감미로운꿀", "Supersweet Syrup"],
  ["협연", "Costar"],
  ["정화의소금", "Purifying Salt"],
  ["예리함", "Sharpness"],
  ["균사의힘", "Mycelium Might"],
  ["쿼크차지", "Quark Drive"],
  ["고대활성", "Protosynthesis"],
  ["넘치는씨", "Seed Sower"],
  ["노릇노릇바디", "Well-Baked Body"],
  ["사령탑", "Commander"],
  ["심안", "Mind's Eye"],
  ["제로포밍", "Teraform Zero"],
  ["총대장", "Supreme Overlord"],
  ["테일아머", "Armor Tail"],
  ["테라셸", "Tera Shell"],
  ["테라체인지", "Tera Shift"],
  ["전기로바꾸기", "Electromorphosis"],
  ["독조종", "Poison Puppeteer"],
  ["독치장", "Toxic Debris"],
  ["독사슬", "Toxic Chain"],
  ["흙먹기", "Earth Eater"],
  ["가시지않는향기", "Lingering Aroma"],
  ["열교환", "Thermal Exchange"],
  ["하드론엔진", "Hadron Engine"],
  ["파수견", "Guard Dog"],
  ["되새김질", "Cud Chew"],
  ["진홍빛고동", "Orichalcum Pulse"],
  ["편승", "Opportunist"],
  ["풍력발전", "Wind Power"],
  ["마이티체인지", "Zero to Hero"],
  ["재앙의그릇", "Vessel of Ruin"],
  ["재앙의목간", "Tablets of Ruin"],
  ["재앙의구슬", "Beads of Ruin"],
  ["재앙의검", "Sword of Ruin"]
]);

export const zhCnToEn = new Map([
  ["恶臭", "Stench"],
  ["降雨", "Drizzle"],
  ["加速", "Speed Boost"],
  ["战斗盔甲", "Battle Armor"],
  ["结实", "Sturdy"],
  ["湿气", "Damp"],
  ["柔软", "Limber"],
  ["沙隐", "Sand Veil"],
  ["静电", "Static"],
  ["蓄电", "Volt Absorb"],
  ["储水", "Water Absorb"],
  ["迟钝", "Oblivious"],
  ["无关天气", "Cloud Nine"],
  ["复眼", "Compound Eyes"],
  ["不眠", "Insomnia"],
  ["变色", "Color Change"],
  ["免疫", "Immunity"],
  ["引火", "Flash Fire"],
  ["鳞粉", "Shield Dust"],
  ["我行我素", "Own Tempo"],
  ["吸盘", "Suction Cups"],
  ["威吓", "Intimidate"],
  ["踩影", "Shadow Tag"],
  ["粗糙皮肤", "Rough Skin"],
  ["神奇守护", "Wonder Guard"],
  ["飘浮", "Levitate"],
  ["孢子", "Effect Spore"],
  ["同步", "Synchronize"],
  ["恒净之躯", "Clear Body"],
  ["自然回复", "Natural Cure"],
  ["避雷针", "Lightning Rod"],
  ["天恩", "Serene Grace"],
  ["悠游自如", "Swift Swim"],
  ["叶绿素", "Chlorophyll"],
  ["发光", "Illuminate"],
  ["复制", "Trace"],
  ["大力士", "Huge Power"],
  ["毒刺", "Poison Point"],
  ["精神力", "Inner Focus"],
  ["熔岩铠甲", "Magma Armor"],
  ["水幕", "Water Veil"],
  ["磁力", "Magnet Pull"],
  ["隔音", "Soundproof"],
  ["雨盘", "Rain Dish"],
  ["扬沙", "Sand Stream"],
  ["压迫感", "Pressure"],
  ["厚脂肪", "Thick Fat"],
  ["早起", "Early Bird"],
  ["火焰之躯", "Flame Body"],
  ["逃跑", "Run Away"],
  ["锐利目光", "Keen Eye"],
  ["怪力钳", "Hyper Cutter"],
  ["捡拾", "Pickup"],
  ["懒惰", "Truant"],
  ["活力", "Hustle"],
  ["迷人之躯", "Cute Charm"],
  ["正电", "Plus"],
  ["负电", "Minus"],
  ["阴晴不定", "Forecast"],
  ["黏着", "Sticky Hold"],
  ["蜕皮", "Shed Skin"],
  ["毅力", "Guts"],
  ["神奇鳞片", "Marvel Scale"],
  ["污泥浆", "Liquid Ooze"],
  ["茂盛", "Overgrow"],
  ["猛火", "Blaze"],
  ["激流", "Torrent"],
  ["虫之预感", "Swarm"],
  ["坚硬脑袋", "Rock Head"],
  ["日照", "Drought"],
  ["沙穴", "Arena Trap"],
  ["干劲", "Vital Spirit"],
  ["白色烟雾", "White Smoke"],
  ["瑜伽之力", "Pure Power"],
  ["硬壳盔甲", "Shell Armor"],
  ["气闸", "Air Lock"],
  ["蹒跚", "Tangled Feet"],
  ["电气引擎", "Motor Drive"],
  ["斗争心", "Rivalry"],
  ["不屈之心", "Steadfast"],
  ["雪隐", "Snow Cloak"],
  ["贪吃鬼", "Gluttony"],
  ["愤怒穴位", "Anger Point"],
  ["轻装", "Unburden"],
  ["耐热", "Heatproof"],
  ["单纯", "Simple"],
  ["干燥皮肤", "Dry Skin"],
  ["下载", "Download"],
  ["铁拳", "Iron Fist"],
  ["毒疗", "Poison Heal"],
  ["适应力", "Adaptability"],
  ["连续攻击", "Skill Link"],
  ["湿润之躯", "Hydration"],
  ["太阳之力", "Solar Power"],
  ["飞毛腿", "Quick Feet"],
  ["一般皮肤", "Normalize"],
  ["狙击手", "Sniper"],
  ["魔法防守", "Magic Guard"],
  ["无防守", "No Guard"],
  ["慢出", "Stall"],
  ["技术高手", "Technician"],
  ["叶子防守", "Leaf Guard"],
  ["笨拙", "Klutz"],
  ["破格", "Mold Breaker"],
  ["超幸运", "Super Luck"],
  ["引爆", "Aftermath"],
  ["危险预知", "Anticipation"],
  ["预知梦", "Forewarn"],
  ["纯朴", "Unaware"],
  ["有色眼镜", "Tinted Lens"],
  ["过滤", "Filter"],
  ["慢启动", "Slow Start"],
  ["胆量", "Scrappy"],
  ["引水", "Storm Drain"],
  ["冰冻之躯", "Ice Body"],
  ["坚硬岩石", "Solid Rock"],
  ["降雪", "Snow Warning"],
  ["采蜜", "Honey Gather"],
  ["察觉", "Frisk"],
  ["舍身", "Reckless"],
  ["多属性", "Multitype"],
  ["花之礼", "Flower Gift"],
  ["梦魇", "Bad Dreams"],
  ["顺手牵羊", "Pickpocket"],
  ["强行", "Sheer Force"],
  ["唱反调", "Contrary"],
  ["紧张感", "Unnerve"],
  ["不服输", "Defiant"],
  ["软弱", "Defeatist"],
  ["诅咒之躯", "Cursed Body"],
  ["治愈之心", "Healer"],
  ["友情防守", "Friend Guard"],
  ["碎裂铠甲", "Weak Armor"],
  ["重金属", "Heavy Metal"],
  ["轻金属", "Light Metal"],
  ["多重鳞片", "Multiscale"],
  ["中毒激升", "Toxic Boost"],
  ["受热激升", "Flare Boost"],
  ["收获", "Harvest"],
  ["心灵感应", "Telepathy"],
  ["心情不定", "Moody"],
  ["防尘", "Overcoat"],
  ["毒手", "Poison Touch"],
  ["再生力", "Regenerator"],
  ["健壮胸肌", "Big Pecks"],
  ["拨沙", "Sand Rush"],
  ["奇迹皮肤", "Wonder Skin"],
  ["分析", "Analytic"],
  ["幻觉", "Illusion"],
  ["变身者", "Imposter"],
  ["穿透", "Infiltrator"],
  ["木乃伊", "Mummy"],
  ["自信过度", "Moxie"],
  ["正义之心", "Justified"],
  ["胆怯", "Rattled"],
  ["魔法镜", "Magic Bounce"],
  ["食草", "Sap Sipper"],
  ["恶作剧之心", "Prankster"],
  ["沙之力", "Sand Force"],
  ["铁刺", "Iron Barbs"],
  ["达摩模式", "Zen Mode"],
  ["胜利之星", "Victory Star"],
  ["涡轮火焰", "Turboblaze"],
  ["兆级电压", "Teravolt"],
  ["芳香幕", "Aroma Veil"],
  ["花幕", "Flower Veil"],
  ["颊囊", "Cheek Pouch"],
  ["变幻自如", "Protean"],
  ["毛皮大衣", "Fur Coat"],
  ["魔术师", "Magician"],
  ["防弹", "Bulletproof"],
  ["好胜", "Competitive"],
  ["强壮之颚", "Strong Jaw"],
  ["冰冻皮肤", "Refrigerate"],
  ["甜幕", "Sweet Veil"],
  ["战斗切换", "Stance Change"],
  ["疾风之翼", "Gale Wings"],
  ["超级发射器", "Mega Launcher"],
  ["草之毛皮", "Grass Pelt"],
  ["共生", "Symbiosis"],
  ["硬爪", "Tough Claws"],
  ["妖精皮肤", "Pixilate"],
  ["黏滑", "Gooey"],
  ["飞行皮肤", "Aerilate"],
  ["亲子爱", "Parental Bond"],
  ["暗黑气场", "Dark Aura"],
  ["妖精气场", "Fairy Aura"],
  ["气场破坏", "Aura Break"],
  ["始源之海", "Primordial Sea"],
  ["终结之地", "Desolate Land"],
  ["德尔塔气流", "Delta Stream"],
  ["持久力", "Stamina"],
  ["跃跃欲逃", "Wimp Out"],
  ["危险回避", "Emergency Exit"],
  ["遇水凝固", "Water Compaction"],
  ["不仁不义", "Merciless"],
  ["界限盾壳", "Shields Down"],
  ["蹲守", "Stakeout"],
  ["水泡", "Water Bubble"],
  ["钢能力者", "Steelworker"],
  ["怒火冲天", "Berserk"],
  ["拨雪", "Slush Rush"],
  ["远隔", "Long Reach"],
  ["湿润之声", "Liquid Voice"],
  ["先行治疗", "Triage"],
  ["电气皮肤", "Galvanize"],
  ["冲浪之尾", "Surge Surfer"],
  ["鱼群", "Schooling"],
  ["画皮", "Disguise"],
  ["牵绊变身", "Battle Bond"],
  ["群聚变形", "Power Construct"],
  ["腐蚀", "Corrosion"],
  ["绝对睡眠", "Comatose"],
  ["女王的威严", "Queenly Majesty"],
  ["飞出的内在物", "Innards Out"],
  ["舞者", "Dancer"],
  ["蓄电池", "Battery"],
  ["毛茸茸", "Fluffy"],
  ["鲜艳之躯", "Dazzling"],
  ["魂心", "Soul-Heart"],
  ["卷发", "Tangling Hair"],
  ["接球手", "Receiver"],
  ["化学之力", "Power of Alchemy"],
  ["异兽提升", "Beast Boost"],
  ["AR系统", "RKS System"],
  ["电气制造者", "Electric Surge"],
  ["精神制造者", "Psychic Surge"],
  ["薄雾制造者", "Misty Surge"],
  ["青草制造者", "Grassy Surge"],
  ["金属防护", "Full Metal Body"],
  ["幻影防守", "Shadow Shield"],
  ["棱镜装甲", "Prism Armor"],
  ["脑核之力", "Neuroforce"],
  ["不挠之剑", "Intrepid Sword"],
  ["不屈之盾", "Dauntless Shield"],
  ["自由者", "Libero"],
  ["捡球", "Ball Fetch"],
  ["棉絮", "Cotton Down"],
  ["螺旋尾鳍", "Propeller Tail"],
  ["镜甲", "Mirror Armor"],
  ["一口导弹", "Gulp Missile"],
  ["坚毅", "Stalwart"],
  ["蒸汽机", "Steam Engine"],
  ["庞克摇滚", "Punk Rock"],
  ["吐沙", "Sand Spit"],
  ["冰鳞粉", "Ice Scales"],
  ["熟成", "Ripen"],
  ["结冻头", "Ice Face"],
  ["能量点", "Power Spot"],
  ["拟态", "Mimicry"],
  ["除障", "Screen Cleaner"],
  ["钢之意志", "Steely Spirit"],
  ["灭亡之躯", "Perish Body"],
  ["游魂", "Wandering Spirit"],
  ["一猩一意", "Gorilla Tactics"],
  ["化学变化气体", "Neutralizing Gas"],
  ["粉彩护幕", "Pastel Veil"],
  ["饱了又饿", "Hunger Switch"],
  ["速击", "Quick Draw"],
  ["无形拳", "Unseen Fist"],
  ["电晶体", "Transistor"],
  ["龙颚", "Dragon's Maw"],
  ["怪药", "Curious Medicine"],
  ["苍白嘶鸣", "Chilling Neigh"],
  ["漆黑嘶鸣", "Grim Neigh"],
  ["人马一体", "As One"],
  ["愤怒甲壳", "Anger Shell"],
  ["搬岩", "Rocky Payload"],
  ["黄金之躯", "Good as Gold"],
  ["面影辉映", "Embody Aspect"],
  ["款待", "Hospitality"],
  ["乘风", "Wind Rider"],
  ["甘露之蜜", "Supersweet Syrup"],
  ["同台共演", "Costar"],
  ["洁净之盐", "Purifying Salt"],
  ["锋锐", "Sharpness"],
  ["菌丝之力", "Mycelium Might"],
  ["夸克充能", "Quark Drive"],
  ["古代活性", "Protosynthesis"],
  ["掉出种子", "Seed Sower"],
  ["焦香之躯", "Well-Baked Body"],
  ["发号施令", "Commander"],
  ["心眼", "Mind's Eye"],
  ["归零化境", "Teraform Zero"],
  ["大将", "Supreme Overlord"],
  ["尾甲", "Armor Tail"],
  ["太晶甲壳", "Tera Shell"],
  ["太晶变形", "Tera Shift"],
  ["电力转换", "Electromorphosis"],
  ["毒傀儡", "Poison Puppeteer"],
  ["毒满地", "Toxic Debris"],
  ["毒锁链", "Toxic Chain"],
  ["食土", "Earth Eater"],
  ["甩不掉的气味", "Lingering Aroma"],
  ["热交换", "Thermal Exchange"],
  ["强子引擎", "Hadron Engine"],
  ["看门犬", "Guard Dog"],
  ["反刍", "Cud Chew"],
  ["绯红脉动", "Orichalcum Pulse"],
  ["跟风", "Opportunist"],
  ["风力发电", "Wind Power"],
  ["全能变身", "Zero to Hero"],
  ["灾祸之鼎", "Vessel of Ruin"],
  ["灾祸之简", "Tablets of Ruin"],
  ["灾祸之玉", "Beads of Ruin"],
  ["灾祸之剑", "Sword of Ruin"]
]);

export const zhTwToEn = new Map([
  ["惡臭", "Stench"],
  ["降雨", "Drizzle"],
  ["加速", "Speed Boost"],
  ["戰鬥盔甲", "Battle Armor"],
  ["結實", "Sturdy"],
  ["濕氣", "Damp"],
  ["柔軟", "Limber"],
  ["沙隱", "Sand Veil"],
  ["靜電", "Static"],
  ["蓄電", "Volt Absorb"],
  ["儲水", "Water Absorb"],
  ["遲鈍", "Oblivious"],
  ["無關天氣", "Cloud Nine"],
  ["複眼", "Compound Eyes"],
  ["不眠", "Insomnia"],
  ["變色", "Color Change"],
  ["免疫", "Immunity"],
  ["引火", "Flash Fire"],
  ["鱗粉", "Shield Dust"],
  ["我行我素", "Own Tempo"],
  ["吸盤", "Suction Cups"],
  ["威嚇", "Intimidate"],
  ["踩影", "Shadow Tag"],
  ["粗糙皮膚", "Rough Skin"],
  ["神奇守護", "Wonder Guard"],
  ["飄浮", "Levitate"],
  ["孢子", "Effect Spore"],
  ["同步", "Synchronize"],
  ["恆淨之軀", "Clear Body"],
  ["自然回復", "Natural Cure"],
  ["避雷針", "Lightning Rod"],
  ["天恩", "Serene Grace"],
  ["悠游自如", "Swift Swim"],
  ["葉綠素", "Chlorophyll"],
  ["發光", "Illuminate"],
  ["複製", "Trace"],
  ["大力士", "Huge Power"],
  ["毒刺", "Poison Point"],
  ["精神力", "Inner Focus"],
  ["熔岩鎧甲", "Magma Armor"],
  ["水幕", "Water Veil"],
  ["磁力", "Magnet Pull"],
  ["隔音", "Soundproof"],
  ["雨盤", "Rain Dish"],
  ["揚沙", "Sand Stream"],
  ["壓迫感", "Pressure"],
  ["厚脂肪", "Thick Fat"],
  ["早起", "Early Bird"],
  ["火焰之軀", "Flame Body"],
  ["逃跑", "Run Away"],
  ["銳利目光", "Keen Eye"],
  ["怪力鉗", "Hyper Cutter"],
  ["撿拾", "Pickup"],
  ["懶惰", "Truant"],
  ["活力", "Hustle"],
  ["迷人之軀", "Cute Charm"],
  ["正電", "Plus"],
  ["負電", "Minus"],
  ["陰晴不定", "Forecast"],
  ["黏著", "Sticky Hold"],
  ["蛻皮", "Shed Skin"],
  ["毅力", "Guts"],
  ["神奇鱗片", "Marvel Scale"],
  ["污泥漿", "Liquid Ooze"],
  ["茂盛", "Overgrow"],
  ["猛火", "Blaze"],
  ["激流", "Torrent"],
  ["蟲之預感", "Swarm"],
  ["堅硬腦袋", "Rock Head"],
  ["日照", "Drought"],
  ["沙穴", "Arena Trap"],
  ["幹勁", "Vital Spirit"],
  ["白色煙霧", "White Smoke"],
  ["瑜伽之力", "Pure Power"],
  ["硬殼盔甲", "Shell Armor"],
  ["氣閘", "Air Lock"],
  ["蹣跚", "Tangled Feet"],
  ["電氣引擎", "Motor Drive"],
  ["鬥爭心", "Rivalry"],
  ["不屈之心", "Steadfast"],
  ["雪隱", "Snow Cloak"],
  ["貪吃鬼", "Gluttony"],
  ["憤怒穴位", "Anger Point"],
  ["輕裝", "Unburden"],
  ["耐熱", "Heatproof"],
  ["單純", "Simple"],
  ["乾燥皮膚", "Dry Skin"],
  ["下載", "Download"],
  ["鐵拳", "Iron Fist"],
  ["毒療", "Poison Heal"],
  ["適應力", "Adaptability"],
  ["連續攻擊", "Skill Link"],
  ["濕潤之軀", "Hydration"],
  ["太陽之力", "Solar Power"],
  ["飛毛腿", "Quick Feet"],
  ["一般皮膚", "Normalize"],
  ["狙擊手", "Sniper"],
  ["魔法防守", "Magic Guard"],
  ["無防守", "No Guard"],
  ["慢出", "Stall"],
  ["技術高手", "Technician"],
  ["葉子防守", "Leaf Guard"],
  ["笨拙", "Klutz"],
  ["破格", "Mold Breaker"],
  ["超幸運", "Super Luck"],
  ["引爆", "Aftermath"],
  ["危險預知", "Anticipation"],
  ["預知夢", "Forewarn"],
  ["純樸", "Unaware"],
  ["有色眼鏡", "Tinted Lens"],
  ["過濾", "Filter"],
  ["慢啟動", "Slow Start"],
  ["膽量", "Scrappy"],
  ["引水", "Storm Drain"],
  ["冰凍之軀", "Ice Body"],
  ["堅硬岩石", "Solid Rock"],
  ["降雪", "Snow Warning"],
  ["採蜜", "Honey Gather"],
  ["察覺", "Frisk"],
  ["捨身", "Reckless"],
  ["多屬性", "Multitype"],
  ["花之禮", "Flower Gift"],
  ["夢魘", "Bad Dreams"],
  ["順手牽羊", "Pickpocket"],
  ["強行", "Sheer Force"],
  ["唱反調", "Contrary"],
  ["緊張感", "Unnerve"],
  ["不服輸", "Defiant"],
  ["軟弱", "Defeatist"],
  ["詛咒之軀", "Cursed Body"],
  ["治癒之心", "Healer"],
  ["友情防守", "Friend Guard"],
  ["碎裂鎧甲", "Weak Armor"],
  ["重金屬", "Heavy Metal"],
  ["輕金屬", "Light Metal"],
  ["多重鱗片", "Multiscale"],
  ["中毒激升", "Toxic Boost"],
  ["受熱激升", "Flare Boost"],
  ["收穫", "Harvest"],
  ["心靈感應", "Telepathy"],
  ["心情不定", "Moody"],
  ["防塵", "Overcoat"],
  ["毒手", "Poison Touch"],
  ["再生力", "Regenerator"],
  ["健壯胸肌", "Big Pecks"],
  ["撥沙", "Sand Rush"],
  ["奇跡皮膚", "Wonder Skin"],
  ["分析", "Analytic"],
  ["幻覺", "Illusion"],
  ["變身者", "Imposter"],
  ["穿透", "Infiltrator"],
  ["木乃伊", "Mummy"],
  ["自信過度", "Moxie"],
  ["正義之心", "Justified"],
  ["膽怯", "Rattled"],
  ["魔法鏡", "Magic Bounce"],
  ["食草", "Sap Sipper"],
  ["惡作劇之心", "Prankster"],
  ["沙之力", "Sand Force"],
  ["鐵刺", "Iron Barbs"],
  ["達摩模式", "Zen Mode"],
  ["勝利之星", "Victory Star"],
  ["渦輪火焰", "Turboblaze"],
  ["兆級電壓", "Teravolt"],
  ["芳香幕", "Aroma Veil"],
  ["花幕", "Flower Veil"],
  ["頰囊", "Cheek Pouch"],
  ["變幻自如", "Protean"],
  ["毛皮大衣", "Fur Coat"],
  ["魔術師", "Magician"],
  ["防彈", "Bulletproof"],
  ["好勝", "Competitive"],
  ["強壯之顎", "Strong Jaw"],
  ["冰凍皮膚", "Refrigerate"],
  ["甜幕", "Sweet Veil"],
  ["戰鬥切換", "Stance Change"],
  ["疾風之翼", "Gale Wings"],
  ["超級發射器", "Mega Launcher"],
  ["草之毛皮", "Grass Pelt"],
  ["共生", "Symbiosis"],
  ["硬爪", "Tough Claws"],
  ["妖精皮膚", "Pixilate"],
  ["黏滑", "Gooey"],
  ["飛行皮膚", "Aerilate"],
  ["親子愛", "Parental Bond"],
  ["暗黑氣場", "Dark Aura"],
  ["妖精氣場", "Fairy Aura"],
  ["氣場破壞", "Aura Break"],
  ["始源之海", "Primordial Sea"],
  ["終結之地", "Desolate Land"],
  ["德爾塔氣流", "Delta Stream"],
  ["持久力", "Stamina"],
  ["躍躍欲逃", "Wimp Out"],
  ["危險迴避", "Emergency Exit"],
  ["遇水凝固", "Water Compaction"],
  ["不仁不義", "Merciless"],
  ["界限盾殼", "Shields Down"],
  ["監視", "Stakeout"],
  ["水泡", "Water Bubble"],
  ["鋼能力者", "Steelworker"],
  ["怒火沖天", "Berserk"],
  ["撥雪", "Slush Rush"],
  ["遠隔", "Long Reach"],
  ["濕潤之聲", "Liquid Voice"],
  ["先行治療", "Triage"],
  ["電氣皮膚", "Galvanize"],
  ["衝浪之尾", "Surge Surfer"],
  ["魚群", "Schooling"],
  ["畫皮", "Disguise"],
  ["牽絆變身", "Battle Bond"],
  ["群聚變形", "Power Construct"],
  ["腐蝕", "Corrosion"],
  ["絕對睡眠", "Comatose"],
  ["女王的威嚴", "Queenly Majesty"],
  ["飛出的內在物", "Innards Out"],
  ["舞者", "Dancer"],
  ["蓄電池", "Battery"],
  ["毛茸茸", "Fluffy"],
  ["鮮艷之軀", "Dazzling"],
  ["魂心", "Soul-Heart"],
  ["捲髮", "Tangling Hair"],
  ["接球手", "Receiver"],
  ["化學之力", "Power of Alchemy"],
  ["異獸提升", "Beast Boost"],
  ["AR系統", "RKS System"],
  ["電氣製造者", "Electric Surge"],
  ["精神製造者", "Psychic Surge"],
  ["薄霧製造者", "Misty Surge"],
  ["青草製造者", "Grassy Surge"],
  ["金屬防護", "Full Metal Body"],
  ["幻影防守", "Shadow Shield"],
  ["稜鏡裝甲", "Prism Armor"],
  ["腦核之力", "Neuroforce"],
  ["不撓之劍", "Intrepid Sword"],
  ["不屈之盾", "Dauntless Shield"],
  ["自由者", "Libero"],
  ["撿球", "Ball Fetch"],
  ["棉絮", "Cotton Down"],
  ["螺旋尾鰭", "Propeller Tail"],
  ["鏡甲", "Mirror Armor"],
  ["一口飛彈", "Gulp Missile"],
  ["堅毅", "Stalwart"],
  ["蒸汽機", "Steam Engine"],
  ["龐克搖滾", "Punk Rock"],
  ["吐沙", "Sand Spit"],
  ["冰鱗粉", "Ice Scales"],
  ["熟成", "Ripen"],
  ["結凍頭", "Ice Face"],
  ["能量點", "Power Spot"],
  ["擬態", "Mimicry"],
  ["除障", "Screen Cleaner"],
  ["鋼之意志", "Steely Spirit"],
  ["滅亡之軀", "Perish Body"],
  ["遊魂", "Wandering Spirit"],
  ["一猩一意", "Gorilla Tactics"],
  ["化學變化氣體", "Neutralizing Gas"],
  ["粉彩護幕", "Pastel Veil"],
  ["飽了又餓", "Hunger Switch"],
  ["速擊", "Quick Draw"],
  ["無形拳", "Unseen Fist"],
  ["電晶體", "Transistor"],
  ["龍顎", "Dragon's Maw"],
  ["怪藥", "Curious Medicine"],
  ["蒼白嘶鳴", "Chilling Neigh"],
  ["漆黑嘶鳴", "Grim Neigh"],
  ["人馬一体", "As One"],
  ["憤怒甲殼", "Anger Shell"],
  ["搬岩", "Rocky Payload"],
  ["黃金之軀", "Good as Gold"],
  ["面影輝映", "Embody Aspect"],
  ["款待", "Hospitality"],
  ["乘風", "Wind Rider"],
  ["甘露之蜜", "Supersweet Syrup"],
  ["同台共演", "Costar"],
  ["潔淨之鹽", "Purifying Salt"],
  ["鋒銳", "Sharpness"],
  ["菌絲之力", "Mycelium Might"],
  ["夸克充能", "Quark Drive"],
  ["古代活性", "Protosynthesis"],
  ["掉出種子", "Seed Sower"],
  ["焦香之軀", "Well-Baked Body"],
  ["發號施令", "Commander"],
  ["心眼", "Mind's Eye"],
  ["歸零化境", "Teraform Zero"],
  ["大將", "Supreme Overlord"],
  ["尾甲", "Armor Tail"],
  ["太晶甲殼", "Tera Shell"],
  ["太晶變形", "Tera Shift"],
  ["電力轉換", "Electromorphosis"],
  ["毒傀儡", "Poison Puppeteer"],
  ["毒滿地", "Toxic Debris"],
  ["毒鎖鏈", "Toxic Chain"],
  ["食土", "Earth Eater"],
  ["甩不掉的氣味", "Lingering Aroma"],
  ["熱交換", "Thermal Exchange"],
  ["強子引擎", "Hadron Engine"],
  ["看門犬", "Guard Dog"],
  ["反芻", "Cud Chew"],
  ["緋紅脈動", "Orichalcum Pulse"],
  ["跟風", "Opportunist"],
  ["風力發電", "Wind Power"],
  ["全能變身", "Zero to Hero"],
  ["災禍之鼎", "Vessel of Ruin"],
  ["災禍之簡", "Tablets of Ruin"],
  ["災禍之玉", "Beads of Ruin"],
  ["災禍之劍", "Sword of Ruin"]
]);

