name: Upload v1 folder to Cloudflare R2

on:
  push:
    branches:
      - main
    paths:
      - "icons/sv/**" # v1配下のファイルが変更された場合のみ実行

jobs:
  upload-files-to-r2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # AWS CLI（S3互換CLI）をインストール
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      # Cloudflare R2に v1 フォルダ内のファイルを一括でアップロード
      - name: Upload v1 folder to Cloudflare R2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.CLOUDFLARE_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFLARE_SECRET_KEY }}
          AWS_EC2_METADATA_DISABLED: true
        run: |
          aws --debug --endpoint-url=https://${{ vars.CLOUDFLARE_ACCOUNT_ID }}.r2.cloudflarestorage.com s3 cp ./icons/sv s3://${{ vars.CLOUDFLARE_BUCKET }}/icons/sv --recursive
